### ISSUE TITLE
Allow to easily update a project created from template to a new version

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#103]
Ideally using paket - I have a rough idea how this could look like, however not yet sure if possible

**Comment by theimowski** [comment]
#123 is related - thanks to having the parts of build script i NuGet package, it's easy just to paket update

**Comment by functionalprogrammer** [comment]
Hi @isaacabraham. I think this can be closed since we now have a recipe for migrating to v2 and I assume the approach isn't going to change.
