### ISSUE TITLE
SAFE with --remoting fails to start backend. 

### ISSUE THREAD

**Issue by jarcane** [SAFE-Stack/SAFE-template#104]
Wanted to play with the `Fable.Remoting` stuff, so I spun up a new test template with `dotnet new FAKE -lang F# --remoting -o SAFE-remoting`. 

Run build.run, front end comes up but it can't get the init data for the counter because the request fails with the following error in the logs: 

```
[HPM] Error occurred while trying to proxy request /api/ICounterProtocol/getInitCounter from localhost:8080 to http://localhost:8085 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

I'm guessing this is because the backend server isn't actually starting, because further back up the logs I get this stack trace pointing to the `run app` line at the end of `Server.fs`:

```
Unhandled Exception: System.ArgumentException: The input sequence was empty.
Parameter name: source
   at Microsoft.FSharp.Collections.SeqModule.Last[T](IEnumerable`1 source)
   at Saturn.SiteMap.generate() in D:\Programowanie\Projekty\Saturn\Saturn\src\Saturn\Diagnostics.fs:line 55
   at Saturn.Application.run(IWebHostBuilder app) in D:\Programowanie\Projekty\Saturn\Saturn\src\Saturn\Application.fs:line 381
   at <StartupCode$Server>.$Server.main@() in C:\projects\SAFE-remoting\src\Server\Server.fs:line 33
Parsing ./Client.fsproj...
watch : Exited with error code -532462766
```

Not quite sure what's going on here.

**Comment by jarcane** [comment]
That did the trick. It works just fine now, no errors, and the client gets the init value from server just fine.

**Comment by Krzysztof-Cieslak** [comment]
Yes, it's known bug that happens if you don't create any `scope` nor any `controller` in the application, which I guess is happening when you use remoting.

**Comment by Krzysztof-Cieslak** [comment]
@Zaid-Ajaj I wonder if we could add my mechanism "collecting" routes at startup to Remoting to get also routes from it into site map?

**Comment by Zaid-Ajaj** [comment]
Not sure how I would do that automatically to be honest, I could just add a `write_sitemap` option to the `remoting` ce that does the same thing

**Comment by CallumVass** [comment]
Hi,

I'm getting the same issue using the latest version (0.27.1). I've added `disable_diagnostics` option but it seems to still error. When I run `fake build --target run` it seems to either start the server or the client but never both? Am I doing something wrong? Thanks
