### ISSUE TITLE
Add Elmish.Bridge as an option 

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#107]
Add https://github.com/Nhowka/Elmish.Remoting option as an alternative to Fable.Remoting.

Naming of these two may be misleading, see https://github.com/SAFE-Stack/SAFE-BookStore/pull/342 and https://github.com/Nhowka/Elmish.Remoting/issues/1 for discussions.

The option should be mutually exclusive with `--remoting` - probably would need to change type of this parameter from boolean to choice and rename it accordingly

**Comment by theimowski** [comment]
adding milestone 1.0 as changing parameter's name is a breaking change

**Comment by Nhowka** [comment]
Even with the small template there is still space for both of them to work together. The initial state could still be fetched from the server via Fable.Remoting and the new state could be calculated on the server and returned back to the client via Elmish.Remoting. That wouldn't break the existing API and would reinforce the fact that both can work together.

I'll try to make an example and release the project under a new name on this weekend.

**Comment by Nhowka** [comment]
[Renaming is ready!](https://github.com/Nhowka/Elmish.Bridge)

**Comment by isaacabraham** [comment]
@theimowski we should definitely get this in. However, playing devils advocate here, does this *need* to be in for the 1.0 milestone?

**Comment by theimowski** [comment]
@isaacabraham we can go 1.0 without that, but I'd change the parameter from `--remoting` to something more generic

**Comment by Nhowka** [comment]
@theimowski Now with the new name you could keep `--remoting` for Fable.Remoting and have `--bridge` for Elmish.Bridge. No need for breaking changes.

**Comment by theimowski** [comment]
that would mean support for both options - not sure if that's viable?

**Comment by Nhowka** [comment]
@theimowski That https://github.com/SAFE-Stack/SAFE-template/issues/107#issuecomment-399283763 gives an example of what the template would look like with both options, one is not exactly a replacement for the other.

**Comment by isaacabraham** [comment]
@Nhowka how likely is it that people will use both? It will simply matters greatly in the template to have them mutually exclusive.

**Comment by Nhowka** [comment]
@isaacabraham I have no information about someone using Elmish.Bridge, so it's all about my opinion and design abilities. I'm planning to use both on a project that involves inventory management for a supermarket.

Bridge is stateful, so I'll use it in a way to make it possible for two or more people to load the same cargo into it, with real-time updates on all workstations. Having the state on the server is something good. I'll see who has which invoice open and send updates as the items are unloaded from the truck.

But I don't need that state nor real-time features when generating a report on the end of the day. For that, the endpoints from Remoting are a great fit where I can consume the information in an organized way.

With that in mind, I believe that Remoting is better with queries that don't need a context, where Bridge is useful on transactions that need a context and workflows keeping state between steps. Both are completely independent so there's no need to design messages ignoring state when Remoting fills that space.

If the project takes off and the library gets adopted we will have real information but even with my rose-tinted glasses, I believe that Bridge won't be one size fits all.

**Comment by theimowski** [comment]
I added #110 to track changing the parameter

This issue can be now independent of planned 1.0

**Comment by isaacabraham** [comment]
Is this now completed?

**Comment by Nhowka** [comment]
I opened an [issue](https://github.com/dotnet/templating/issues/1698) to track the possibility of multiple choice arguments on the template engine. As it is now with the `--communication` it would only be possible to add or Fable.Remoting or Elmish.Bridge, but not both at the same time.

I'll try to work on that feature on the templating engine if it takes too long on their backlog so we can have that option here.

**Comment by isaacabraham** [comment]
Aha I see. I must admit that I'm still not sold on that - I can see the value (indeed, I'm doing something now that might use both!) but if it makes the template too complex, it might be better to leave it as a documentation thing on the website as a "here's how to add bridge to an existing project" etc.

**Comment by Nhowka** [comment]
There's also #172 where we could add functionalities that have more value. Bridge could do something real-time or having the server pushing the messages. That way the complexity could be more contained.

**Comment by theimowski** [comment]
I don't think we're blocked by the lack of multiple choice arguments in template engine.
Having a choice argument allows to build different options, e.g.:
* `none`
* `remoting`
* `bridge`
* `bridge-remoting`

So one can imagine potentially different combinations of those

**Comment by Nhowka** [comment]
We can do that while we have two options. Maybe that feature will be done by the time a third one appears.

I'll do something this week.

**Comment by Nhowka** [comment]
I'm revisiting this issue. I'm thinking about adding a clock that will be updated with the time sent by the server, showing that the server can send messages without a request from the client. That way it won't interfere with the other features.

Do you have a better idea?

**Comment by theimowski** [comment]
Given the complexity we already have in the template I think we want to maintain the simple communication protocol we have right now.
Is it possible to add Elmish.Bridge to the mix without interfering too much with current scheme?

**Comment by Nhowka** [comment]
With Saturn I could mostly add new things without modifying the existing
features. I'll try to do the same with Suave and Giraffe.

Em ter, 21 de mai de 2019 08:24, Tomasz Heimowski <notifications@github.com>
escreveu:

**Comment by theimowski** [comment]
Closed by #267
