### ISSUE TITLE
Change `remoting` parameter to allow adding new options

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#110]
Related to #107 

I'd vote for changing the boolean `--remoting` parameter to choice parameter with a catchy name (how about `--link` ?) and `remoting` as the only option for now.

So instead of `dotnet new SAFE --remoting` one would type `dotnet new SAFE --link remoting`

This will allow adding easily support for Elmish.Bridge in future, without "breaking" CLI invocation

**Comment by isaacabraham** [comment]
Will there be the option to add both bridge and remoting together?

**Comment by Nhowka** [comment]
Could be. The main problem is having the room without changing the counter. Maybe adding a new feature only when bridge is used with remoting could be an option.

**Comment by theimowski** [comment]
Closed by #143
