### ISSUE TITLE
Building the raw template (v0.23.0) fails when .NET Core SDK 2.1.301 is already installed

### ISSUE THREAD

**Issue by markpattison** [SAFE-Stack/SAFE-template#111]
**Repro steps**

Found on Windows 7.

1. Have .NET Core SDK 2.1.300 and 2.1.301 both installed already.
2. `dotnet new -i SAFE.Template`
3. `dotnet new SAFE` (I had `--remoting --js-deps npm` as well but I doubt it makes a difference)
4. `fake run build.fsx --target run`

**Outcome**

The following error was thrown while trying to (re)install version 2.1.300 of the SDK:

`The term 'Get-CimInstance' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling
of the name, or if a path was included, verify that the path is correct and try again.`

![image](https://user-images.githubusercontent.com/9657374/42033237-1fa16942-7ad4-11e8-9e09-8fb3c0129bf1.png)

**Expected outcome**

Build succeeds.

**Workaround**

Uninstall  .NET Core SDK 2.1.301.

**Comment by theimowski** [comment]
@matthid is there a way with FAKE 5 to specify that dotnet 2.1.300 is the minimal required version instead of requesting the exact version?

**Comment by matthid** [comment]
@theimowski I'm probably looking at the fake issue this weekend and providing a "fix" in fake, But I'm not exactly sure how it will look like. The problem is that currently there a multiple issues combined with the fact that we didn't initially understood how it is supposed to work.

**Comment by theimowski** [comment]
Is this still an issue with latest fake?

**Comment by matthid** [comment]
I think it is if you use the api according to the docs

**Comment by theimowski** [comment]
I've decided to remove "Install dotnet" step for now - https://github.com/SAFE-Stack/SAFE-template/commit/e4462c98116e9b93dbf66aefaf1335a7eca853ea 

Let's see what people think of it - if you encounter issues please reopen

**Comment by theimowski** [comment]
Using `global.json` would only move the place where the version is stored, so all the issues users have would still persist. 
Let's just see where this leads us - if removing the constraint results in even more issues, I'll reconsider adding it back to template.

**Comment by matthid** [comment]
I just re-read the initially reported bug and it probably should be reported to https://github.com/dotnet/cli as it is neither a bug in fake nor in the template.

**Comment by theimowski** [comment]
Correct, but the issue is indirectly related to the fact that the template tries to install SDK

**Comment by matthid** [comment]
Yes that is because while global json says 2.1.300 is still seems to allow 2.1.301, so we need to figure out what the rules are (ie when a difference between global json and the dotnet version is allowed) because currently fake doesn't allow any difference at all.

**Comment by theimowski** [comment]
Ok, I'm happy to add back the constraint as soon as we support this scenario in fake
