### ISSUE TITLE
Support for working on multiple SAFE projects in parallel

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#114]
Splitting #113 
Issue is that one cannot have multiple instances of apps created from SAFE template in `run` mode 

This is due to:
* fable default port 61225
* hardcoded port 8080 for web server
* hardcoded port 8085 for webpack

**Comment by matthid** [comment]
Actually let me clarify: I wouldn't mind if this scenario would NOT be supported. But I mind that the current behavior is just a full lock and I have to kill everything and start from scratch (I wouldn't mind the second instance failing if the first instance continues to work for example)

**Comment by theimowski** [comment]
Right, anyway I imagine it'd be a similar effort to allow multiple instances working in parallel, so I'd opt for that.
If it turns out hard in practice, then we can fallback to block

**Comment by theimowski** [comment]
As an afterthought IMO it's unlikely one desperately needs a scenario to work on multiple SAFE projects in parallel.
As of now, if one tries to run a second project, the errors are quite clear what's wrong:

Client:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
```

Server:
```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://0.0.0.0:8085: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
```

**Comment by matthid** [comment]
No the problem was different. As far as I remember it didn't even compile becahse it was trying to connect with the wrong fable compilation service and 'hang' forever, that's why I reported this initially

**Comment by theimowski** [comment]
Right, anyway looks like with current version of fable the behaviour is different and as a result this shouldn't be a huge issue. Running first project still works even if you try to run a second project and fail to
