### ISSUE TITLE
dotnet watch : Exited with error code 1

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#12]
happens when reloading Server app, though reload is successful

**Comment by nojaf** [comment]
I've never seen this any other way with dotnet watch. Is it possible to exit with code 0?

**Comment by theimowski** [comment]
Should be possible to exit with 0: https://github.com/aspnet/DotNetTools/issues/359
I tried verbose output, but couldn't deduce anything from that

**Comment by theimowski** [comment]
Same as in referenced issue - closing, since it's how `dotnet watch` is supposed to work - killing the process before recompiling, hence the error code `1`
