### ISSUE TITLE
Upgrade to Saturn 0.7 and drop obsolete constructs

### ISSUE THREAD

**Issue by vasily-kirichenko** [SAFE-Stack/SAFE-template#124]
![image](https://user-images.githubusercontent.com/873919/43043230-5ed06200-8d97-11e8-9ecd-98846b5299b0.png)

**Comment by isaacabraham** [comment]
I would sooner just see the router keyword removed. We're not at 1.0 yet, breaking changes like this are ok IMHO.

**Comment by theimowski** [comment]
It's also related to #66 - the locked version of Saturn (0.5) for default arguments won't have that warning.

**Comment by Krzysztof-Cieslak** [comment]
I'd strongly recommend bumping it to 0.7.x in the lock file ;-)
