### ISSUE TITLE
"intersperse" not very beginner friendly

### ISSUE THREAD

**Issue by matthid** [SAFE-Stack/SAFE-template#125]
It is used here: https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Client/Client.fs#L121
And defined here: https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Client/Client.fs#L94-L97

I feel like we should get rid of it?

**Comment by isaacabraham** [comment]
Oh, this. I thought it was something in the docs!! Happy to rename this to something more meaningful or refactor etc. @theimowski thoughts?

**Comment by theimowski** [comment]
Yes, I'm all in for making this one easier to comprehend - open for ideas

**Comment by theprash** [comment]
The name `List.join` would be analogous to `String.join`, and it should take a list as the separator: `List.join [ str ", " ]`. It could maybe be placed in another file. Or added to F# core 😃

**Comment by matthid** [comment]
Honestly even the implementation is really hard to gasp for newcomers, a lambda returning a lambda ;).

**Comment by vasily-kirichenko** [comment]
Let's search such signature on hoogle :)

**Comment by vasily-kirichenko** [comment]
https://www.haskell.org/hoogle/?hoogle=a+-%3E+%5Ba%5D+-%3E+%5Ba%5D which gives us `intersperse`...

**Comment by isaacabraham** [comment]
```fsharp
let insertSeparator sep items =
    match items with
    | [] -> []
    | head :: tail ->
        head :: (tail |> List.collect(fun item -> [ sep; item ]))
```

Is that any better?

**Comment by theprash** [comment]
Maybe this as a more understandable implementation:

```fsharp
module List =
    let join sep xs =
        match xs with
        | [] -> []
        | head :: tail ->
            [ yield head
              for x in tail do
                yield! sep
                yield x ]
```

I think it's more important for the name to be consistent with F# than with Haskell.

**Comment by matthid** [comment]
join signature is `'a -> 'a list -> 'a` while this is `'a -> 'a list -> 'a list`
(@theprash I think you mean `yield` instead of `yield!` otherwise the signature doesn't match)

**Comment by matthid** [comment]
Here are some other suggestions:

```fsharp
let rec intersperseRec sep xs =
    match xs with
    | [] -> []
    | [ head ] ->
        [ head ]
    | head :: tail ->
        head :: sep :: intersperseRec sep tail
let intersperse2 sep xs =
    let rec intersperseRec result sep xs =
        match xs, result with
        | [], result -> List.rev result
        | head :: tail, [] -> intersperseRec [head] sep tail
        | head :: tail, result ->
            intersperseRec (head :: sep :: result) sep tail
    intersperseRec [] sep xs

```

**Comment by isaacabraham** [comment]
@vasily-kirichenko how about this?

```fsharp
let second sep items =
    match items with
    | [] -> []
    | items ->
        [ for item in items do yield! [ sep; item ] ]
        |> List.skip 1
```

**Comment by theimowski** [comment]
Actually I'm thinking this code is used only for safe components credits - one probably deletes that at some point. IMO It's yet another example of something that shouldn't be in the sources, but probably referenced (yet another next to extracting common build functions in #123)

**Comment by forki** [comment]
Yes let's remove it completely and just fill the list explicitly

Tomasz Heimowski <notifications@github.com> schrieb am Do., 26. Juli 2018,
11:03:

**Comment by theprash** [comment]
@matthid 

Sorry sorry sorry, I was confusing things by remembering the wrong function name. I was actually thinking of `String.concat : string -> seq<string> -> string`, which is analogous to this `intersperse` function if you think of a string as a list of chars (which is similar to the relationship between `String.map` and `List.map`). However, there is already a `List.concat` which doesn't let you provide a list separator so this already an inconsistency within F# which doesn't help us choose a name.

**Comment by matthid** [comment]
> Yes let's remove it completely and just fill the list explicitly

Yes that's what I initially meant with "I feel like we should get rid of it". This issue is more about creating awareness to keep things ridiculously easy. The SAFE template should be a good way to start with F# overall and not be a place for F# experts. We shouldn't assume a lot of F# (or JavaScript for that matter) knowledge here.
