### ISSUE TITLE
Support Heroku

### ISSUE THREAD

**Issue by Nhowka** [SAFE-Stack/SAFE-template#136]
I made a [test project](https://github.com/Nhowka/BridgeChat) based on the current template and modified [a buildpack](https://github.com/Nhowka/dotnetcore-buildpack) to support the fake script on it. For the deploy button to work I only needed an `app.json` defining the buildpack.

Should we have that under the SAFE-Stack umbrella and an option to generate that `app.json` file on the template?

**Comment by Zaid-Ajaj** [comment]
Yes, please! 🙏 I specialized "SAFE buildpack" would be awesome

**Comment by isaacabraham** [comment]
No objection here! Would you also consider documenting it in the safe docs repo? thanks

**Comment by Nhowka** [comment]
Ok by me! Maybe the [Procfile](https://github.com/Nhowka/dotnetcore-buildpack/blob/master/bin/compile#L49-L51) generation should also be on the script to support different project names. I'll work on it and ask for help as needed.

**Comment by theimowski** [comment]
closed by #251
