### ISSUE TITLE
Simplify Webpack template

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#138]
Related to https://github.com/SAFE-Stack/docs/issues/43 - it appears as though the template file could be simplified, although I have no idea if that's still the case or even if it's possible.

**Comment by theimowski** [comment]
The webpack.config.js changed significantly in #157 but I assume it can be still simplified / better documented

**Comment by isaacabraham** [comment]
@theimowski i've had a look at the new webpack file - it looks much better now, especially as there are some comments in it.

**Comment by theimowski** [comment]
#186
