### ISSUE TITLE
Suggestion: Fallback to npm if yarn isn't installed

### ISSUE THREAD

**Issue by nojaf** [SAFE-Stack/SAFE-template#14]
It be nice if yarn wasn't a strict dependency of the template.
Changing the build.fsx to fallback to npm if yarn isn't present.

```fsharp
let npmTool = platformTool "npm" "npm.cmd"  

// ...

Target "InstallClient" (fun _ ->
  printfn "Node version:"
  run nodeTool "--version" __SOURCE_DIRECTORY__
  printfn "Npm version:"
  run npmTool "--version"  __SOURCE_DIRECTORY__
  run npmTool "install" __SOURCE_DIRECTORY__
  run dotnetCli "restore" clientPath
)
```

**Comment by forki** [comment]
Can you please push that as pr to bookstore?

Am 30.11.2017 08:25 schrieb "Florian Verdonck" <notifications@github.com>:

**Comment by theimowski** [comment]
PR in the template is also welcome :)

**Comment by theimowski** [comment]
added `--NPM` option in 0.7.0
