### ISSUE TITLE
Running fake build --target run intermittent issues

### ISSUE THREAD

**Issue by CallumVass** [SAFE-Stack/SAFE-template#142]
Hi,

Sometimes when I run `fake build --target run` only the client starts, sometimes only the server starts and then sometimes it works. Am I doing something wrong? I've looked at the task and it should run in parallel but I'm not sure why sometimes this isn't the case. I'm using version 0.27.1 of the template, so the latest version and the template I installed was `dotnet new SAFE --remoting`

I've attached 3 log outputs. One where only the server starts, one where only the client starts and one where they both start and the app launches correctly.

Thanks.

[server only.txt](https://github.com/SAFE-Stack/SAFE-template/files/2293118/server.only.txt)
[both starting.txt](https://github.com/SAFE-Stack/SAFE-template/files/2293119/both.starting.txt)
[client only.txt](https://github.com/SAFE-Stack/SAFE-template/files/2293120/client.only.txt)

**Comment by theimowski** [comment]
I think I've seen this before - when client didn't want to work it was because there was another dangling node process, after killing the other node process, client started working

**Comment by isaacabraham** [comment]
This was the other way around for me - client started but no server. Couldn't see the attempt to start it in the console.

**Comment by theimowski** [comment]
My guess would be a dotnet process hanging around?

**Comment by Zaid-Ajaj** [comment]
When this happens to me, the reason is usually that dotnet can’t access global.json file (recreating it on every build), removing the “install dotnet” block from build.fsx and using “runTool ‘dotnet’” fixed the issue

**Comment by theimowski** [comment]
I've decided to remove "Install dotnet" step for now - https://github.com/SAFE-Stack/SAFE-template/commit/e4462c98116e9b93dbf66aefaf1335a7eca853ea 

Let's see what people think of it - if you encounter issues please reopen
