### ISSUE TITLE
AppService arm template RequestIsNotValidJson

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#145]
When deploying the template to appservice with default options I get:

```
State is Accepted, completed 0 operations.
State is Running, completed 0 operations.
State is Running, completed 2 operations.
State is Running, completed 3 operations.
State is Failed, completed 4 operations.
DEPLOYMENT ERROR: BadRequest - '{
  "error": {
    "code": "RequestIsNotValidJson",
    "message": "The request cannot be interpreted as valid Json: {\"sku\":{\"name\":\"Standard_LRS\",\"tier\":\"Standard\"},\"kind\":\"Storage\",\"location\":\"westeurope\",\"tags\":{}}."
  }
}'
DEPLOYMENT ERROR: Conflict - 'Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
```

/cc @isaacabraham

**Comment by isaacabraham** [comment]
Ummmm. What's changed I wonder.

**Comment by theimowski** [comment]
"Conflict" is not the case rather here - I removed all resources before the deployment

**Comment by isaacabraham** [comment]
Let me give it a go here - might be something environment specific e.g. subscription etc. but that error suggests that the JSON is plain wrong.

**Comment by isaacabraham** [comment]
@theimowski it works here.

**Comment by isaacabraham** [comment]
@theimowski can you reproduce this issue? Or, were there any parameters you were passing through?

**Comment by theimowski** [comment]
Hm, works fine now. Strange, I think I used the defaults all the time

**Comment by isaacabraham** [comment]
Hmmm. It's possible it was just an Azure "thing".... ¯\_(ツ)_/¯
