### ISSUE TITLE
Add at least a second page so the navigation infrastructure is in place

### ISSUE THREAD

**Issue by 0x53A** [SAFE-Stack/SAFE-template#148]
One of the many things I love about elmish is how easy the navigation composes from just a few basic DUs.

I propose to add at least a second page so the whole routing layer is in place. Then it is trivial to add a third manually.

Or is this so barebones on purpose, and you don't want to prescribe any specific navigation?

**Comment by theimowski** [comment]
We had a similar discussion in #60 - the baseline question really is whether the navigation feature is a must-have for all elmish apps?

**Comment by 0x53A** [comment]
I guess not.
