### ISSUE TITLE
add SSR with react-hydrate

### ISSUE THREAD

**Issue by 0x53A** [SAFE-Stack/SAFE-template#149]
Hey, sorry for spamming you with issues right now, but I didn't want to mash it all into one.

What do you think about moving server-side-rendering from [SAFE-Bookstore](https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/src/Client/App.fs#L119) here, maybe behind a flag (``--ssr``)?

**Comment by theimowski** [comment]
I'm all in for this option - would be great to have that in the template

**Comment by theimowski** [comment]
it's now on the TODO list for docs recipes: https://github.com/SAFE-Stack/docs/issues/154
