### ISSUE TITLE
Start of process dotnet.exe failed

### ISSUE THREAD

**Issue by red-swan** [SAFE-Stack/SAFE-template#154]
### Error
Running `fake build --target run` always ends in the fake script failing to find dotnet.exe

### Details
The FAKE command `runDotNet` always starts a powershell command to install dotnet.exe to a temp folder, where the install fails, and then the exe is not found there so it fails.
- **OS**: Windows 7 Enterprise, SP1
- **dotnet version**: 2.1.301
- **fake version**: 5.0.0-rc007
- **relevant fake message**:
```
Finished (Success) 'DotNet:version' in 00:00:00.6753484
powershell -ExecutionPolicy Bypass -NoProfile -NoLogo -NonInteractive -Command "C:\Users\jdks\AppData\Local\Temp\dotnet_install_3ea75dfe585a79d60b0e3e2a5b392714.ps1 -Verbose -Channel "release-2.1" -Version "2.1.300" -NoPath; if (-not $?) { exit -1 };"
.NET Core SDK installed to C:\Users\jdks\AppData\Local\Microsoft\dotnet\dotnet.exe
C:\Users\jdks\AppData\Local\Microsoft\dotnet\dotnet.exe  restore
```
This error message always shows up on the first execution of the `runDotNet`

I assume this has something to do with the `install` function.

### Workaround
Replace `runDotNet` with the appropriate `DotNet` function (e.g. `DotNet.restore`, `DotNet.exec`).

**Comment by red-swan** [comment]
I just upgraded dotnet sdk and it still ran into the issue. Now on version `2.1.401` and the build process works after updating the `runDotNet` to bypass the install, e.g.
```
let runDotNet cmd workingDir =
    let result =
        DotNet.exec (DotNet.Options.withWorkingDirectory workingDir) cmd ""
    if result.ExitCode <> 0 then failwithf "'dotnet %s' failed in %s" cmd workingDir
```

**Comment by isaacabraham** [comment]
Can we just remove the install step from the script? I'm really not a fan of it being in there anyway. @theimowski?

**Comment by theimowski** [comment]
I've decided to remove "Install dotnet" step for now - https://github.com/SAFE-Stack/SAFE-template/commit/e4462c98116e9b93dbf66aefaf1335a7eca853ea 

Let's see what people think of it - if you encounter issues please reopen
