### ISSUE TITLE
Lock version to Fable 1 or upgrade the project to Fable 2

### ISSUE THREAD

**Issue by MangelMaxime** [SAFE-Stack/SAFE-template#158]
Yesterday we released Fable 2 and because the template isn't locking the versions users end up with Fable 2 installed on a Fable 1 repo architecture.

**Comment by forki** [comment]
@MangelMaxime @alfonsogcnunez nuget is still showing 1.3.x as fable version

Maxime Mangel <notifications@github.com> schrieb am Sa., 29. Sep. 2018,
09:10:

**Comment by MangelMaxime** [comment]
@forki  I just checked right now and both 2.0.0 are listed for me.

Also, the person on slack confirmed that after locking version to Fable 1, the template works again.

**Comment by forki** [comment]
I meant https://www.nuget.org/packages/Fable.Compiler/

Maxime Mangel <notifications@github.com> schrieb am Sa., 29. Sep. 2018,
17:33:

**Comment by MangelMaxime** [comment]
Are we using this one? I don't have it in `paket.lock` of repl2.

It's probably a transitive deps because even with Fable 1 I think I have always only used `Fable.Core` and `dotnet-fable` in the `paket.dependencies` file.

It's possible that we don't use it anymore Fable 2 got some major rewrite/rework of the folder architecture so it's possible it's now included in `dotnet-fable`.

**Comment by theimowski** [comment]
I'm working on #157 so ideally the template should be updated soon. 
In the meantime the dependencies should be locked on paket.lock level

**Comment by theimowski** [comment]
Closed by #157
