### ISSUE TITLE
"Rogue" version of SAFE Template

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#159]
There's a "second" version of the SAFE Template that can be accidentally downloaded. This template is older than the proper one and doesn't actually work for me on Linux.

1. Open a terminal
2. Install the "rogue" template: `dotnet new -i SAFE-Template` (notice the - and not .)

You get a template that looks as follows:

```
Templates                                         Short Name         Language          Tags                                 
----------------------------------------------------------------------------------------------------------------------------
Console Application                               console            [C#], F#, VB      Common/Console                       
Class library                                     classlib           [C#], F#, VB      Common/Library                       
SAFE-Stack Web App                                SAFE               F#                F#/Web/Suave/Fable/Elmish            
```

3. Now, remove the rogue template: `dotnet new -u SAFE-Template`.
4. Install the proper one: `dotnet new -i SAFE.Template`

```
Templates                                         Short Name         Language          Tags                                   
------------------------------------------------------------------------------------------------------------------------------
Console Application                               console            [C#], F#, VB      Common/Console                         
Class library                                     classlib           [C#], F#, VB      Common/Library                         
SAFE-Stack Web App v0.29.1                        SAFE               F#                F#/Web/Suave/Fable/Elmish/Giraffe/Bulma
```

Notice the different name etc..

Where is the other one coming from? Can we somehow remove it?

**Comment by theimowski** [comment]
Indeed this looks like a very early version of the template got somehow indexed as "SAFE-Template" - investigating now

**Comment by theimowski** [comment]
https://github.com/dotnet/templating/issues/1671

**Comment by theimowski** [comment]
Waiting for response from dotnet templating team - meanwhile, maybe we can try to push new versions both as `SAFE.Template` and `SAFE-Template`? What you think?

**Comment by theimowski** [comment]
I've decided to publish safe-template again, this time removing all Contents and placing a README with a note. This should hopefully make things clearer for confused users

**Comment by theimowski** [comment]
This is what a user sees if installs "rogue" version:

```
/safe # dotnet new safe
The template "SAFE-Stack Web App" was created successfully.

Processing post-creation actions...
Description: Open README.md in the editor
Manual instructions:

/safe # cat README.md
# Template obsolete

1. Uninstall this template: `dotnet new --uninstall safe-template`
2. Install correct template: `dotnet new --install SAFE.Template`

For more info, see https://github.com/SAFE-Stack/SAFE-template/issues/159
```
