### ISSUE TITLE
Wait for Saturn 1.0 before releasing SAFE Template 1.0

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#167]

**Comment by isaacabraham** [comment]
@Krzysztof-Cieslak what's your thoughts on this happening in the next 6-8 weeks?

**Comment by Krzysztof-Cieslak** [comment]
Before a certain conference in London? ;-)

I hope I'll manage to do that.

**Comment by isaacabraham** [comment]
Yes indeed ;-) Ideally we would love to be able to include that in a v1 of SAFE but there is obviously some latency between v1 Saturn release and v1 SAFE as well that needs to be considered.
