### ISSUE TITLE
Keeps reinstalling dotnet

### ISSUE THREAD

**Issue by pkese** [SAFE-Stack/SAFE-template#17]
Although I already have latest dotnet sdk installed, running `build Run` cleans some stuff and then reinstalls dotnet again -- see `Deleting contents of C:\Users\peter_000\AppData\Local\dotnetcore` down below.

    :\> build Run
    Paket version 5.125.3
    Performance:
    - Runtime: 1 second
    Building project with version: LocalBuild
    Shortened DependencyGraph for Target Run:
    <== Run
    <== RestoreServer
        <== InstallClient
            <== InstallDotNetCore
                <== Clean

    The running order is:
    - Clean
    - InstallDotNetCore
    - InstallClient
    - RestoreServer
    - Run
    Running build with 1 worker
    Starting Target: Clean
    Finished Target: Clean
    Starting Target: InstallDotNetCore (==> Clean)
    dotnet --version
    C:\Users\peter_000\AppData\Local\dotnetcore\dotnet.exe --version
    Deleting contents of C:\Users\peter_000\AppData\Local\dotnetcore
    Installing 'https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.3/dotnet-dev-win-x64.2.0.3.zip' to 'C:\Users\peter_000\AppData\Local\Temp\dotnet-dev-win-x64.2.0.3.zip'
    Installing 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0.3/dotnet-sdk-2.0.3-win-x64.zip' to 'C:\Users\peter_000\AppData\Local\Temp\dotnet-sdk-2.0.3-win-x64.zip'

**Comment by pkese** [comment]
Apparently it is because

    C:\Users\peter_000\AppData\Local\dotnetcore\dotnet.exe --version

returns `2.2.0-preview1-007736` rather than the expected `2.0.3`

But still...

**Comment by forki** [comment]
I'm looking into this right now

Am 11.12.2017 22:04 schrieb "Peter Keše" <notifications@github.com>:

**Comment by forki** [comment]
https://github.com/SAFE-Stack/SAFE-BookStore/pull/252 fixes this.

**Comment by forki** [comment]
@theimowski I applied the FAKE update in https://github.com/SAFE-Stack/SAFE-template/pull/20 but I think the template should also use the global.json model here. See the bookstore PR

**Comment by theimowski** [comment]
What's the purpose of global.json apart from keeping dotnet version?
Anyway I think I'm ok with having the global.json - how about adding that change to #20 then?

**Comment by forki** [comment]
if yiou have that global.json the cmd line calls will always take that version.

**Comment by theimowski** [comment]
@pkese could you please test with 0.2.1?
