### ISSUE TITLE
Can we kill the counter example ?

### ISSUE THREAD

**Issue by MangelMaxime** [SAFE-Stack/SAFE-template#172]
Hello guys,

IHMO the counter example is something similar to an Hello World sample and I would be really happy to kill it :)

My proposition is something like that:
*This is a similar program as default REPL example and Fulma templates*

1. A "nicely styled" input with a help text asking the user to type something in it.
2. Have a button `To upper`
3. When the user click on `To upper` set the input as disabled or loading set (the user can't edit it anymore) and send a request the server.
4. On the server, transform the input into it's upper equivalent. Add a delay >500ms so the animation is visible
5. When the client received the transformed string, display it.

Goals of the demo:
- Shows some easy-medium view composition.
- Shows how to call a Server via HTTP request
- Shows how to control the UI state when waiting for the server
- How to handle input which are not trivial in Elmish
- The user can try to add some validation to the input either on the client of the server

I created a demo in the REPL so you can have an idea of the code and adapt it if you think something needs to be adapted.

[Demo in the REPL](https://goo.gl/V1gX7a)

Gif:

![2018-11-02 22 11 29](https://user-images.githubusercontent.com/4760796/47940879-5dabfa00-deec-11e8-8a0e-2033087f11b3.gif)

Source code:
```fs
module Elmish.SimpleInput

(**
Minimal application showing how to use Elmish
You can find more info about Emish architecture and samples at https://elmish.github.io/
*)

open Fable.Core.JsInterop
open Fable.Helpers.React
open Fable.Helpers.React.Props
open Elmish
open Elmish.React
open Fulma
open Fable.PowerPack
open Fable.Import

module FakeServer =

    let toUpper (text : string) =
        promise {
            do! Promise.sleep 500
            return text.ToUpper()
        }

// MODEL

type ResultState =
    | Initial
    | Success of string
    | Failed
    | Waiting

type Model =
    { Value : string
      ResultState : ResultState }

type Msg =
    | ChangeValue of string
    | OnError of exn
    | OnServerResponse of string
    | ToUpper

let init () = { Value = ""
                ResultState = Initial }, Cmd.none

// UPDATE

let update (msg:Msg) (model:Model) =
    match msg with
    | ChangeValue newValue ->
        { model with Value = newValue }, Cmd.none
    
    | ToUpper ->
        { model with ResultState = Waiting }, Cmd.ofPromise FakeServer.toUpper model.Value OnServerResponse OnError

    | OnError exn ->
        Browser.console.error exn
        { model with ResultState = Failed }, Cmd.none

    | OnServerResponse upperText ->
        { model with ResultState = Success upperText }, Cmd.none

// VIEW (rendered with React)

let private mainContainer children =
    Section.section [ ]
        [ Columns.columns [ ]
            [ Column.column [ Column.Width(Screen.All, Column.Is6)
                              Column.Offset(Screen.All, Column.Is3) ]
                children ] ]

let private entryPanel model dispatch =
    Field.div [ ]
        [ Label.label [ ]
            [ str "Enter some text to convert" ]
          Field.div [ Field.HasAddonsRight ]
            [ Control.div [ Control.IsExpanded
                            Control.IsLoading (model.ResultState = Waiting) ]
                [ Input.input [ Input.Value model.Value
                                Input.OnChange (fun ev -> ev.Value |> ChangeValue |> dispatch )
                                Input.Placeholder "Ex: Text to convert"
                                Input.Disabled (model.ResultState = Waiting) ] ]
              Control.div [ ]
                [ Button.button [ Button.Color IsPrimary
                                  Button.OnClick (fun _ ->
                                    dispatch ToUpper
                                  ) ]
                    [ str "To upper" ] ] ] ]

let private resultPanel (resultState : ResultState) dispatch =
    match resultState with
    | Initial
    | Waiting -> ofOption None
    | Success upperText ->
        Content.content [ ]
            [ Text.span [ Modifiers [ Modifier.TextWeight TextWeight.Bold ] ]
                [ str "Result: " ]
              br [ ]
              str upperText ]
    | Failed ->
        Message.message [ Message.Color IsDanger ]
            [ Message.body [ ]
                [ str "An error occured" ] ]

let view model dispatch =
    mainContainer
        [ entryPanel model dispatch
          resultPanel model.ResultState dispatch ]

// App
Program.mkProgram init update view
|> Program.withReact "elmish-app"
|> Program.run
```

**Comment by Nhowka** [comment]
Those simple interactions with the server are nice. That could be less cramped to add an interaction with Remoting and Bridge at the same time.

**Comment by MangelMaxime** [comment]
Unfortunatly, I don't know bridge enough to propose a meaningful example. 

And looking at how the template is structured I would offer either provide Remoting or classic HTTP call :)

And have one more functionality activated if user want to add Bridge. And this functionality would presents the strengh of Bridge.

**Comment by MangelMaxime** [comment]
Fable remoting should not be a problem as it's an abstraction for doing HTTP calls.

About Fable.Reaction, it's probably a similar case as for Bridge, we need a custom feature for it because I don't think it's a good idea to use it for doing HTTP call but I can be wrong.

**Comment by EelcoMulder** [comment]
I fiddleld around with the template to add a more empty project, so that if you start a new project you don't have some many noise to remove, should I do a pull request?

**Comment by isaacabraham** [comment]
We need to be careful of not mixing an "art of the possible" with a template. The basic template should have (IMHO) a minimal amount of code in it but all the pieces wired together so you can get up and running as quickly as possible. Think of the F# console application - it's just hello world.

A larger demo should really either be a separate repo, otherwise people starting a new SAFE project have to spend time removing everything that's there already, which for a beginner is not ideal.

I'd be really happy to see another demo in the SAFE repository though!

**Comment by EelcoMulder** [comment]
Yes, I tried making it more minimal than the counter example, mainly pushing less ui. Counter example is nice for the first time you create somehting with the template, but you have to remove much code if you want to start a new blank project. Or did I miss an option and is it already there? :D

**Comment by theimowski** [comment]
@EelcoMulder there's a `--layout none` option that doesn't include Fulma and has a really small `view` function. 

I think I agree with @isaacabraham on that the template should come up with a minimal working sample that demonstrates both:
a) elmish,
b) talking to server.
So I'd either leave the counter example or change it to something which is similar with regards to complexity.

**Comment by MangelMaxime** [comment]
@isaacabraham For the "bare" option, we should at least make the code compile otherwise people would see it's red on first launch and so think it's being broken, bad "first experience", etc.

The code could be as minimal as:

```fs
let update msg model = model, Cmd.none

let view model dispatch = nothing
```

**Comment by theimowski** [comment]
With `--layout none` the amount of code to remove is small IMO.
"bare" could be an option but it should probably become a separate one - I don't see how it fits into existing parameters

**Comment by isaacabraham** [comment]
@MangelMaxime that would be about right, yes. @theimowski perhaps bare isn't necessary then - just some guidance / comments on what needs to be removed is maybe the way to go?

**Comment by isaacabraham** [comment]
@MangelMaxime would you like to put the original idea you had as a separate repository? I think it would be great to add to the safe-stack github project, and to link from the docs.

**Comment by MangelMaxime** [comment]
@isaacabraham As a template or as a ready to clone repo like bookstore ?

**Comment by Zaid-Ajaj** [comment]
@isaacabraham Speaking of the docs, is anyone maintaning that repo? Code is getting a bit outdated in there, especially with regard to remoting so I sent a [PR](https://github.com/SAFE-Stack/docs/pull/80)

**Comment by MangelMaxime** [comment]
@isaacabraham Ok i will work on something.

Can you please create a repo and add me as a maintainer of the repo ?

**Comment by isaacabraham** [comment]
@Zaid-Ajaj apologies - I was travelling the last two weeks and @theimowski has been looking at the template itself. But yes, the docs have some problems (I've actually just created a couple of issues for it over on that repo). I also just accepted your PR (without having seen your message!) - apologies again for the delay.

**Comment by isaacabraham** [comment]
@MangelMaxime can you just create a repo and get it working, we'll then invite you to the project?

**Comment by theimowski** [comment]
Closing for now - I think we kinda agreed that less is more in this case
