### ISSUE TITLE
Fulma Admin template does not open burger-menu on small screens

### ISSUE THREAD

**Issue by Zaid-Ajaj** [SAFE-Stack/SAFE-template#176]
Clicking on the burger-menu button on small screen does not show the navigation menu

### Safe template with `--layout fulma-admin` 
![fulma-admin-safe](https://user-images.githubusercontent.com/13316248/48098696-c4e3ea00-e21d-11e8-83e4-554e97090f66.gif)

### Original Bulma Admin template
![fulma-admin-original](https://user-images.githubusercontent.com/13316248/48098711-ca413480-e21d-11e8-81bd-fc2867b10816.gif)

**Comment by theimowski** [comment]
To make this work we'd need to include some more javascript: https://github.com/dansup/bulma-templates/blob/master/js/bulma.js

**Comment by theimowski** [comment]
I've been thinking about this, and came to a conclusion that if we wanted to support that, then we'd ideally implement the burger behaviour via Elmish, which implies new Message just for specific layouts (fulma-admin is not the only one affected).
This in turn would complicate the template itself, adding another conditions.

IMO, we should remove the burger altogether from the layouts, and leave it to the user if one wants to add it.

We loose consistency with bulma-templates, but gain simplicity which in this case is more important.
@Zaid-Ajaj is this fine with you?

**Comment by Zaid-Ajaj** [comment]
> IMO, we should remove the burger altogether from the layouts, and leave it to the user if one wants to add it.

Totally agree! this can always be added when necessary
