### ISSUE TITLE
Use "full" record in counter sample

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#177]
Any objection to replacing the use of `int` with a proper record? The use of a type alias, whilst cute, is somewhat confusing to newcomers and also breaks down as soon as you want to add a second field to a record etc.

**Comment by isaacabraham** [comment]
@theimowski would you be happy for me to push this through?

**Comment by theimowski** [comment]
Yes I think we should do this - together with the Auto Decoder thing with Thoth.Json
Wondering what the record should be though? an integer and a dummy string?

**Comment by isaacabraham** [comment]
Could just be the counter value - doesn't need more does it?

**Comment by theimowski** [comment]
Correct, then simply something like:

```
type Counter =
    { Value : int }
```
?

**Comment by isaacabraham** [comment]
Exactly.
