### ISSUE TITLE
Consider pinning everything in paket.dependencies?

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#180]
What are people's thoughts on pinning everything in the paket.dependencies file? This would help make things even more stable (at the cost of not getting updates more regularly). If you wanted to update a single depedency, you would unlock it temporarily, update the dependency (plus children) and then re-pin.

**Comment by forki** [comment]
Well that's not how paket is supposed to be used.

Am Do., 8. Nov. 2018, 10:12 hat Isaac Abraham <notifications@github.com>
geschrieben:

**Comment by isaacabraham** [comment]
I know. I'm thinking more from template point of view - for example, I replaced the JSON serialization package in the template for Fable 2 compat. Through the excellent FAKE script we have, it generates / updates paket scripts for specific groups etc. - but in addition to adding the new package, several others were "silently" upgraded by the paket update process. Locking would make the dependency graph slightly more stable and reduce the chance of incompatibilities being introduced (think about customers taking on SAFE project / template).

**Comment by isaacabraham** [comment]
Perhaps an alternate way to solve this is with a metapackage? Don't know.

**Comment by isaacabraham** [comment]
Lets close this then - twiddle operator is probably enough, and we can revisit in the future if needed.
