### ISSUE TITLE
Advanced Saturn template

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [SAFE-Stack/SAFE-template#181]
One of the promises of the Saturn is that it provides opinionated way to structure application, and that it provides additional tooling for scaffolding etc.

However this is not currently shown (or enabled) by current shape of the template - Saturn is used as just plug-and-play addition to Giraffe that makes code just bit more readable. In comparison Saturn template (`dotnet new saturn`) provides bit more options:
1. More stuff enabled and configured by default
2. More advanced routing, that clearly shows user where to start adding new routes
3. Default views (that's not necessary in SAFE case)
4. Migration project, that's used for creating and running DB migrations while using `dotnet saturn`
5. Helpers for data access layer that are used by scaffolded code.
6. It's not available yet, but next version will include test project showing how to do integration tests of controllers and handlers

So, clearly there is huge gap in what I think should be a starting point for Saturn application and what we currently have in SAFE template. 

I wonder what you'd think about making Saturn part here in SAFE template bit more advanced.

**Comment by isaacabraham** [comment]
Yes, interested for sure. There's always the balance between features / complexity in maintaining the template / complexity for new users - but I would really be interested in some tangible examples of what this could look like.

**Comment by theimowski** [comment]
Ideally we wouldn't replicate the features in both templates.
I'm afraid there's no ad-hoc solution for "referencing" one template from another, but maybe we can come up with some kind of workaround for that?

Brain dump of my ideas:
* Invoke `dotnet new saturn` as a post-action script from safe template
* Package features from saturn template in a nupkg and add a dependency in the template + helper build script logic. Then for new features in saturn template, we'd simply need to update the dependency version
* Use `github` paket dependencies in safe template to reach for stuff from saturn template

**Comment by theimowski** [comment]
Closing as part of old issues housekeeping - feel free to reopen if this is still relevant
