### ISSUE TITLE
Large JS files with warnings generated on clean template

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#185]
Creating and building a brand new SAFE project gives the following warning:

```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (303 KiB)
      vendors.js
      app.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

I've had a read through this but it's way over my js foo. Is there any way to minimise the load further? It would be great to remove this warning not only for confidence reasons but also because it will have a positive impact on performance (obvs).

cc: @alfonsogarciacaro @MangelMaxime

**Comment by MangelMaxime** [comment]
Yes and no :p

It's should be possible to do it by using lazy loading as stated in the end of warning. And I had a working prototype at a time but was hacky and I didn't explore it more as I am focusing on others things for now like the HMR and FormBuilder stuff.

Another solution could be try making code coming from `fable-core` or Fable libs into another chunks as we do for [node_modules](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Client/webpack.config.js#L58-L69)

But it's just a temporary solution because the more `libs`, `fable-core function` or `node_modules` you use the more the chunck will increase in size.

The real solution would be supporting `lazy` loading but it's not that easy in the context of an Elmish application.

**Comment by alfonsogarciacaro** [comment]
Not sure the chunks will solve the problem because Webpack is complaining about the **combined size**. But yeah, I think something is going on because the bundles seem to be getting bigger, I'll check.

**Comment by alfonsogarciacaro** [comment]
Some preliminary findings:

- `Thoth.Json.Decode.Auto.generateDecoder` makes reference to all types in fable-core, so you get them in the bundle even if you don't use them (e.g. BigInteger) :/
- Fulma is still quite big because it has many string literals for the class names
- Lists constructors appear everywhere (`new List(1, new List(2, new List(3, new List())))`), I'll optimize them to: `List.ofArray([1,2,3])`
- Modules from fable-core are not concatenated with the main app. When analyzing Webpack stats (in one of my apps), it complains about Elmish.Toast because `Module uses injected variables`. I suspect [the CSS imports are the cause](https://github.com/MangelMaxime/Thoth/blob/de1f1e561e466b83edb44987ba002532b227092d/src/Thoth.Elmish.Toast/Toast.fs#L13-L14).

**Comment by alfonsogarciacaro** [comment]
Yes, removing Elmish.Toast from my app saved more than 40KB in the minified bundle, so it may be a good idea to ask the user to import the CSS manually (or turn the CSS into React inline styles).

A possibility I'm thinking for Fulma would be to put the class names in the union types (with `CompiledName` attribute) so only the literal strings that are actually used get into the bundle.

I've noticed a couple of other things, but nothing that could trim lots of KBs. We need indeed a better story for lazy loading in Fable, but I would only recommend it for big apps. Also we need to be careful with the shared dependencies so they don't get duplicated in each chunk. We would need to turn things like React (and probably also `fable-core` JS files) into global values.

**Comment by forki** [comment]
40KB for the toast!? ouch

**Comment by alfonsogarciacaro** [comment]
The other solution is to add `performance: { hints: false }` to Webpack config and then the problem is solved 🙈 :trollface:

**Comment by isaacabraham** [comment]
@forki yeah but they look so cool

**Comment by forki** [comment]
yeah I don't want to miss them either

**Comment by forki** [comment]
Awesome

Am Mi., 14. Nov. 2018, 15:26 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by isaacabraham** [comment]
What's the difference between Elmish.Toast and Elmish.Toastr?

**Comment by MangelMaxime** [comment]
Elmish.Toastr is based on [toastr](https://github.com/CodeSeven/toastr).

Elmish.Toast is an based on Elmish.
It implemented from scratch with the idea to have the toast logic independent from the view library.
You have to provide a [`IRenderer`](https://github.com/MangelMaxime/Thoth/blob/master/demos/Thoth.Elmish.Demo/src/Toast.fs#L24-L68) contract so the library can know how to render the different elements.

For now, we have support for a "default" view and for Fulma.

**Comment by theimowski** [comment]
WIP #204 lowers the size a little bit:

```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (290 KiB)
      vendors.ce58f6c483b6132e0e9f.js
      style.css
      app.ce58f6c483b6132e0e9f.js
```

**Comment by isaacabraham** [comment]
Perhaps [this](https://medium.com/@kai.ito/fable-react-is-nice-but-what-about-fable-preact-517887ce2cde) is another alternative? The results look very promising and it appears a drop-in replacement.

**Comment by isaacabraham** [comment]
The following webpack plugins contribute to around 50% (if not more) of vendors.js - are they really necessary? Or have I misunderstood these (are the babel ones only used during build by node / webpack and not actually used on the client e.g. I imagine polyfill is a server-side module but has an impact on the javascript that's generated)

* "@babel/plugin-transform-runtime": "^7.2.0",
* "@babel/polyfill": "^7.0.0",
* "@babel/preset-env": "^7.2.0",
* "@babel/runtime": "^7.2.0",
* "whatwg-fetch": "^3.0.0"
* "remotedev": "^0.2.9",

**Comment by theimowski** [comment]
I think they are necessary - polyfill / whatwg-fetch are "workarounds" for older browsers, so I imagine it's a significant amount of JS to be included. `remotedev` should be included only for `debug` though - it's for the redux chrome dev tool to work

**Comment by isaacabraham** [comment]
Perhaps in the future we could have a "compat" flag in the template which does or doesn't include these elements (with a slimmed-down webpack.js) - or (as a first pass) some documentation which explains this.

**Comment by MangelMaxime** [comment]
Using `preact` instead of `react` will indeed reduce the bundle size but then not all the `react` features are supported and so people can have problems with it.

Also, it's possible to reduce `react` size by using:
```js
plugins: [
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': JSON.stringify('production')
    }
  })
],
```

when bundling for production. It will remove lot of react checks and validation used in dev mode.

**Comment by theimowski** [comment]
@MangelMaxime is this optimisation generic enough to add it as an enhancement to webpack-config-template?

**Comment by MangelMaxime** [comment]
I think so.

`NODE_ENV` is kind of a convention in JS world. At first it was for `Node.js` env but libraries use it too now, to help minimizer do their work.

**Comment by theimowski** [comment]
It would be worth experimenting and seeing how adjusting the compatibility level (browsers target) influences the total bundle size - e.g. currently as of v0.42 it's 290KB for `"targets": "> 0.25%, not dead"` which gives 89.16% browser coverage according to https://browserl.ist

Maybe we can come up with a good compromise by supporting just modern browsers, and then mention the compatibility issue in docs somewhere?

**Comment by MangelMaxime** [comment]
I just released Thoth.Elmish.Toast 1.1.0 which should saved `40KB` in production mode.

See: https://github.com/SAFE-Stack/SAFE-template/issues/185#issuecomment-445765771

**Comment by forki** [comment]
@MangelMaxime anything we need to do apart from paket update?

**Comment by MangelMaxime** [comment]
@forki No just running `paket update` should be enough. 

We only added `#if DEBUG ... #endif` in the source code.

**Comment by theimowski** [comment]
Talking about adjusting browser compatibility level it's just a matter of single field in webpack configuration, so IMO template parameter would be indeed an overkill. We should rather come up with a sensible default and document configuring the level of compatibility. Also we can look for further optimisations in used dependencies

**Comment by MangelMaxime** [comment]
I do think we can by default support all modern browser and discard Internet Explorer from this list. 

And simply add to the documentation a note about supporting older browsers.

If you want to avoid people running into bugs at runtime, you can also check the browser version display a message directly from the app. 

Fable REPL is doing this using [ReactDeviceDetect](https://github.com/fable-compiler/repl/blob/master/src/App/Libs/ReactDeviceDetect.fs)

**Comment by theimowski** [comment]
@MangelMaxime how would you define then the `"targets"` to support modern browsers and skip IE?

**Comment by MangelMaxime** [comment]
[> 0.5%, not IE 11](https://browserl.ist/?q=%3E+0.5%25%2C+not+IE+11) seems ok I guess

**Comment by theimowski** [comment]
Results for default template:

Target|Coverage|Size|Warning
------|----------|----|--------
\> 0.25%, not dead|89.16%|290KB|Yes
\> 0.5%, not IE 11|84.04%|272KB|Yes
last 2 Chrome versions|25.47%|229KB|No

So skipping IE doesn't really help that much. Out of curiosity I checked also `last 2 Chrome versions` just to see what footprint the polyfill has

**Comment by alfonsogarciacaro** [comment]
`> 0.5%, not IE 11` includes OperaMini which doesn't support many features either. I'm not sure about other mobile browsers, but I guess old iOS Safari and maybe Samsung Internet will have the same issue. As it's [not possible to specify desktop browsers only](https://github.com/browserslist/browserslist/issues/91#issuecomment-319233903) you'll need a browser like Chrome as reference if you need support for specific features.

I haven't read in full yet, but [this tweet](https://twitter.com/addyosmani/status/1082902291328360448) offers links to tutorials on how to serve different bundles for modern an old browsers (though this seems to bring another number of gotchas).

I personally would support older browsers by default and give pointers to users on how to reduce the bundle size for modern browsers if they need it.

**Comment by isaacabraham** [comment]
That would fit with my thoughts - leave the defaults as greedy and let people trim out if needed with *simple* guidance on how to do it.

**Comment by isaacabraham** [comment]
@MangelMaxime Preact is (allegedly) a "drop-in" replacement for React, but I'm not sure if that's *really* the case. Certainly that's what the documentation says.

**Comment by MangelMaxime** [comment]
@isaacabraham Preact don't support 100% of react features. 

Because JavaScript/React developers are really "imaginative" when designing their library it's possible that preact doesn't work well with them.

You can see the difference on [this](https://preactjs.com/guide/differences-to-react) page.

For example, it's says that `preact-compat` "attempts" to achieve 100% compatibility with React. The important word being attempts.

**Comment by theimowski** [comment]
Ok so it looks like it's not easy to find a low-hanging fruit to decrease the bundle size below warning level. 
Do you agree that we should add a note to docs on optimising and live with the warning in default template settings?

Regarding preact we can move the discussion to https://github.com/SAFE-Stack/SAFE-template/pull/213

**Comment by MangelMaxime** [comment]
> Do you agree that we should add a note to docs on optimising and live with the warning in default template settings?

Yes, documenting the situation is fine for me.

**Comment by alfonsogarciacaro** [comment]
BTW, I'm working on a PR for Fulma that should trim off some more KBs from the production bundle. It'd be great if someone could help with that: https://github.com/MangelMaxime/Fulma/pull/177

**Comment by theimowski** [comment]
@alfonsogarciacaro good to hear - currently the template with no Fulma (`--layout none`) bundles to 230 KB which doesn't trigger a warning, so Fulma itself is taking roughly 60KB out of 290KB in total.

Anyway this optimisation probably won't make the warning disappear yet, so I've created https://github.com/SAFE-Stack/docs/pull/95 to describe the current state

**Comment by forki** [comment]
Awesome

Am Mi., 23. Jan. 2019, 13:36 hat Tomasz Heimowski <notifications@github.com>
geschrieben:

**Comment by theimowski** [comment]
FYI I'm now working on updating Fable / Elmish / Fulma dependencies and with current prerelease versions, for default options the bundle size dropped from 290KB to **252KB** - so it's just above the WebPack warning limit

**Comment by Zaid-Ajaj** [comment]
@theimowski if the difference isn't *that* significant (only a couple of bytes) you can cheat a bit and increase the threshold that gives the warning by a couple of bytes, say to 260kb instead of 244kb, see [perfomance.maxEntrypointSize](https://webpack.js.org/configuration/performance/#performancemaxentrypointsize) hints in webpack

**Comment by kerams** [comment]
Given the overhead of Fable and the fact that the entry point currently comprises everything, wouldn't it be reasonable to increase maxEntrypointSize? Significantly, not just by a couple of bytes. What's the point of getting rid of the warning on a freshly created project if you're going to see the warning again as soon as you add a page or two and import some component?

**Comment by theimowski** [comment]
Small update on this: current (2.2) version outputs 441 KiB for default and 225 KiB (below warning limit) for minimal option
