### ISSUE TITLE
Include TaskBuilder.fs in Server side?

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#187]
Seems to be pretty much what people will need if they are doing server side programming with tasks?

**Comment by forki** [comment]
Yes please add it

Am Di., 13. Nov. 2018, 23:28 hat Isaac Abraham <notifications@github.com>
geschrieben:

**Comment by theimowski** [comment]
Isn't TaskBuilder.fs already a dependency of Giraffe?

https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Server/paket_saturn-noremoting-azure.lock#L7-L18

**Comment by isaacabraham** [comment]
Oops. Good point - didn't even notice. I wonder why I missed that.
