### ISSUE TITLE
Babel options are not passed to fable-loader

### ISSUE THREAD

**Issue by 0x53A** [SAFE-Stack/SAFE-template#188]
https://github.com/SAFE-Stack/SAFE-template/blob/52d1679879ec2b3097644f02b7942a7dd218eae9/Content/src/Client/webpack.config.js#L89-L93

As I understand this, it doesn't actually convert the fable output to lowlevel Javascript.

Or does webpack automatically run the output of the fable-loader through the babel-loader again?

**Comment by 0x53A** [comment]
I changed the preset to target ``Internet Explorer 10``. I don't actually care about IE10, but it was a good test target.

```js
            ["@babel/preset-env", {
                "targets": {
                    "browsers": ["ie 10"]
                },
                "modules": false,
                "useBuiltIns": "usage",
            }]
```

According to caniuse, ie 10 doesn't support let / const:

![grafik](https://user-images.githubusercontent.com/4236651/48631310-85a45e80-e9be-11e8-9571-6c8fb770e603.png)

But the generated output still contains ``const``:

![grafik](https://user-images.githubusercontent.com/4236651/48631356-a40a5a00-e9be-11e8-9cc6-bdfd5e506369.png)

--------



### fix

after changing the loader declaration to 

```js
            {
                test: /\.fs(x|proj)?$/,
                use: {
					loader: "fable-loader",
					options: {
						babel: CONFIG.babel,
						define: isProduction ? [] : ["DEBUG"]
					}
				},
            },
```

it didn't use const anymore:

![grafik](https://user-images.githubusercontent.com/4236651/48631620-3ad71680-e9bf-11e8-8e8a-aab27bde6170.png)

**Comment by isaacabraham** [comment]
Does this mean that things like minification weren't working as well?

**Comment by 0x53A** [comment]
minification is controlled by a different key (optimization.minimizer)

https://github.com/SAFE-Stack/SAFE-template/blob/d49115b070c4f80b7efd9b941ad402a31e653deb/Content/src/Client/webpack.config.js#L58-L71

**Comment by isaacabraham** [comment]
Fixed by #375

**Comment by isaacabraham** [comment]
@0x53A thanks very much for the PR.

**Comment by isaacabraham** [comment]
@0x53A apologies for closing - I wrongly thought that the PR had been merged!

**Comment by 0x53A** [comment]
The one in bookstore was.
