### ISSUE TITLE
Node process is hanging around after debugging session

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#191]
After stopping the "Debug SAFE App" configuration, node process is still working in background.
We need to find a way to force stop it.

@isaacabraham already mentioned that issue in the [PR](https://github.com/SAFE-Stack/SAFE-template/pull/161#issuecomment-437305968)

**Comment by isaacabraham** [comment]
We can possibly look at post launch tasks in vscode, or something through fake. The trick will be to find the event to hook into.

**Comment by theimowski** [comment]
Yup, the question is how we can stop `dotnet fable webpack-dev-server`

**Comment by isaacabraham** [comment]
I've also opened https://github.com/Microsoft/vscode-chrome-debug/issues/759

**Comment by alfonsogarciacaro** [comment]
Hmm, I gave a quick try but in my case I couldn't even stop the debugging. I guess the issue is FAKE is running Fable no the launch.json. Not sure how it can be fixed, hopefully the VS Code replies to @isaacabraham issue.

**Comment by isaacabraham** [comment]
@alfonsogarciacaro hmmm, you should be able to explicitly stop the fake process by going to the terminal window and hitting ctrl + c.

**Comment by alfonsogarciacaro** [comment]
Yes, sorry, I can do that. What I can't do is stop the debugging by clicking the red button in the VS Code debugger control :)

**Comment by isaacabraham** [comment]
Taken from the linked issue:

> please file a feature request against vscode since we do not have this functionality at the moment

So no :-( I've raised an issue in VS Code as well to track this.

@alfonsogarciacaro what do you mean by

> I guess the issue is FAKE is running Fable no the launch.json

What should we do instead?

@theimowski Am I right that the biggest issue is that people won't realise that node is running if they kill code suddenly?

**Comment by theimowski** [comment]
well in my case, when I stopped the debugging session, node process was still running meaning you could run neither `fake build` nor debug session again due to port conflicts etc

**Comment by isaacabraham** [comment]
Yeah, same thing. Note in VSCode that if you stop debugging and then hit F5 again, it'll simply re-attach to the same client app (it should start the server again though).

**Comment by isaacabraham** [comment]
@theimowski I'm not sure that we'll be able to get this in for v1 given that it's looking like it'll be dependent on a feature being added to Code.

**Comment by theimowski** [comment]
I'll try to look closer at this issue in spare time and see if there's another possible workaround

**Comment by theimowski** [comment]
Looking at that now and actually I didn't know one can ctrl+c the task in tasks window to stop node process. Maybe we can treat this as "by design" for now rather than "bug" until there's an option in vs code to get a handle of the "preLaunchTask" somehow.

To emphasise the behaviour I think we should add an explicit note at https://safe-stack.github.io/docs/feature-debugging/ pointing to the troubleshooting section - this can be easily missed as in my case

**Comment by theimowski** [comment]
Marking as "Blocked" until we have a solution from VS Code
