### ISSUE TITLE
Building solution in a docker container. 

### ISSUE THREAD

**Issue by WilliamBerryiii** [SAFE-Stack/SAFE-template#192]
Hope this is of interest to folks ... here's how to build your safestack app in a stretch based Linux container.  I'll work up the Windows Nano version after the release of RS5 and can publish the base build to dockerhub to speed things up.

* Create a new app using the `--deploy docker` flag; e.g. `dotnet new SAFE --deploy docker -o webapp`
* Add a `.dockerignore` file to the solution root with the following contents:
```docker
node_modules
paket-files
Dockerfile.*
```
* replace the content of the Dockerfile with the following:
```docker
##############################################################
# Do build env setup and app build
##############################################################

FROM microsoft/dotnet:2.1-sdk AS build-env

# Prep for Mono Install 
RUN apt-get update && apt-get install -y apt-transport-https dirmngr

# Add keys and sources lists
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" \
    | tee /etc/apt/sources.list.d/yarn.list

# gpg via apt-key has an issue where it tries to output via /dev/tty so filp the flag
RUN apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 \
    --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb https://download.mono-project.com/repo/debian stable-stretch main" \
    | tee /etc/apt/sources.list.d/mono-official-stable.list

# Install node, 7zip, yarn & mono
RUN apt-get update && apt-get install -y nodejs p7zip-full yarn mono-devel

WORKDIR /app
COPY . ./

# Install fake
RUN dotnet tool install fake-cli -g

# add dotnet tools to path to pick up fake installation 
ENV PATH="/root/.dotnet/tools:${PATH}"

# execute the bundle target
RUN fake build --target bundle 

##############################################################
# Do final image build and copy assets over
##############################################################

# adjust image base, installs and user add based on root image
FROM microsoft/dotnet:2.1-aspnetcore-runtime

COPY --from=build-env /app/deploy /app
WORKDIR /app/Server
EXPOSE 8085

# Create container user so we're not running as root
RUN useradd -ms /bin/bash app \
    && chown -R app:app /app \
    && chmod 755 /app
USER app

ENTRYPOINT [ "dotnet", "Server.dll" ]

```
* Run the docker build with: `docker build --rm -f "webapp\Dockerfile" -t {docker_user}/{docker_image}:{tag} \webapp`
* Run the container with: `docker run -it -p 8085:8085 {docker_user}/{docker_image}:{tag}`

**Comment by WilliamBerryiii** [comment]
Maintainers feel free to close if this is not of interest.

**Comment by Krzysztof-Cieslak** [comment]
Yeah, we're doing something similar for the ast-viewer project. And it's working pretty nice, even for local testing of "deployed" application while developing...
I think it may be good to add this somewhere on the docs site. 

Just one point:
Node isn't necessary on the run-time server, isn't it?

**Comment by WilliamBerryiii** [comment]
Correct (dependency of my application) ... removed it.

**Comment by theimowski** [comment]
Thanks @WilliamBerryiii  for this.
I think the question is where do we want to take it from here:
a) include in template itself (maybe when `--deploy docker` is specified?)
b) write about such possibility in docs
c) create a sample app in https://github.com/SAFE-Stack org demonstrating building using Docker
