### ISSUE TITLE
Use Webpack default minifier

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#194]
See https://github.com/SAFE-Stack/SAFE-template/issues/190#issuecomment-441476975

**Comment by alfonsogarciacaro** [comment]
Please see this too: https://github.com/SAFE-Stack/SAFE-template/issues/190#issuecomment-444041124

Also, every time I learn another mystery from Webpack/Babel configuration (and there's something new every day), I'm updating the [webpack-config-template](https://github.com/fable-compiler/webpack-config-template/blob/master/webpack.config.js). I'd recommend to align that template with SAFE-template as much as possible (not sure if using Paket Github dependencies or similar makes sense here). But please note we cannot merge them (as some people may use the webpack-config-template independently) and I can't send a PR here every time I make a change.

**Comment by theimowski** [comment]
How does webpack-config-template relate to versions of the JS dependencies (webpack, loaders, etc)? 

/cc @isaacabraham - it might be good idea to go in pair with this webpack template. To do this however, we'd need to identify and address all differences, as there are some.

**Comment by isaacabraham** [comment]
@theimowski I believe the Fable template is being deprecated in favour of the safe one anyway. Alfonso can you confirm this?

**Comment by theimowski** [comment]
I think these are two separate things:
* [fable template](https://github.com/fable-compiler/fable-templates) is a dotnet template and indeed seems to be depracated now
* [webpack-config-template](https://github.com/fable-compiler/webpack-config-template) is a different GitHub repository which I believe Fable docs point to as the go-to as of now

I'm for the idea of having a single source of truth for weback config, that's why I created #204 - so that future changes to webpack-config-template can be pulled to safe template simply by doing `paket update`

**Comment by theimowski** [comment]
Closed by #204
