### ISSUE TITLE
Update Fable libraries

### ISSUE THREAD

**Issue by 0x53A** [SAFE-Stack/SAFE-template#200]
https://github.com/fable-compiler/fable-powerpack/issues/63#issuecomment-445782911

> ATTENTION: Modules have been published as standalone packages (see #63). Fable.PowerPack won't receive more updates.

**Comment by theimowski** [comment]
We don't have direct dependency on `Fable.PowerPack`, we do have a transient dependency via `Fable.Elmish` - seems that v3.0 of Fable.Elmish drops that dependency, so when it's released we should be fine by simply update paket lock files

**Comment by theimowski** [comment]
New libraries are now released: https://fable.io/blog/Announcing-2-2.html
Changing this issue to track updating whole Fable stack

**Comment by theimowski** [comment]
Closed by #250
