### ISSUE TITLE
Deployment for GCP Kubernetes engine

### ISSUE THREAD

**Issue by mastoj** [SAFE-Stack/SAFE-template#208]
GCP has a super strong kubernetes story, Google Kubernetes Engine (GKE), and it would be nice to be able to deploy there in a simple manner.

The workflow I'm thinking is:

1. Build docker and tag it with the SHA from the last git commit
2. Push the docker image to google cloud container registry
3. Authenticate with google cloud kubernetes cluster
4. Deploy to the kubernetes cluster and expose port using command line options

That is the simplest possible thing to get it up I think. There are probably ways some of it can be generalized so the kubernetes part is similar for different kubernetes hosting providers, but that should be done when support for the second one is added.

Also, the deploy process for GKE is super basic as described above, but functional. I see this as a way for a developer to get started and then tweak to the specific use case.

**Comment by isaacabraham** [comment]
@mastoj this is fantastic - thank you very much! Adding a new deployment option for another cloud platform will be an excellent addition. There's probably a bit of testing needed for this but I think it might well be possible to get this in for v1.

There's also the [sibling repository](https://github.com/SAFE-Stack/docs) which contains the docs for this - something that would need doing for this would be to also document the new option in the template and how it impacts the FAKE script etc.. I'm happy to help you out with some pointers if needed - just let me know.
