### ISSUE TITLE
Replace successful.ok with json

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#211]
If you go to the Saturn endpoint directly with a browser that doesn't specify the content type as JSON, Giraffe falls back to using the XML serializer by default. This requires `[<AllowCLIMutable>]` attributes on all types, and without this you get a confusing error saying that your types requires a non-default constructor or something. This is very confusing for a beginner.

To work around this, we can either explain this in the docs (a good thing to do anyway), but it might also be worth replacing `Successful.OK` with `json` in Saturn / Giraffe.

**Comment by isaacabraham** [comment]
You can test this out with Firefox, for example - it doesn't explicitly send the preferred content type as JSON.

**Comment by theimowski** [comment]
With the default template? Works ok for me on Firefox 63.0.3 (64-bit) for OSX:

![screenshot 2019-01-02 at 13 49 38](https://user-images.githubusercontent.com/5909015/50592646-51fd9500-0e95-11e9-8f9f-d4d9811abe1a.png)

**Comment by isaacabraham** [comment]
Weird - must be my firefox then. Let me double check!

**Comment by isaacabraham** [comment]
I assume that that request you have highlighted if from you entering that URI in the browser directly (and *not* just loading the SAFE web app)?

**Comment by theimowski** [comment]
Ah ok now I got you - I went indirectly via http://localhost:8080/ 
The outlined issue does occur if I go to http://localhost:8080/api/init in firefox

So the `Giraffe.Serialization.Json.IJsonSerializer` comes into action only if request contains json content-type right? If so the simplest change indeed seems to be changing `Successful.OK` to `json`

**Comment by isaacabraham** [comment]
Exactly :-)
