### ISSUE TITLE
New fulma-login comes with warning

### ISSUE THREAD

**Issue by forki** [SAFE-Stack/SAFE-template#215]
![image](https://user-images.githubusercontent.com/57396/50759043-277c5500-1264-11e9-9732-df65fe871dff.png)

/cc @MangelMaxime

**Comment by MangelMaxime** [comment]
Which warning are you speaking about ? 

The extension of the one from react ?
If it's about react, then you need to look at the done and identify which part of the code generate a `p` in a `p` and change that behavior in the source code.

**Comment by forki** [comment]
yes that react thing. this is just tracking issue...

**Comment by MangelMaxime** [comment]
Or we can just replace `Text.p` with  `Text.div` ?

**Comment by theimowski** [comment]
Yep, even better if it works
