### ISSUE TITLE
missing Deploy target in template

### ISSUE THREAD

**Issue by sashang** [SAFE-Stack/SAFE-template#217]
The docs here https://safe-stack.github.io/docs/template-docker/ mention this:
```
fake build --target Deploy "DockerLoginServer=docker.io" "DockerImageName=****" "DockerUser=****" "DockerPassword=***" %*
```
but when I run that command I get an error about the missing 'Deploy' target.

**Comment by theimowski** [comment]
This is the same as https://github.com/SAFE-Stack/docs/issues/92
