### ISSUE TITLE
Template 0.46.0 not building

### ISSUE THREAD

**Issue by tforkmann** [SAFE-Stack/SAFE-template#220]
Hi,

i just updated my SAFE template to version 0.46.
Building the fresh template seems is failing.

Paket seems so be broken.

![image](https://user-images.githubusercontent.com/4168951/51864629-92411d80-2344-11e9-9fb2-cf93e41e0306.png)

Did I do anything wrong?

**Comment by theprash** [comment]
I think you need to install the latest version of .NET Core if you don't have it already.

**Comment by tforkmann** [comment]
Nope. That didn't help. Have the newest .NET Core Version v2.2.103 installed.

**Comment by forki** [comment]
Yeah message comes from within paket. But how to repro?

**Comment by rbrus** [comment]
Have you tried to clear the caches files and also even remove the paket lock? I don't remember exactly if I have removed it or not, but I probably tried and something finally helped. 
In paket lock you have set netcoreapp2.0 or 2.1 which is (as an assumption) not valid for 2.2.

**Comment by tforkmann** [comment]
Deleting of paket.lock didn't help as well.
Deleted all cache files as well.
Try with paket install. Same issue.

Even tried dotnet restore of the client and the server project.

**Comment by tforkmann** [comment]
Nope sorry.

![image](https://user-images.githubusercontent.com/4168951/51907929-91ea6600-23c8-11e9-88c1-ae799df44bd6.png)

**Comment by theimowski** [comment]
Can you please provide detailed log from `fake -v build --target run` + `dotnet info` ?

**Comment by forki** [comment]
please upload the paket.lock file

Am Di., 29. Jan. 2019 um 13:21 Uhr schrieb Tomasz Heimowski <
notifications@github.com>:

**Comment by rbrus** [comment]
Then I would also suggest to got to .paket folder and run .paket install (and clear/clean before if exists)

**Comment by tforkmann** [comment]
@forki  had to zip it...
[paket.zip](https://github.com/SAFE-Stack/SAFE-template/files/2807627/paket.zip)

**Comment by tforkmann** [comment]
@theimowski 
![image](https://user-images.githubusercontent.com/4168951/51908152-48e6e180-23c9-11e9-8e78-75f3c7d4206b.png)

**Comment by theimowski** [comment]
Right sorry my german is not that great so I misunderstood the output :) 
Try `dotnet tool update -g fake-cli`

**Comment by theimowski** [comment]
Right sorry my german is not that good so I didn't understand the output :)
I think you did `dotnet tool install` instead of `dotnet tool update -g fake-cli` - can you retry the latter?

**Comment by theimowski** [comment]
and to confirm do `fake --version`

**Comment by theimowski** [comment]
Also note if you happen to have FAKE installed by different means other than `dotnet tool` (e.g. chocolatey) you might have two different versions installed - `where fake` should show which you're using from command line

**Comment by tforkmann** [comment]
yes i think it was chocolatey
FAKE 5 - F# Make (5.0.0-rc005)
FakePath: C:\ProgramData\chocolatey\lib\fake\bin\Fake.Runtime.dll
was my respone

**Comment by tforkmann** [comment]
Nice! deinstalled chocolatey and its working now!
Thanks!

**Comment by theprash** [comment]
I am not a fan of using FAKE as a global tool as it doesn't seem robust and can result in problems like this. But I assume the plan is to move over to dotnet local tools once they are stable?

**Comment by forki** [comment]
yes that's the plan

Am Di., 29. Jan. 2019 um 15:11 Uhr schrieb Prash <notifications@github.com>:
