### ISSUE TITLE
Upgrade to Fable 2 causes cannot be serialized error

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-template#225]
I am trying to upgrade an existing project to the latest safe-template using Fable 2. However, one of the problems I run into using a simple record type that I get a 'cannot be serialized because it does not have a parameterless constructor' error. So, it basically the same as with the Counter record example, just a simple Fsharp record type.

**Comment by isaacabraham** [comment]
Hmm. Where is this occurring? On the server or client? As far as I'm aware the basic template should just work out of the box - I suspect during the manual upgrade something has gone wrong.

**Comment by halcwb** [comment]
Thanks for looking into this. I just branched the repository for which I did the upgrade: https://github.com/halcwb/GenPres2/tree/Fable2.

In the Shared lib I have a Models.fs file with the GenPres record type which is causing the issues.

**Comment by Zaid-Ajaj** [comment]
Hello there @halcwb, 

With Fable 2, you might want to change the JSON serializer on the server to use `Thoth.Json` to match the serialization library on the client for, on your server you have old `Fable.JsonConverter`:
```fs
let configureSerialization (services:IServiceCollection) =
    let fableJsonSettings = Newtonsoft.Json.JsonSerializerSettings()
    fableJsonSettings.Converters.Add(Fable.JsonConverter())
    services.AddSingleton<IJsonSerializer>(NewtonsoftJsonSerializer fableJsonSettings)
``` 
I suspect that this is the reason why serialization isn't working, latest template uses [Thoth.Json.Giraffe](https://www.nuget.org/packages/Thoth.Json.Giraffe) package as follows:
```fs
let configureServices (services : IServiceCollection) =
    services.AddGiraffe() |> ignore
    services.AddSingleton<IJsonSerializer>(Thoth.Json.Giraffe.ThothSerializer()) |> ignore
```
Can you please update and see whether that fixes the problem?

**Comment by halcwb** [comment]
Yep, I didn't following the right upgrade instructions. Thanks for answering this.
