### ISSUE TITLE
Namespaces not defined in new SAFE project

### ISSUE THREAD

**Issue by SirKastic** [SAFE-Stack/SAFE-template#228]
OS: Windows 10 version 1803
.Net version: 2.1.503
using Visual Studio Code with Ionide (fsharp, FAKE and paket)

running `fake build -i Run` in the project as it got created by `dotnet new SAFE` gives the following errors:
`C:\Program Files\dotnet\sdk\2.1.503\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETDK1045: The actual .NET SDK doesn't give support for the directing the .NET Core 2.2. Direct the .NET Core 2.1 or lesser, or use a new version of the .NET SDK compatible with .NET Core 2.2.`

Server.fsproj:
`<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.2</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="..\Shared\Shared.fs" />
        <Compile Include="Server.fs" />
    </ItemGroup>
    <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>`

Server\paket.references:
`group Server
    FSharp.Core
    Saturn
    Thoth.Json.Giraffe`

It also give the following erros on the compiler:
![capturar](https://user-images.githubusercontent.com/39251878/52672073-db2bd100-2f03-11e9-9fb1-679ecdfcada7.PNG)

**Comment by theimowski** [comment]
We haven't yet updated the docs, but newest template uses .NET SDK 2.2 - can you try upgrading and see if that fixes the issue?

**Comment by SirKastic** [comment]
Yeah, updated to .NET 2.2.104 and now everything is running. Thanks and sorry to bother

**Comment by theimowski** [comment]
Sure, you're welcome!
