### ISSUE TITLE
Maybe make testing of a running webserver possible?

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-template#229]
I have written a [blog post](https://informedica.nl/?p=100) that proposes a solution to start up the webserver and run tests or code using the running web server in the FSI. This enables interactive experimentation and writing tests that uses the actual running webserver to check the responses to particular requests.
Maybe, some sort of testing template could be added to the SAFE-stack?

**Comment by theimowski** [comment]
Do you mean tests for the template itself or tests for projects created from the template?

**Comment by theimowski** [comment]
closing in favour of #263
