### ISSUE TITLE
Sourcemap breakpoints behave differently outside of Docker

### ISSUE THREAD

**Issue by Alex2357** [SAFE-Stack/SAFE-template#233]
In this great video https://channel9.msdn.com/Events/NDC/NDC-Oslo-2017/C9L13 at 16.15 Alfonso shows that he can set breakpoints in App.fs file and they actually work. When I set breakpoint in Client.fs?d433d with F# code, the breakpoints appear in Client.fs with Javascript code in corresponding code location.
It kind'a works but not as awesome as it was in the video.

Is that possible to make it work the same way as in the video?

**Comment by isaacabraham** [comment]
Hi @Alex2357. Is this using the standard SAFE template, and are you debugging in Chrome directly or using e.g. VS Code?

**Comment by Alex2357** [comment]
> Hi @Alex2357. Is this using the standard SAFE template, and are you debugging in Chrome directly or using e.g. VS Code?

The template was created using `dotnet new SAFE --deploy docker`, I wanted to try use just Chrome for Debug without VSCode. 

I have tried to use VSCode and yes, it works, but it was slow. I was hopping that it would be faster in Chrome without VSCode.

**Comment by theimowski** [comment]
What made the debugging experience in VSCode slow? Maybe there's something that could be improved?

Also could you elaborate on `not as awesome as it was in the video` ? - what's missing in current configuration compared to the video?

**Comment by Alex2357** [comment]
> What made the debugging experience in VSCode slow? Maybe there's something that could be improved?
> 
> Also could you elaborate on `not as awesome as it was in the video` ? - what's missing in current configuration compared to the video?

Have you watched the video? You need to watch just 25 seconds from 16.15 to 16.40. Then try do what I have described.
When I said not as awesome I meant that I was not able to set breakpoint in Chrome in the F# file at all. When I try to do that the breakpont was added into the corresponding javascript file at the corresponding code location but not in the F# file as in the video. 

It reminded me the debugging for typescript code in the past. You set brakpoint in the typescript file but it actually added in the corresponding Javascript file into corresponding location,

**Comment by alfonsogarciacaro** [comment]
I don't know. There's nothing specific in Fable about the breakpoints besides the sourcemaps. It can be tricky to get the configuration right in VS Code sometimes, I think this one in latest fulma-demo works: https://github.com/MangelMaxime/fulma-demo/blob/74f60dd511ffd2d63752cc4e2861e12f6b7de33b/.vscode/launch.json#L9-L12

**Comment by isaacabraham** [comment]
The breakpoints in Code and Chrome should actually be the same. Hmmm.

**Comment by isaacabraham** [comment]
Reopening - if you're seeing different behaviour inside and outside of docker this looks like a bug, somewhere.

**Comment by theimowski** [comment]
I'm trying to understand the difference here.
Indeed seems it's working better when running inside a container - there are `*.js.map` files there.
Still not sure how source mapping works for "non-production" mode, but apparently it depends on [WebPack devtool configuration](https://webpack.js.org/configuration/devtool/) 
Also it might behave differently if running from `fake build -t run` vs running as a task from VS Code.

> I confirm it works in the fulma-demo but doesn't work the project created using dotnet new SAFE --deploy docker if I run the project using fake build --target run.

@Alex2357 did it work properly for you when run fulma-demo via VS Code launch or via `fake`?

**Comment by Alex2357** [comment]
@theimowski fulma-demo & 'dotnet new SAFE --deploy docker' have different build /fake pipeline as I remember. The steps are different. It wasn't easy to notice what could cause this.

**Comment by theimowski** [comment]
Fable 2.2 comes with improvements for source maps: https://fable.io/blog/Announcing-2-2.html
Let's come back to this issue when template gets updated to latest Fable - maybe that helps somehow

**Comment by theimowski** [comment]
I tried to revisit this issue with new Fable bits - it seems there's still a difference in behaviour for sourcemaps between `development` and `production` modes, where `production` experience is more user-friendly. 
If someone's into webpack stuff, any help would be welcome

**Comment by alfonsogarciacaro** [comment]
The name of the concerning webpack option is a bit misleading: [devtool](https://webpack.js.org/configuration/devtool/). The recommendation is usually to use [a faster method during development](https://github.com/fable-compiler/Fable/blob/e0a0e43a9b503bbdd5e1b0077a2a668ad05815d0/src/Fable.Cli/ProjectCracker.fs#L103-L123)  to get faster recompilation times, that's likely why you see differences with the production sourcemaps.
