### ISSUE TITLE
Integration with ProjectScaffold

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-template#234]
Are there any plans, ideas to integrate this framework with [ProjectScaffold](https://github.com/fsprojects/ProjectScaffold)?

That would give some nice benefits like a test project setup, more general build file, and the ability to generate source code documents using FSharp.Formatting.

**Comment by theimowski** [comment]
I don't think we want to follow that route, as SAFE is works only on .net core and new .net sdk where dotnet templates is becoming de facto a standard for bootstrapping projects. 
Curious to hear other opinions though

**Comment by halcwb** [comment]
Maybe I was to literal with suggesting that SAFE-Stack should become an actual ProjectScaffold sub project. But I would like to have a nice Documentation and Testing setup like exists in ProjectScaffold. I know there is some thought in porting the Formatting lib to .net core.

**Comment by theimowski** [comment]
Yes it would be nice to have a setup for Tests. Not sure about Documentation though, since SAFE is an application rather than a general-purpose library

**Comment by theimowski** [comment]
closing in favour of #263
