### ISSUE TITLE
Feature Request - GraphQL

### ISSUE THREAD

**Issue by purkhusid** [SAFE-Stack/SAFE-template#238]
I think it would be a good move to add a GraphQL option to the template. GraphQL keeps on growing and I think adding and example of how to use GraphQL with Fable/Elmish could capture a new audience for Fable/Elmish.

**Comment by jonathanstiansen** [comment]
I think it's also neat to notice that GraphQL works great with Typing! Which f# loves :-)

**Comment by Alex2357** [comment]
After watching this https://vimeo.com/131196782 I started to think about REST differently. 
I started to think that REST is exposing too much, graphql brings this to the next level.
Do you really think that it is a good idea to use GraphQL?

**Comment by functionalprogrammer** [comment]
Hi @isaacabraham. This issue can be closed since we will write a recipe on this shortly. :)

**Comment by theimowski** [comment]
Added GraphQL to the TODO list for recipes in docs https://github.com/SAFE-Stack/docs/issues/154
