### ISSUE TITLE
Consider setting the CurrentDirectory in the template code

### ISSUE THREAD

**Issue by baronfel** [SAFE-Stack/SAFE-template#239]
Often when an application is run under the ionide debugger, the `System.Environment.CurrentDirectory` is set to that of the debugging instance, which is somewhere inside the user home. This causes relative-path file lookups, like a bundled sqlite database for example, to fail. Should the template include code to set the `System.Environment.CurrentDirectory` to the location of the currently-executing assembly(`System.Reflection.Assembly.GetExecutingAssembly().Location`)?  This was inspired by a troubleshooting session I had this morning with a Slack user in #web.

**Comment by theimowski** [comment]
I'm not entirely convinced - it sounds more like a specific rather than a general case.
Is it Ionide that sets the working directory?

**Comment by baronfel** [comment]
I did some digging and from what I can see Ionide just requests the coreclr debugger be started with a particular dll as the entry point, and the currently-opened workspace as the currently directory, so I'm not sure where the hijacking is coming from. I do agree that it makes more sense to solve the mystery of what's setting the current directory, though.

**Comment by theimowski** [comment]
any update to this?
