### ISSUE TITLE
Use a Shared project instead of including shared files individually

### ISSUE THREAD

**Issue by theprash** [SAFE-Stack/SAFE-template#255]
I propose adding a `Shared/Shared.fsproj` file, referenced from Server and Client projects. Even though there is only one shared file in the initial template, I have seen projects take this template and add many shared files in a way that doesn't scale very well.

With a Shared project file, if there are multiple shared files, they don't have to be included in both Server and Client in the correct order: There is one source of truth for file ordering.

Is there any reason this isn't the approach already taken by the template?

**Comment by theimowski** [comment]
I've been thinking about that back in a day - just wasn't sure if that scenario is supported by Fable.
But if that works I'm all in for that change

**Comment by theprash** [comment]
Can this be re-opened? The change was reverted due to #258, which seems to be an issue only affecting Linux.

Using Shared files like this still feels very wrong to me. We are teaching people that this is how to handle project dependencies in F#. I have just seen someone do this between two .NET assemblies within a SAFE project.

@iNecas, could you help us solve this? Does using a shared project between Fable and .NET still cause issues for you?

**Comment by theprash** [comment]
#258 seems to be caused by this Fable bug: https://github.com/fable-compiler/Fable/issues/1953. It looks like it was happening intermittently and it's mostly stopped happening. So I'm going to open another PR making this change again.

**Comment by theimowski** [comment]
Yes, I'm all in for having Shared as an fsproj - actually that's what has been done in the v2_minimal branch
