### ISSUE TITLE
Quickstart broken after making the Shared.fsproj

### ISSUE THREAD

**Issue by iNecas** [SAFE-Stack/SAFE-template#258]
How to reporduce:

1. follow [quickstart guide](https://safe-stack.github.io/docs/quickstart/)
2. `fake build --target run` fails with this (and couple of other similar errors):
```
ERROR in ./src/Client/Client.fs
Module Error (from ./node_modules/fable-loader/index.js):
/home/inecas/active/projects/fsharp/my/iii/src/Client/Client.fs(12,5): (12,11) error FSHARP: The namespace or module 'Shared' is not defined.
 @ ./src/Client/Client.fsproj 1:0-28 1:0-28
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./src/Client/Client.fsproj
```

Reproduced on Linux.

Reverting https://github.com/SAFE-Stack/SAFE-template/pull/256/files fixed the issue for me

**Comment by theimowski** [comment]
Thanks, I reverted the Shared.fsproj change in v1.5 - should be fixed now

**Comment by iNecas** [comment]
Thank you!
