### ISSUE TITLE
Add template projects for tests

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#263]
[SAFE BookStore](https://github.com/SAFE-Stack/SAFE-BookStore/tree/master/test) demonstrates concepts of "UITests" (Selenium + canopy) and "ServerTests" (Expecto)
I think we could also consider "ClientTests" consisting of [jest](https://jestjs.io/) or other JS testing library (I think `jest` is most common across Fable users)

Comments are welcome

**Comment by Zaid-Ajaj** [comment]
There are three possible test projects
 - Server side unit tests project (using Expecto)
 - Client side unit tests (maybe [Fable.Mocha](https://github.com/Zaid-Ajaj/Fable.Mocha)?)
 - Intergration tests for both which can be either 
   -  a dotnet application using canopy + expecto
   - A node.js application (written in Fable) using a headless browser (maybe [Cypress](https://www.cypress.io/)?)

**Comment by theimowski** [comment]
Closing - we have server, client and shared tests now in v2.
Might reconsider adding Integration / End-to-end tests at one point.
