### ISSUE TITLE
Add support for authentication into the template

### ISSUE THREAD

**Issue by bruinbrown** [SAFE-Stack/SAFE-template#273]
# Introduction
Given that we're aiming to reduce the overall complexity of the SAFE template by removing Suave as per #271 this lets us start to include more functionality that cuts across all parts of the stack, i.e. front end and back end. I think the most noticeable of these is authentication. Given how many applications need authentication to be added to them, it seems like this could be a significant time saver for many.

# Proposal
I'm proposing that we add a number of new configuration options to the template similar to what ASP.Net core does with the MVC template. The MVC template allows for authentication with one of either (as documented [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore22#tabpanel_CeZOj-G++Q-3_netcore22)):
1. No auth (default)
1. Individual user accounts
1. Individual accounts in Azure AD B2C
1. Single organisation in Azure AD
1. Multitenant in Azure AD
1. Windows Auth

Given the aims of SAFE with its intention of currently being cloud agnostic, I'm not sure of the benefits of supporting Azure AD and I'm not sure Windows auth is worth the effort at this point in time. This leaves us with individual user accounts, which opens up a few more questions.

1. Which approach should we be encouraging when using authentication? Should we be telling people to use cookies or tokens? Since we've got a SPA with Fable, a default approach might be to use tokens but as we deploy the Fable app onto the same app server as the web API, this means that cookies are a valid option as long as they are configured correctly (IETF guidance [here](https://tools.ietf.org/html/draft-parecki-oauth-browser-based-apps-02#section-6.1) and blog discussing how to implement this in ASP.Net Core [here](https://leastprivilege.com/2019/01/18/an-alternative-way-to-secure-spas-with-asp-net-core-openid-connect-oauth-2-0-and-proxykit/)
1. Should we be using libraries like ASP.Net core identity to handle the core of the identity storage and authentication? This would simplify a lot of the code we'd need to add but would require the use of EF Core unless we were to provide a replacement storage provider
1. If we choose to add individual user accounts using a username and password, where should we store the user data? My initial thought would be to store this in a SQLite database or similar
1. If we add individual user accounts, should we add a user account management section to the template which would allow the end users who registered the opportunity to change things like email addresses etc?
1. If we do add individual account management pages should these be added as pages in the Fable side of the application and add Elmish.Browser to the template with multiple pages or should we render them server side using the Giraffe view engine?
1. Should we instead be encouraging the use of social providers like Facebook, Twitter etc?
1. Should we allow for management of user accounts with social providers? E.g. linking a Facebook login to an existing email address login and vice versa or removing associated logins from an account

Based on the number of people developing SAFE apps who may not have prior experience of the security considerations which are relevant when developing features such as authentication and authorisation, this feels like something we should implement to provide guidance to the community on best practices. I'm interested in hearing any other thoughts on this or whether there's anything else we should consider or include as part of this and I would be happy to lead the work on implementing this within the template.

**Comment by isaacabraham** [comment]
Definitely needed, although I think this might be something we look at within the context of a secondary tool, script or document - I'm not sure about putting it in the template itself though if our goal is to simplify it.

I also remember the old aspnet mvc days, creating a new app and it was filled with all sorts of fluff so this should probably to be an opt-in.

**Comment by bruinbrown** [comment]
> I also remember the old aspnet mvc days, creating a new app and it was filled with all sorts of fluff so this should probably to be an opt-in.

I agree that it should definitely be an opt in process rather than the default. I also agree that the old ASP.Net templates generated a lot of fluff which made it difficult to see exactly what was happening but a lot of that fluff was ultimately required as part of a user identity setup

> Definitely needed, although I think this might be something we look at within the context of a secondary tool, script or document - I'm not sure about putting it in the template itself though if our goal is to simplify it.

Also a valid consideration, my reasoning for including this as part of the core template is for 2 main reasons
1. Identity is a fundamental aspect of many apps and so retrospectively adding it may prove to be a complex procedure
1. It's easy to get something slightly wrong when developing a security solution which then compromises the overall security of the application. By providing it in the template we can minimise the risk that something goes wrong at a later date. For example, if it was a document which somebody doesn't follow exactly then it may expose other vulnerabilities

**Comment by Freymaurer** [comment]
Hello everyone,

I can only say how much i would have loved to have such options for the SAFE template. But now i tried to implement a user management by myself and without any prior knowledge about the topic.

I don't know if this helps anyone or if something like this already exists (personally i was not able to find something besides the [tabula-rasa](https://github.com/Zaid-Ajaj/tabula-rasa) example).

But i came up with a [user management](https://github.com/Freymaurer/UserManagement) and with a [multi-url user management](https://github.com/Freymaurer/UserManagement-Multi-Url-Template). 

Please excuse if this is the wrong place to post this, or if it is not needed.

**Comment by isaacabraham** [comment]
@Freymaurer hey. Thanks so much for doing this! We'll definitely have a look at this - if you're happy to do so, we could add this as a first step as a sample project for people to look at, and then consider if / how to add to the template at a later date.

**Comment by Freymaurer** [comment]
@isaacabraham , i really appreciate your kind words and would love to see this as an example project.

**Comment by Zaid-Ajaj** [comment]
Instead of adding pre-implemented auth machanism, I believe it would much much better to write guides in the docs on how to *add* them to an existing or brand new SAFE template and explaining the reasoning and train of thought between the steps and why things are done this way. Having many more examples demonstrating security implementations that follow each guide would be a great addition. 

In other words, it is not about telling people to use tokens or to use cookies but explain to them when either approaches should be or should not be considered. 

The template will always have all kinds of requirements, keep adding things to it and it will become a giant mess, just the same as the old template wizard of ASP.NET applications which gave you an `AccountController`/`ApplicationUser` abstractions that you would often have to delete from moving on

> Based on the number of people developing SAFE apps who may not have prior experience of the security considerations which are relevant when developing features such as authentication and authorisation, this feels like something we should implement to provide guidance to the community on best practices. 

I don't understand this sentiment: pre-implementing security in the template does not help people understand security if they don't have prior knowledge about it.

**Comment by theimowski** [comment]
Closing as we have that on the TODO list in docs recipes https://github.com/SAFE-Stack/docs/issues/154

**Comment by kurt-mueller-osumc** [comment]
I would still love to see this added into the template! I'm currently trying to figure out how to add jwt auth to both the Saturn backend and elmish frontend of a SAFE Stack app.
