### ISSUE TITLE
Cannot open paket.exe

### ISSUE THREAD

**Issue by mastoj** [SAFE-Stack/SAFE-template#275]
I tried to create a safe app and just run deploy and it fails with the error:

> Cannot open assembly '/Users/tomasjansson/tmp/safe_bug/.paket/paket.exe': No such file or directory.

Steps to reproduce:

    dotnet new SAFE --deploy gcp-kubernetes
    fake build -t Deploy

Complete error message:

> The last restore is still up to date. Nothing left to do.
> run Deploy
> Building project with version: LocalBuild
> Shortened DependencyGraph for Target Deploy:
> <== Deploy
>    <== ClusterAuth
>       <== Publish
>          <== Docker
>             <== Bundle
>                <== Build
>                   <== InstallClient
>                      <== Clean
> 
> The running order is:
> Group - 1
>   - Clean
> Group - 2
>   - InstallClient
> Group - 3
>   - Build
> Group - 4
>   - Bundle
> Group - 5
>   - Docker
> Group - 6
>   - Publish
> Group - 7
>   - ClusterAuth
> Group - 8
>   - Deploy
> Starting target 'Clean'
> Finished (Success) 'Clean' in 00:00:00.0085760
> Starting target 'InstallClient'
> Node version:
> > "/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono" --version (In: false, Out: true, Err: true)
> /Users/tomasjansson/tmp/safe_bug> "/Users/tomasjansson/.nvm/versions/node/v8.11.3/bin/node" --version (In: false, Out: false, Err: false)
> v8.11.3
> Yarn version:
> /Users/tomasjansson/tmp/safe_bug> "/usr/local/bin/yarn" --version (In: false, Out: false, Err: false)
> 1.9.4
> /Users/tomasjansson/tmp/safe_bug> "/usr/local/bin/yarn" install --frozen-lockfile (In: false, Out: false, Err: false)
> yarn install v1.9.4
> [1/4] 🔍  Resolving packages...
> success Already up-to-date.
> ✨  Done in 0.48s.
> Finished (Success) 'InstallClient' in 00:00:01.4016400
> Starting target 'Build'
> /Users/tomasjansson/tmp/safe_bug/src/Server> "/usr/local/share/dotnet/dotnet" build (In: false, Out: false, Err: false)
> Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Cannot open assembly '/Users/tomasjansson/tmp/safe_bug/.paket/paket.exe': No such file or directory.
> /Users/tomasjansson/tmp/safe_bug/.paket/Paket.Restore.targets(91,5): error MSB3073: The command "/Library/Frameworks/Mono.framework/Commands/mono --runtime=v4.0.30319 "/Users/tomasjansson/tmp/safe_bug/.paket/paket.exe" restore" exited with code 2. [/Users/tomasjansson/tmp/safe_bug/src/Server/Server.fsproj]
> 
> Build FAILED.
> 
> /Users/tomasjansson/tmp/safe_bug/.paket/Paket.Restore.targets(91,5): error MSB3073: The command "/Library/Frameworks/Mono.framework/Commands/mono --runtime=v4.0.30319 "/Users/tomasjansson/tmp/safe_bug/.paket/paket.exe" restore" exited with code 2. [/Users/tomasjansson/tmp/safe_bug/src/Server/Server.fsproj]
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.57
> Finished (Failed) 'Build' in 00:00:01.0699700
> 
> ---------------------------------------------------------------------
> Build Time Report
> ---------------------------------------------------------------------
> Target          Duration
> ------          --------
> Clean           00:00:00.0022980
> InstallClient   00:00:01.4014420
> Build           00:00:01.0697870   ('dotnet build' failed in /Users/tomasjansson/tmp/safe_bug/src/Server)
> Bundle          00:00:00           (skipped)
> Docker          00:00:00           (skipped)
> Publish         00:00:00           (skipped)
> ClusterAuth     00:00:00           (skipped)
> Deploy          00:00:00           (skipped)
> Total:          00:00:02.6722670
> Status:         Failure
> ---------------------------------------------------------------------
> Script reported an error:
> -> BuildFailedException: Target 'Build' failed.
> -> One or more errors occurred. ('dotnet build' failed in /Users/tomasjansson/tmp/safe_bug/src/Server)
> -> 'dotnet build' failed in /Users/tomasjansson/tmp/safe_bug/src/Server
> Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
> Warning: Paket resolved a FSharp.Core with version '4.6.0.0', but fake runs with a version of '4.5.0.0'. This is not supported.
> Please either lock the version via 'nuget FSharp.Core <nuget-version>' or upgrade fake.
> Read https://github.com/fsharp/FAKE/issues/2001 for details.
> Hint: Could not find a version in your paket.dependencies file, consider adding 'version 5.189.1' at the top of your dependencies file (/Users/tomasjansson/tmp/safe_bug/paket.dependencies).
> Read https://github.com/fsharp/FAKE/issues/2193 for details.
> Performance:
>  - Cli parsing: 272 milliseconds
>  - Packages: 19 milliseconds
>  - Script analyzing: 29 milliseconds
>  - Script running: 2 seconds
>  - Script cleanup: 19 milliseconds
>  - Runtime: 3 seconds
>

**Comment by theimowski** [comment]
I just tried reproducing that issue using a dotnet:2.2-sdk-alpine docker image, but FAKE does restore packages.
What's your FAKE version? Can you try upgrading to latest and see if that helps?

**Comment by mastoj** [comment]
@theimowski looks like that solved it, thanks.
