### ISSUE TITLE
Add safe template to Ionide’s create new project templates 

### ISSUE THREAD

**Issue by tforkmann** [SAFE-Stack/SAFE-template#279]
Hi there,

it would be nice to add the safe template to the F# - Create new Project feature in VSCode.

You already can select some templates like F# console application or even Saturn application and it works pretty well.

I would like to contribute but just don’t know where to add this template and the template should always update correspond to the latest Safe Template version. I think the existing templates are not up to date.

Let me know if this is something useful.

**Comment by Krzysztof-Cieslak** [comment]
Ionide in the future will move to scaffolding based on `dotnet new` templates (https://github.com/fsharp/FsAutoComplete/pull/412), and then we will automatically support SAFE template. Current solution that Ionide use is considered legacy so I don't think there is sense in adding SAFE template there.

**Comment by tforkmann** [comment]
Awesome! Thanks. Closing it now
