### ISSUE TITLE
Feature request: Add SignalR as a --communication option

### ISSUE THREAD

**Issue by filipelbc** [SAFE-Stack/SAFE-template#283]
https://dotnet.microsoft.com/apps/aspnet/real-time

**Comment by theimowski** [comment]
Thanks for suggestion, however it's rather unlikely we add this in near feature as we're currently trying to minimise the variance of the template ([details](https://github.com/SAFE-Stack/SAFE-template/issues/269))

**Comment by theimowski** [comment]
@isaacabraham worth adding a recipe for this?

**Comment by kerams** [comment]
You could just point users to https://shmew.github.io/Fable.SignalR/#/installation

**Comment by theimowski** [comment]
Thanks @kerams for pointing to the project, wasn't aware of it. Anyway would be good to provide at least a short recipe to showcase how to integrate Fable.SignalR into SAFE project. Added a TODO with link to https://github.com/SAFE-Stack/docs/issues/154
