### ISSUE TITLE
How to I change the browser tab name from "SAFE Template" to something else?

### ISSUE THREAD

**Issue by ChechyLevas** [SAFE-Stack/SAFE-template#287]
I've started a personal web app using the SAFE template. Whenever I navigate to the URL, my browser (Firefox) tab name is "SAFE Template". However, I can't find where this value is set. Is this a default value, or have I just missed where it is set?

**Comment by Zaid-Ajaj** [comment]
It is simply the title of the `index.html` page, see [this line](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Client/index.html#L4)

**Comment by theimowski** [comment]
Also if you want to manipulate it from Fable, simply do `Browser.Dom.document <- "my title"`
