### ISSUE TITLE
Error on first time build of project

### ISSUE THREAD

**Issue by dsyme** [SAFE-Stack/SAFE-template#29]
Steps

    dotnet new -i SAFE.Template
    dotnet new SAFE -n SafeApp -o SafeApp -lang F#
    cd SafeApp
    .\build

Gave me:

![image](https://user-images.githubusercontent.com/7204669/35388714-c6ae9eac-01cc-11e8-9bcb-ae9a11bc70e7.png)

Simple fix was to add ``module Client`` to Code.fs, I'll submit a PR for this

**Comment by forki** [comment]
it needs redeploy @theimowski

**Comment by theimowski** [comment]
Thanks, released in 0.5.3
