### ISSUE TITLE
.devcontainer folder appears in new SAFE app

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#292]
On latest SAFE template, doing a normal `dotnet new SAFE` will create a `.devcontainer` folder which contains a DockerFile etc. Is this intentional (or is it something being created by VSCode on my machine?)?

**Comment by Krzysztof-Cieslak** [comment]
Yes, this is intentional - it’s definition of docker image in which you can develop and run your extension with Remote Container VSCode extension - https://github.com/SAFE-Stack/SAFE-template/pull/254

**Comment by theimowski** [comment]
Yup, although wondering why VS Code team decided to go with a separate `.devcontainer` directory instead of placing that inside `.vscode` - it seems to be an editor-specific thing
