### ISSUE TITLE
Upgrade to netstandard2.0

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#301]
With the release of FSharp.Core 4.7, we are now in a position to try moving to netstandard2.0. There are at least two projects in the basic SAFE template that are still at 1.6 - FParsec (<== FAKE) and TaskBuilder.fs (<== Giraffe).

**Comment by theimowski** [comment]
I'm still bit confused by this - what exactly do we want to upgrade to netstandard2.0?
Server is netcoreapp2.2, Client via Fable refers to netstandard2.0, Same for build script dependencies - netstandard2.0

**Comment by isaacabraham** [comment]
There's nothing that we can do at the moment. Once FParsec and TaskBuilder are done, we need to update the lock files to the latest versions of them - that should be all.

**Comment by theimowski** [comment]
And again - what would be the major benefit from doing that?

**Comment by isaacabraham** [comment]
Lock files will be greatly reduced in size, resulting in a much better experience the first time someone adds a new package.

**Comment by theimowski** [comment]
Still don't understand how that will happen since currently FSharp.Core in paket.lock is on 4.6.2 and doesn't have any dependencies:

```
...
     FSharp.Control.Reactive (4.2)
       FSharp.Core (>= 4.2.3)
       System.Reactive (>= 4.0)
     FSharp.Core (4.6.2)
     Microsoft.Build (16.0.461)
     Microsoft.Build.Framework (16.0.461)
...
```

**Comment by isaacabraham** [comment]
Hmmm! Maybe because it's pinned to netstandard2.0 it doesn't matter? All the lock files I've seen that have FSharp.Core 4.6.2 etc. have huge lock files because they go against netstandard1.6. @forki what am I missing here?

**Comment by forki** [comment]
yes it's already pinned to netstandard2 - this can probably just go
