### ISSUE TITLE
Update React versions

### ISSUE THREAD

**Issue by nojaf** [SAFE-Stack/SAFE-template#303]
`Fable.React 5` contains bindings for Hooks yet the version of React is too low to use this.
Please update 
```
      "react": "16.5.2",
      "react-dom": "16.5.2",
```
to 16.8 or higher if available.

**Comment by theimowski** [comment]
does the update imply any breaking changes?

**Comment by nojaf** [comment]
I don't think so, no.

**Comment by theimowski** [comment]
released in v1.15
