### ISSUE TITLE
"Root element is missing" error in Server.fsproj

### ISSUE THREAD

**Issue by lem0n4de** [SAFE-Stack/SAFE-template#307]
When I clone the repository and run `fake built -t run`, this error shows up, also vscode can not load the project too.

`/opt/dotnet/sdk/3.0.100-preview7-012821/NuGet.targets(123,5): error : Root element is missing. [/home/user/dev/safe/src/Server/Server.fsproj]`

I am on a linux machine.
- `dotnet --version` : `3.0.100-preview7-012821`
- `yarn --version` : `1.17.3`

I thought the error could be because I use a preview version but after adding a global.json file the error is still there. I couldn't solve it.

**Comment by lem0n4de** [comment]
Apparently, this is a problem with Saturn template. Giraffe and Suave templates are working fine. All fsproj files are identical though.

**Comment by theimowski** [comment]
This repository is not meant to be cloned, see https://safe-stack.github.io/docs/quickstart/ for how to bootstrap SAFE apps
