### ISSUE TITLE
Deploy to App Service is not working

### ISSUE THREAD

**Issue by JonathanDDuncan** [SAFE-Stack/SAFE-template#308]
Azure has changed its layout and it is no longer possible to following the instructions to deploy a safe-stack app to Azure.  There also seems to be a problem with the ArmTemplate.

**Comment by JonathanDDuncan** [comment]
I've just spent two days trying to deploy the sample Safe-Stack application with no success. So it hasn't been a fantastically good experience for me as I was hoping. :cry: :confused: :disappointed:

It started by running the following in the command prompt.  All ran without any errors.

- dotnet new -i SAFE.Template
- dotnet new SAFE
- fake build --target run
- dotnet new SAFE --deploy azure --force

But where I had trouble with instructions was 
[https://safe-stack.github.io/docs/template-azure-registration/#creating-an-app-registration](https://safe-stack.github.io/docs/template-azure-registration/#creating-an-app-registration)

I got the Subscription Id and the Application id (client id) 

But I could not the following instructions because the Azure portal page has been modified.
Set the **Application type** as **Native**.
Choose **Settings** from the top menu.
Choose **Required Permissions** from the Settings blade.
![image](https://user-images.githubusercontent.com/6956837/63640761-bc03be00-c661-11e9-90a3-8eabd1a0800c.png)
![image](https://user-images.githubusercontent.com/6956837/63640769-cf168e00-c661-11e9-81ad-ddc26f6472a8.png)


So I chose **API permissions** instead
![image](https://user-images.githubusercontent.com/6956837/63640774-d89ff600-c661-11e9-8849-6ee20223e2a9.png)

**Add a permission**, 
From the Microsoft APIs tab I chose,  **Azure Service Management**

Then I checked the box beside 

**Access Azure Service Management as organization users (preview)**
![image](https://user-images.githubusercontent.com/6956837/63640781-e5bce500-c661-11e9-8677-39449f5f5276.png)

Below **Grant consent**

I clicked on the 
**Grant admin consent for Default Directory**

Then I click on **Yes** to approve it.
![image](https://user-images.githubusercontent.com/6956837/63640788-f4a39780-c661-11e9-87e1-eb5c7da28fc9.png)

Then on the page
https://safe-stack.github.io/docs/template-appservice/

At the command prompt I ran 
fake build --target appservice -e subscriptionId=<subscription id here> -e clientId=<client id here>

When prompted to do I went to  https://microsoft.com/devicelogin in the browser and entered the code displayed and selected my account.
In the browser, I got the message 
You have signed in to the AplicationRegistrationName application on your device. You may now close this window.

Then in the command prompt I get the following error. :scream: :fearful: :sweat:
ArmTemplate     00:00:34.7566623   (One or more errors occurred. (AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 884e622e-9ca5-4096-b666-78e59ee35400
Correlation ID: bf31f4d0-1760-46a5-a1ec-4b28f12797bc
Timestamp: 2019-08-24 16:49:39Z))

So I went to the Certificates & secrets in the left hand menu and proceeded to create a client secret. 
![image](https://user-images.githubusercontent.com/6956837/63640984-24ec3580-c664-11e9-9f8c-35f9c4faf631.png)
And added  -e client_secret=clientsecret to my FAKE command line and ran it again.

And I still get the same error. :cry::cry::cry:


---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target          Duration
------          --------
Clean           00:00:01.0892716
InstallClient   00:00:01.6686945
Build           00:00:33.3338632
Bundle          00:00:04.5753826
ArmTemplate     00:00:45.8748901   (One or more errors occurred. (AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: b2e7fa91-cc3e-4661-bcbd-15ab793a1500
Correlation ID: 96515848-2986-4dd8-ab9f-6d87e9358653
Timestamp: 2019-08-24 17:32:19Z))
AppService      00:00:00           (skipped)
Total:          00:01:26.7579630
Status:         Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'ArmTemplate' failed.
-> One or more errors occurred. (One or more errors occurred. (AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
   Trace ID: b2e7fa91-cc3e-4661-bcbd-15ab793a1500
   Correlation ID: 96515848-2986-4dd8-ab9f-6d87e9358653
   Timestamp: 2019-08-24 17:32:19Z))
-> One or more errors occurred. (AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
   Trace ID: b2e7fa91-cc3e-4661-bcbd-15ab793a1500
   Correlation ID: 96515848-2986-4dd8-ab9f-6d87e9358653
   Timestamp: 2019-08-24 17:32:19Z)
-> AdalServiceException: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
   Trace ID: b2e7fa91-cc3e-4661-bcbd-15ab793a1500
   Correlation ID: 96515848-2986-4dd8-ab9f-6d87e9358653
   Timestamp: 2019-08-24 17:32:19Z
-> HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
-> AdalException: {"error":"invalid_client","error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: b2e7fa91-cc3e-4661-bcbd-15ab793a1500\r\nCorrelation ID: 96515848-2986-4dd8-ab9f-6d87e9358653\r\nTimestamp: 2019-08-24 17:32:19Z","error_codes":[7000218],"timestamp":"2019-08-24 17:32:19Z","trace_id":"b2e7fa91-cc3e-4661-bcbd-15ab793a1500","correlation_id":"96515848-2986-4dd8-ab9f-6d87e9358653","error_uri":"https://login.microsoftonline.com/error?code=7000218"}: Unknown error

:unamused:
I think you might need to pass the client_secret into the ArmTemplate  or something along those lines.

:disappointed::disappointed:

**Comment by JonathanDDuncan** [comment]
Here is the output of one of the FAKE runs
[output.txt](https://github.com/SAFE-Stack/SAFE-template/files/3537438/output.txt)

**Comment by isaacabraham** [comment]
@JonathanDDuncan hey. thanks for this - i'll have a look into this ASAP as it should be working. As you rightly say, the entire UI for AD apps has changed, and we should update the docs to reflect this.

**Comment by JonathanDDuncan** [comment]
Ok great looking forward to your response I would really like to get it
deploying.  I might just not know how to properly do one one the steps or
something.

**Comment by isaacabraham** [comment]
I'm testing it out right now. To be honest, it doesn't matter whether it's a bug in the template or not, something is wrong because you've not been able to get it working :-) So we need to either fix the code or fix the docs.

**Comment by isaacabraham** [comment]
OK - it's still working, but we need to update the docs to make it clearer what to do in the "new" AD pages.

**Comment by isaacabraham** [comment]
@JonathanDDuncan can you check the PR (https://github.com/SAFE-Stack/docs/pull/126/) - either read the MD files locally or use mkdocs to generate a local version of the docs to see? The one extra thing I think we need to do (@theimowski this will unfortunately require a new release of the template) is to update the following line in the deploy script:

```fsharp
        |> authenticateDevice Trace.trace { ClientId = clientId; TenantId = None) }
```

so that the `TenantId` is explicitly set. It seems that this previously wasn't needed but I'm seeing this nowadays needed more and more. You can temporarily just do it manually e.g. `TenantId = Some (Guid.Parse "123123123123")`.

Let me know how you get on.

**Comment by isaacabraham** [comment]
@JonathanDDuncan thanks for the testing and feedback - really appreciated.

Would you consider submitting both of these (the documentation changes and possibly the template changes) as pull requests? The first can go [here](https://github.com/SAFE-Stack/docs), the second would be as a PR to this repo

If you've never done a PR before, I'm happy to spend some time with you to help you figure that out!

**Comment by isaacabraham** [comment]
@JonathanDDuncan just to be clear: I had already put in the first regarding `TenantId` as a PR (https://github.com/SAFE-Stack/SAFE-template/pull/310/files) :-)

**Comment by theimowski** [comment]
Do latest changes resolve this issue?

**Comment by JonathanDDuncan** [comment]
Yes

**Comment by JonathanDDuncan** [comment]
> Do latest changes resolve this issue?

Yes

**Comment by theimowski** [comment]
Ok then closing the issue - @isaacabraham  I believe there are some pending PRs for these changes in docs repository
