### ISSUE TITLE
Deploy a SAFE app as Self-Contained Deployment to IIS hosting server

### ISSUE THREAD

**Issue by JonathanDDuncan** [SAFE-Stack/SAFE-template#309]
Is it possible to deploy a Safe-Stack app as Self-Contained Deployment to a hosting server other than the ones listed in the docs as we can do with other ASP.NET Core apps?

If so how would we go about it?

Thanks

**Comment by isaacabraham** [comment]
What sort of things are you thinking about in terms of hosting server? SAFE apps are at their most basic just ASP .NET Core apps on the server with normally a static JS bundle.

**Comment by Zaid-Ajaj** [comment]
> I was thinking of a compiled deploy folder or deploy.zip file.

Isn't this what you already get with
```
dotnet new SAFE --deploy iis
fake build --target bundle
```
See [Deploy to IIS](https://safe-stack.github.io/docs/template-iis/)

**Comment by theimowski** [comment]
The [Deploy to IIS](https://safe-stack.github.io/docs/legacy-template-iis/) has been moved as it regards legacy template v1.
We plan to add a recipe on IIS integration https://github.com/SAFE-Stack/docs/issues/154
