### ISSUE TITLE
include release and deployment options from BookStore

### ISSUE THREAD

**Issue by kfrie** [SAFE-Stack/SAFE-template#31]
I chose a snapshot of the BookStore sample over the CLI template because of the extended support for tests, release and deployment.

It would be very nice if those options were available with the template and it would be the cleanest way to fire up new projects

**Comment by theimowski** [comment]
As a good start I added `--Docker` option for additional FAKE targets

**Comment by theimowski** [comment]
Future ideas that come to my mind include Azure Functions or AWS Lambda.
Waiting for more feedback / suggestions

**Comment by kfrie** [comment]
I lost a bit track of this 🙈. What about deployment scenarios with Kubernetes and Helm charts ?

**Comment by isaacabraham** [comment]
I think you should close this issue - it's too broad - and make specific issues for specific scenarios e.g. k8s etc.. We have one for ARM + Azure App Service already.

**Comment by theimowski** [comment]
Agreed - we can now build on top of the `--Deploy` option
