### ISSUE TITLE
Hot Reload does not work

### ISSUE THREAD

**Issue by TorbenRahbekKoch** [SAFE-Stack/SAFE-template#312]
To reproduce simply run dotnew in an empty directory

    dotnew new safe

Build and run:

    fake build -t run

Try changing src/Client/Client.fs. No reload occurs.

To fix:
Update some package versions in package.json:

    "fable-compiler": "^2.3.20",
    "webpack": "^4.39.3",
    "webpack-dev-server": "^3.8.0",

It has to be all three of them, though.

Now run yarn install and build and run again. Changing Client.fs now results in reload.

**Comment by theimowski** [comment]
Hot reload should work fine for template version 1.17 - can you check you're running latest SAFE template?

**Comment by TorbenRahbekKoch** [comment]
I was actually running 1.16, but just tried with 1.17. Same result. The code recompiles automatically but the browser does not refresh (manual refresh does get the changed items). Tried with Chrome and Firefox. The browser logs doesn't seem to give anything useful away.

Again - simply updating the above mentioned packages in package.json fixes the problem.

**Comment by theimowski** [comment]
It works for me in Chrome both for yarn and npm with 1.17. I'll update the JS dependencies anyway - hopefully it can fix the issue

**Comment by TorbenRahbekKoch** [comment]
The wonderful intricacies of modern computing at play, I guess ;) Thanks for fixing and thanks for the template!

**Comment by theimowski** [comment]
I've released 1.18 version of template with updated JS dependencies - could you please test if that new version fixes the issue?

**Comment by theimowski** [comment]
Thank you!
