### ISSUE TITLE
Lots of odd files in client deployment folder

### ISSUE THREAD

**Issue by markpattison** [SAFE-Stack/SAFE-template#313]
Using version 1.16.0 of the SAFE-stack template.

Repro steps:

```
dotnet new safe --js-deps npm --communication remoting
fake build -t build
```

The src/Client/deploy folder now contains 75 items with extensions including `ttf`, `svg`, `woff` and `woff2`.  The files have long filenames which look randomly generated, and make up around 12MB in total.

Where do these files come from, and are they all necessary for deployment?

With previous templates, in the equivalent folder you only got `app.js`, `vendors.js`, `index.html` and the favicon.

**Comment by theimowski** [comment]
This change has been introduced as part of #286 in order to avoid loading dependencies from CDN

**Comment by markpattison** [comment]
Thanks for the explanation.  That makes sense - although the deployment folder looks a bit ugly, I don't suppose it matters.

**Comment by theimowski** [comment]
Agreed - pros and cons. Closing the issue for now, feel free to reopen if you feel like we should revisit that one day
