### ISSUE TITLE
Fresh template is unable to dotnet restore a project individually

### ISSUE THREAD

**Issue by Zaid-Ajaj** [SAFE-Stack/SAFE-template#315]
Due to the missing paket.exe in the template, if you bootstrap a project using a fresh template, you cannot call `dotnet restore` on a project because it is looking for `paket.exe`. I think users expect this to "just work"

### Reproduce the problem
```bash
mkdir SafeTest
cd SafeTest
dotnet new -i SAFE.Template
dotnet new safe
cd src
cd Client
dotnet restore
```
Result
```
c:\projects\SafeTest\.paket\Paket.Restore.targets(117,5): error MSB3073: The command ""paket.exe" restore" exited with code 9009. [c:\projects\SafeTest\src\Client\Client.fsproj]
```
### Possible solutions

.NET Core 3 has now [Local CLI Tools](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#local-tools) per repository which means both `paket` and `fake` can be included as local cli tools to the project instead of requiring the users to install them separately. Problem with using `paket` as a local cli tool is that the issue above persists unless you add the following to the project file
```xml
<PaketCommand>dotnet paket</PaketCommand>
```
### Related information
 - `dotnet --version` : 3.0.100
 - OS: Windows

**Comment by isaacabraham** [comment]
The current guidance [clearly states](https://safe-stack.github.io/docs/quickstart/#install-pre-requisites) that you need to install Paket as a global tool, but yes we should look at local tools now that .NET Core 3 is a thing.

I suspect that we might want to move to .NET Core 3 and put some other simplifications in for v2 of the template.

**Comment by Zaid-Ajaj** [comment]
> The current guidance clearly states that you need to install Paket as a global tool, but yes we should look at local tools now that .NET Core 3 is a thing.

I understand that, my point was that maybe the docs should remove the wording about paket being an *optional* requirement because even if you are not "editing" packages, it becomes problematic for a simple use case as the one above. It is nice when the something doesn't just break if you deviate a bit from the docs ;)

**Comment by forki** [comment]
Does dotnet restore work with global Paket already? Never tried it

Zaid Ajaj <notifications@github.com> schrieb am Mi., 25. Sep. 2019, 17:50:

**Comment by Zaid-Ajaj** [comment]
> Does dotnet restore work with global Paket already? Never tried it

Me neither, but I have been working on a new Femto release that helps with these issues

![femto-install](https://user-images.githubusercontent.com/13316248/65618772-27251500-dfbf-11e9-9805-174fac902006.png)

**Comment by isaacabraham** [comment]
Yes global paket works great with dotnet restore, been using it for a while without problems.

**Comment by theimowski** [comment]
Agreed this is not best UX, unfortunately it's an expected behaviour at the moment if you don't use `fake` which can restore the packages. 
Is the paket bootstrapper for .net core ready yet? I believe we agreed having paket bootstrapper as local dotnet tool would be better than paket itself.

**Comment by theimowski** [comment]
@isaacabraham not sure if I'd associate update to .net core 3 with v2 of the template - v2 still seems like a long way to go

**Comment by forki** [comment]
>Is the paket bootstrapper for .net core ready yet?

I hope @vbfox can help me with that

**Comment by forki** [comment]
latest version should support local paket tool. Can you please try?

**Comment by Zaid-Ajaj** [comment]
Sure I can, but you mean try it from a fresh Safe template? if that is the case, shouldn't paket restore targets be updated first (or do I need to run a restore from fake first to have the restore targets updated?)

**Comment by Zaid-Ajaj** [comment]
@forki  Confirmed `dotnet restore` works with paket as a local cli tool but as I expected the restore targets have to updated first by running `dotnet paket restore` in the project root

**Comment by forki** [comment]
Yes chicken and egg. Targets file need to be updated

Zaid Ajaj <notifications@github.com> schrieb am Fr., 27. Sep. 2019, 14:08:

**Comment by Zaid-Ajaj** [comment]
@forki Actually the problem still persists if you install a package
```bash
# inside {SafeApp}/src/Client 
dotnet restore # WORKS
# install a package (inside {SafeApp})
dotnet paket add Feliz --group Client --project ./src/Client/Client.fsproj
# inside {SafeApp}/src/Client 
dotnet restore # FAILS 
```

**Comment by forki** [comment]
What do you think we need to do?

**Comment by Zaid-Ajaj** [comment]
Restoring the specific project automatically after the installation seems to be a workaround 
```
dotnet paket restore --project ./src/Client/Client.fsproj
```
At least that is why I am doing with Femto

**Comment by forki** [comment]
That is weird. What's the exact error message?

**Comment by Zaid-Ajaj** [comment]
The same error I got before updating the restore targets:
```
c:\projects\SafeTest\.paket\Paket.Restore.targets(117,5): error MSB3073: The command ""paket.exe" restore" exited with code 9009. [c:\projects\SafeTest\src\Client\Client.fsproj]
```
![Untitled](https://user-images.githubusercontent.com/13316248/65771743-29ab7a00-e139-11e9-987a-74b1ae251797.png)

**Comment by forki** [comment]
Did the targets file get changed between those two calls?

Zaid Ajaj <notifications@github.com> schrieb am Fr., 27. Sep. 2019, 15:12:

**Comment by Zaid-Ajaj** [comment]
I can check the diff later for you just to be sure but I think the restore targets reverted back and started looking for paket.exe again

**Comment by forki** [comment]
Yes that's what I thought. One of the calls invoked a older Paket and that
one set tgr targets back

Zaid Ajaj <notifications@github.com> schrieb am Fr., 27. Sep. 2019, 15:23:

**Comment by theimowski** [comment]
Closing - this should be now solved by using dotnet local tools
