### ISSUE TITLE
include several CSS frameworks with themability and webpack workflow

### ISSUE THREAD

**Issue by ghost** [SAFE-Stack/SAFE-template#32]
another nice feature would be the ability to choose between several CSS Frameworks at startup and in a variant that allows for custom themes with SASS or LESS out of the box by setting up `webpack.config.js`
accordingly

The ones to go for in my opinion are:

* [Bulma](https://bulma.io/) : thats already included with Fulma so 👍 
* [Semantic UI ](https://semantic-ui.com/): setup with webpack sucks, but when its done it's a breeze to work with, especially as a non-designer + themes feature is really superior with respect to others
* [Bootstrap ](https://getbootstrap.com/) : the most prominent 
* [MaterializeCSS ](http://materializecss.com/) : for going with idiomatic material design
* [UI Kit](https://getuikit.com/docs/introduction)  : another very clean, minimalistic and good-looking alternative

I do not know how to do templates for `dotnet` t this point, but if this stuff is desired by some of you I might give it a go. 

The first step could be the integration of custom themes for Bulma, since it is already present in the template.

**Comment by isaacabraham** [comment]
I've recently seen a demo of materialise in fable so perhaps this is worth another look at.

**Comment by theimowski** [comment]
Also https://www.evilznet.com/fable-ant-design/index.html

**Comment by theimowski** [comment]
Would be good to change `--Fulma` parameter e.g. to `--layout fulma-basic` before targeting 1.0 so that we can have a convention for other frameworks like ant design or materialise

**Comment by theimowski** [comment]
Let's keep on the list only those frameworks that are already working integration projects with Fable:

- [ ] [Fulma](https://mangelmaxime.github.io/Fulma/)
- [ ] [Material UI](https://mvsmal.github.io/fable-material-ui/#/home)
- [ ] [Ant design](https://www.evilznet.com/fable-ant-design/#home)

**Comment by aloisdg** [comment]
I would love to have tailwindcss (functional css rocks!)

**Comment by isaacabraham** [comment]
On the same theme, we could also consider adding https://jenil.github.io/bulmaswatch/ without too much effort.

**Comment by theimowski** [comment]
Taking https://github.com/SAFE-Stack/SAFE-template/issues/269 into consideration I think we should put this on "hold" until we feel comfortable to add other css frameworks.

**Comment by functionalprogrammer** [comment]
Hi @isaacabraham. I don't think this is relevant anymore and it can be closed since we've gone with Bulma as default for the standard template and don't use any CSS framework for the minimal.

**Comment by theimowski** [comment]
Closing - this is unlikely to happen anytime soon
