### ISSUE TITLE
Azure WebApp for Container Docker Deployment Elmish Bridge Not Working

### ISSUE THREAD

**Issue by steelcityrkp** [SAFE-Stack/SAFE-template#321]
If I try to deploy the template as per the instructions following Docker container deploy hosted on Azure WebApp for Container the Client loads up correctly, but the WebSockets used in the Elmish Bridge communication option fail to connect.

I'm trying to resolve this for a project I'm working on built off of this basis; itworks great locally, but doesn't deploy.  If I have any progress, I will share.  However, I did want to highlight that I did try this from a fresh template and so this doesn't work out of box, or as expected.

The counter example will work fine running locally from a container, but when deployed, the client will load, but it just remains in Loading...

This error keeps repeating in Chrome Debug Console:
`WebSocket connection to 'wss://xxx.azurewebsites.net/socket/init' failed: Error during WebSocket handshake: Unexpected response code: 503
`
I did follow some steps to enable WebSockets for the app (which required using the Shell directly); however, this problem remains.

**Comment by theimowski** [comment]
FYI @isaacabraham - that's probably some knobs in Azure?

**Comment by isaacabraham** [comment]
Uhhh. 503 is service unavailabile IIRC which suggests maybe the routing is somehow screwed or the port is not open? I must admit I've barely tried Elmish Bridge anyway let along through App Service. 

HOWEVER

A quick bit of googling sent me [here](https://github.com/aspnet/AspNetCore/issues/10370) - seems like websockets aren't fully supported on App Service Containers!

**Comment by steelcityrkp** [comment]
It seems that [utilizing SignalR in Elmish Bridge](https://github.com/Nhowka/Elmish.Bridge/issues/3) is in the pipeline, which would resolve this issue of this combination of Communication Option and Build/Deployment for the template working out-of-box.  However, this larger consideration that the WebSockets not being fully supported on App Service for Containers (_specifically Linux, it seems_) is worth keeping note of and following.   Appreciate your feedbacks...!
