### ISSUE TITLE
style.scss overrides the standard font?

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#323]
Inside the style.scss file is the following:

```scss
// OpenSans
$FontPathOpenSans: "~open-sans-fonts/open-sans";
@import '~open-sans-fonts/open-sans';
$family-primary: 'Open Sans';
```

This overrides the standard Bulma font, resulting in pages that do not look the same as in Bulma examples. Why is it there?

**Comment by theimowski** [comment]
Closing as we no longer have SCSS in v2
