### ISSUE TITLE
SAFE Template doesn't have an package.json lock file

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#328]
We should probably be including this in the template.

**Comment by theimowski** [comment]
you sure? https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/.template.config/template.json#L624-L627

need to use `--js-deps npm`, otherwise you should have `yarn.lock`

**Comment by isaacabraham** [comment]
Sorry - I meant the package json file for NPM (assuming that we're still supporting NPM as well as Yarn).

**Comment by theimowski** [comment]
yes, so the package-lock.json should be there if creating project with `--js-deps npm` 
can you double check? 
if it's not there then it's a bug

**Comment by isaacabraham** [comment]
Ooops, that's right. That worked. Sorry!
