### ISSUE TITLE
Add FAKE and Paket local tools

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#330]
We should support FAKE and Paket local tools from .NET Core 3.1. This would require an update of the template to netcore3.1 but since that's LTS and 3.0 is maintenance, we should probably do that anyway.

Doing this will mean it's quicker and easier for people to get started, since they don't need to install either of the tools as pre-requisites.

The SAFE Dojo project has been upgraded this weekend and I've applied the change there, and it works beautifully.

**Comment by theimowski** [comment]
that's something I'm already doing for v2, but maybe it's worth adding also to v1

**Comment by theprash** [comment]
#339 is merged so this is done for the template output. Should we also make the change for the template project itself?

**Comment by theimowski** [comment]
sure - go for it
