### ISSUE TITLE
Azure locations outdated

### ISSUE THREAD

**Issue by TerenceHinrichsen** [SAFE-Stack/SAFE-template#335]
I assume that the 

> Microsoft.Azure.Management.ResourceManager.Fluent.Core 

needs to be updated. I wanted to publish to South Africa North (which is listed as available [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.core.region?view=azure-dotnet)), but the deployment defaulted to westeurope (which according the Build.fsx) is the fallback.

Alternatively, maybe someone can instruct me how to update the file on my local copy?

**Comment by theimowski** [comment]
@isaacabraham can you help here?

**Comment by TerenceHinrichsen** [comment]
Thanks @theimowski, I have in the interim modified the build.fsx file and replaced the deployment function's first line `let location = ...` to simply `let location = "myLocation"` and been able to deploy without issue.

**Comment by isaacabraham** [comment]
I would like to move over to Farmer for the ARM template side of things - just a matter of scheduling it in with the other changes we're making to the template. With this, people will be able to supply whichever region they like.

**Comment by isaacabraham** [comment]
In the short term you could probably just run a paket update on this?

**Comment by TerenceHinrichsen** [comment]
Thanks @isaacabraham
