### ISSUE TITLE
A bad version of javascript-serialize is triggering a moderate security alert

### ISSUE THREAD

**Issue by Kavignon** [SAFE-Stack/SAFE-template#336]
After installing the SAFE template in my project, I can see in my repository that the current version of the javascript-serialize dependency in the yarn.lock is causing an issue. 

<img width="764" alt="image" src="https://user-images.githubusercontent.com/6740474/75436886-4683ed80-5923-11ea-9cf5-e2c4b25f86cc.png">

**Comment by theimowski** [comment]
Thanks for reporting this, in #338 I updated those dependencies
