### ISSUE TITLE
Broken URL for Elmish.Streams

### ISSUE THREAD

**Issue by Kavignon** [SAFE-Stack/SAFE-template#337]
The Template provides the link to[ here ](https://elmish-streams.readthedocs.io/)

![image](https://user-images.githubusercontent.com/6740474/75466440-34707200-5958-11ea-8be2-948ce046b29d.png)

And the new URL is now [this](https://fablereaction.readthedocs.io/en/latest/fable.reaction/index.html)

![image](https://user-images.githubusercontent.com/6740474/75466535-57028b00-5958-11ea-942e-bee06696f531.png)

**Comment by theimowski** [comment]
I thought the project was renamed from Fable.Reaction to Elmish.Streams, but now it seems to be reverted to the original name? Am I right @dbrattli ?

**Comment by dbrattli** [comment]
@theimowski Yes, sorry about that. Trying to extend Elmish wasn't the right path forward. Fable.Reaction has no dependency on Elmish anymore. We're using React hooks instead (which means it works with Elmish as well).

**Comment by Kavignon** [comment]
Should it still be named Elmish.Streams when the library is called Fable.Reaction?
