### ISSUE TITLE
Giraffe template .UseContentRoot(publicPath) ?

### ISSUE THREAD

**Issue by Balinth** [SAFE-Stack/SAFE-template#347]
Creating the template with --server giraffe configures the WebHost to use the same path for ContentRoot and WebRoot
`
WebHost
    .CreateDefaultBuilder()
    .UseWebRoot(publicPath)
    .UseContentRoot(publicPath)
`
What gives? Seemingly nothing needs it this way, but on the other hand breaks the file configuration providers, which by default look at the ContentRoot for config files, which according to this should be placed alongside the publicly available static assets.
This option is not provided in the Saturn version of the template (or in standard asp net mvc templates), and commenting it out did not break anything, but fixed the config file provider.

**Comment by theimowski** [comment]
Closing as we no longer provide `--giraffe` option in v2
