### ISSUE TITLE
SAFE Template App - How to enableCORS

### ISSUE THREAD

**Issue by TheDevKnight** [SAFE-Stack/SAFE-template#351]
Hi,

im very new to the SAFE Stack und Web development with F#. I created a new app with the Template and added only a very simple call to my API that is not hosted bei the Saturn/MVC BackEnd.

`let getItems() = Fetch.fetchAs<Item list> "https://customname.azurewebsites.net/items"`

The rest is identical to the init call for the Counter. But ive got an error in the Browser that the call is  blocked because the response has no CORS header to allow theses calls.

What is the right way to enable CORSs in a SAFE App? I try some settings "disableHostCheck" and added Header in the config section of the WebpackDevServer. But this has no impact :(

Regards

**Comment by kerams** [comment]
Webpack dev servers settings matter only during development -- it's not used when you deploy your application. So to enable CORS, you need to do it in ASP.NET https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1 (for Giraffe, that is)

It boils down to adding this above `.UseGiraffe` (

```fsharp
.UseCors(fun b -> b.WithOrigins [|"https://*.eu.ngrok.io"; "http://127.0.0.1:8080"|] |> ignore)
```

and `.AddCors()` above `.AddGiraffe`.

I haven't used Saturn, but this looks promising https://www.reddit.com/r/fsharp/comments/fzvsn8/cors_saturn_and_fable/

**Comment by TheDevKnight** [comment]
@kerams thx for the hint, i will give it a try. And you are right this is a must have in production!

But my client is in development not published by the saturn/MVC Server. I can start the client standalone over the webpackdev server, where these settings are not available. 

How can i fix the problem in development time with the webpackserver?

Regards

**Comment by kerams** [comment]
This used to work for me a couple of months ago:

```
devServer: {
        publicPath: "/",
        contentBase: resolve(CONFIG.assetsDir),
        port: CONFIG.devServerPort,
        proxy: CONFIG.devServerProxy,
        hot: true,
        inline: true,
		allowedHosts: [
			'.ngrok.io'
		],
		writeToDisk: false,
		headers: {
			"Access-Control-Allow-Origin": "*",
		}
    },
```

**Comment by isaacabraham** [comment]
The alternative is to use WebPack to proxy calls to the API (obviously this means that you will in the production system also have to do this). But that might be overkill for what you're doing.

**Comment by TheDevKnight** [comment]
Thx for the tips but the settings in the webpack config has no effect. Still CORS problem and strange is that the initial Response for the app has the header Access-Control-Allow-Origin: * :(  
But i found another Solution...

`let getKonten() = Fetch.fetchAs<Konto list> ("http://product.azurewebsites.net/konten", [ RequestProperties.Mode RequestMode.Nocors ])`

and i see (DevConsole F12) that the call to my API works and ive got a 200 and the data. 
But then a exception is raised and i have no clue what the problem is. When i try a call over local host and return the identical data it will work and i have my deserialzed data in the app. 

`Fetch.fs?cbdb:353 Uncaught (in promise) Error: 0  for URL 
    at a (Fetch.fs?cbdb:353)` 

Can someone give me a working sample for an app that works with an external API. 

Regards :/

**Comment by TheDevKnight** [comment]
I found the Solution, the problem was not the safe app >_> it was my api service. Because it send no Access-Control-Allow-Origin header. The call from my app was succeeded after i added the cors policy to my api service :)

This blogpost was very helpfull
https://blog.kritner.com/2019/10/05/cors-headers-with-dotnetcore-3/

Regards
