### ISSUE TITLE
Migration to Saturn 0.13.1 is difficult and fails to run in IIS

### ISSUE THREAD

**Issue by robertpi** [SAFE-Stack/SAFE-template#354]
Not sure if this really solvable, but thought I'd write it up so people might benefit from my bug hunting.

Just changing the `.dependencies` file to `nuget Saturn ~> 0.13.1` breaks SAFE stack after a `paket install` as packet choses a mix of 3.1.3 and 3.1.1 versions for certain Microsoft.AspNetCore Microsoft.Extensions assemblies. 

This cause the server to fail to run with this error:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at <StartupCode$Server>.$Server.main@()
```

I spent sometime trying to fix this with `redirects: on` and `paket install --create-new-binding-files`, but it didn't seem to work. Not even sure if the redirection feature works on .NET Core, the docs are bit vague, I have the impression it doesn't, but I could be wrong.

Deleting the `.lock` file and running `paket install` produces a server that runs locally with Saturn 0.13.1 but the client is broken due to an incompatibility between Thoth.Fetch (1.1) and Thoth.Json (4.1.0), this can be solved by down grading Thoth.Json to 3.4.1.

So client and server run fine, but fail when run under a Windows Azure AppService (windows version) and also when run locally under IIS Express, I later discovered. The exception I receive is in this file: [null ref.txt](https://github.com/SAFE-Stack/SAFE-template/files/4597850/null.ref.txt)

This comes from `iisConfigData.pwzBindings` being null:
```
                        services.Configure<IISServerOptions>(
                            options => {
                                options.ServerAddresses = iisConfigData.pwzBindings.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
                                options.ForwardWindowsAuthentication = iisConfigData.fWindowsAuthEnabled || iisConfigData.fBasicAuthEnabled;
                                options.IisMaxRequestSizeLimit = iisConfigData.maxRequestBodySize;
                            }
                        );
```

Someone else has discovered this bug too and it appears to come from mixing AspNetCore 2 and 3 dependencies: https://github.com/dotnet/aspnetcore/issues/18662

While it's true that it doesn't seem a good idea to mix dependencies between major version, it seems somewhat enviable as some AspNetCore dlls, like Microsoft.AspNetCore.Authentication are still only at version 2.2.

Going to try and solve this by hosting under Linux.

**Comment by isaacabraham** [comment]
This issue seems like several mini issues in one:

* Saturn 0.13 cc @Krzysztof-Cieslak 
* Thoth client / server cc @MangelMaxime 

Maybe Paket as well re: @forki 

Also - you're right, binding redirects are no more in netcore land.

**Comment by Krzysztof-Cieslak** [comment]
Looking at our dependencies on NuGet, I'm not sure if we mix any in Saturn 🤔:

![image](https://user-images.githubusercontent.com/5427083/81411525-c956cf00-9142-11ea-8296-637bc269b457.png)

**Comment by isaacabraham** [comment]
That's what I thought - from latest release everything was simplified. However, it could be Giraffe that had the extra deps? Possibly we need to update the template to use latest Giraffe which now has better support for netcore3.1

**Comment by MangelMaxime** [comment]
Concerning Thoth.Fetch you have the version 2 which should support the latest version of Thoth.Json.

**Comment by Krzysztof-Cieslak** [comment]
We still have netstandard2.0 version of Saturn, it includes lot of different deps... @robertpi what's the target framework for your application?

**Comment by theimowski** [comment]
Possibly related to https://github.com/SAFE-Stack/SAFE-template/issues/326 ?

**Comment by robertpi** [comment]
@Krzysztof-Cieslak  I'm building a netcoreapp3.0 app.

Yes, @theimowski , I believe https://github.com/SAFE-Stack/SAFE-template/issues/326 is the same underlying issue, and that ultimately the root cause of the issue is this https://github.com/dotnet/aspnetcore/issues/18662.

I've put together a git repository that reproduces the error: https://github.com/robertpi/test-safe-stack-startup-bug

If you debug with visual studio in IIS express mode with "break on exceptions" and "just my code" disabled you should see:
![2020-05-09 07_34_41-test-safe-stack-startup-bug (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/51381/81465120-d23db400-91c7-11ea-81be-eb835d206847.png)

If you look at .lock you see paket has chosen lots of AspNetCore dlls with the version 2.2, not sure why it would do this: https://github.com/robertpi/test-safe-stack-startup-bug/blob/master/paket.lock#L671

**Comment by robertpi** [comment]
I suppose this is two different paket issues:
- change "nuget Saturn" to "nuget Saturn ~> 0.13.1" with the existing and run install and paket will fail a good solution and end up mixing AspNetCore dlls version 3.1.3 and 3.1.1
- make no changes to paket dependencies and delete the lock file paket will end up mixing AspNetCore dlls with version 3.0 and 2.2

**Comment by robertpi** [comment]
Concerning the Thoth.Fetch @MangelMaxime is right the safe template constrains Thoth.Fetch to version 1 https://github.com/robertpi/test-safe-stack-startup-bug/blob/master/paket.dependencies#L21 and running packet with no existing lock file cause it to choose version Thoth.Fetch 1.1 and Thoth.Json 4.2 which are incompatible.

I've created this PR to upgrade to Thoth.Fetch 2: https://github.com/SAFE-Stack/SAFE-template/pull/355

**Comment by robertpi** [comment]
Pushing the example repository caused me to noticed this security alert: https://github.com/robertpi/test-safe-stack-startup-bug/network/alert/yarn.lock/minimist/open

I'm preparing a PR for it.

**Comment by Krzysztof-Cieslak** [comment]
Try bumping your project to `netcoreapp3.1`

**Comment by robertpi** [comment]
Bumping to 3.1 does totally change the dlls choosen by fake: https://github.com/robertpi/test-safe-stack-startup-bug/commit/0ca5001035a89e23b73f4896a25c2805c05e0eab

When I try and run the server with version `netcoreapp3.1` under IIS Express I get a 404 when I try and hit /api/init. Could be something to do with this? https://stackoverflow.com/questions/59604325/asp-net-core-3-1-app-on-iis-express-this-site-cant-be-reached

Continues to work fine when running the exe as a server.

For the app I'm actually working on, I have moved to linux and running the exe as a server with nginx as a reverse proxy.

**Comment by Krzysztof-Cieslak** [comment]
Yes... So Saturn is published is cross-target for 2 targets:
* `netcoreapp3.1` - depending on ASP.Net Core 3.X
* `netstandard2.0` - depending on ASP.Net Core 2.X

If your application is targeting `netcoreapp3.0` then you use `netstandard2.0` set of dependencies... which well doesn't work for some reason 🤷‍♂️

In general, I'd recommend using `netcoreapp3.1` in both your application and this template - 3.1 is LTS release, and we will drop targeting `netstandard2.0` in Saturn in the future (https://github.com/SaturnFramework/Saturn/issues/237)

And yeah, I know nothing about IIS :-)

**Comment by theimowski** [comment]
Can we close this now @robertpi ?

**Comment by robertpi** [comment]
Yes, that's fine.
