### ISSUE TITLE
Update webpack.config.js

### ISSUE THREAD

**Issue by tforkmann** [SAFE-Stack/SAFE-template#366]
Hi there,

if you upgrade the  "copy-webpack-plugin": from "5.1.1" to the current version "copy-webpack-plugin": "^6.0.2" you will run into a error if you try to deploy to production. 
The `webpack.config.js` has to be update like this:

Current version: 

```js
commonPlugins.concat([
            new MiniCssExtractPlugin({ filename: 'style.[hash].css' }),
            new CopyWebpackPlugin([{ from: resolve(CONFIG.assetsDir) }]),
        ])
```

To ->:

```js
commonPlugins.concat([
            new MiniCssExtractPlugin({ filename: 'style.[hash].css' }),
            new CopyWebpackPlugin([{
                patterns: [{
                    from: resolve(CONFIG.assetsDir) }]
                }]),
        ])
```

**Comment by theimowski** [comment]
Thanks - I've recently stumbled upon that when updating the plugin version :)
