### ISSUE TITLE
dotnet new --update-check not finding latest version

### ISSUE THREAD

**Issue by brettrowberry** [SAFE-Stack/SAFE-template#368]
`dotnet new --update-check` does not find the latest version.

# System Information
`> dotnet --version`
`3.1.300`

# Steps to Reproduce
```
dotnet new --install SAFE.Template::1.0.0
dotnet new --update-check
```
Output:
```
An update for template pack SAFE.Template::1.0.0 is available.
    install command: dotnet new -i SAFE.Template::1.19.0```
```
I expected to see the latest version, 1.24.0, not 1.19.0.

# Workaround
`dotnet new -i SAFE.Template`
Sometimes this still fails and I have to run
`dotnet nuget locals all --clear;dotnet new -i SAFE.Template`
I can't get it to fail again and I wonder if this would be sufficient:
`dotnet nuget locals http-cache --clear;dotnet new -i SAFE.Template`

**Comment by theimowski** [comment]
Is this still an issue with v2?

**Comment by brettrowberry** [comment]
It’s a general issue with .NET new so I’ll close this issue.
