### ISSUE TITLE
Weird issue when changing the build script

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-template#370]
I did a very simple change in the build script:

```fsharp
    let tasks =
        [ if not safeClientOnly then yield server
          yield client ]
//          if not vsCodeSession then yield browser ]

```

But when I try to run the updated script I get:

> Script is not valid:
>         D:\Development\MetaVision\MVMedCheckApp2\build.fsx (11,5)-(11,9): Error FS0039: The namespace or module 'Fake' is not defined.
>         D:\Development\MetaVision\MVMedCheckApp2\build.fsx (12,5)-(12,9): Error FS0039: The namespace or module 'Fake' is not defined.
>         D:\Development\MetaVision\MVMedCheckApp2\build.fsx (13,5)-(13,9): Error FS0039: The namespace or module 'Fake' is not defined.
>         D:\Development\MetaVision\MVMedCheckApp2\build.fsx (15,0)-(15,6): Error FS0039: The value, namespace, type or module 'Target' is not defined

When I try to change this back to the original script, I keep getting the same message. Tried deleting the .fake folder didn't help.

**Comment by halcwb** [comment]
Ok, that was a bit of a surprise. It seems that when you change the build framework in the paket.dependencies to netstandard2.1 you run into this issue.See: https://github.com/fsharp/FAKE/issues/2513

**Comment by isaacabraham** [comment]
Closing - fixed in SAFE 2
