### ISSUE TITLE
v2 template has incorrect urls in Server launchSettings.json

### ISSUE THREAD

**Issue by Ryan-Palmer-CIT** [SAFE-Stack/SAFE-template#380]
If you try to launch the debugger from Visual Studio it fails to connect.

This is because the application URLs are set up incorrectly in the Server's launchSettings.json.

Also it doesn't launch the browser as this isn't set up either.

Ideally the app url would be http://localhost:8080 and the launch url would be http://localhost:8085 for both IIS and Server profiles.

I have included instruction for how to fix it in the [recipe I am writing](https://github.com/CompositionalIT/safe-stack-docs/blob/debug-safe-app/docs/recipes/developing-and-testing/debug-safe-app.md) but I could remove all of that if we sort it in the template.

**Comment by theimowski** [comment]
This is no longer applicable I believe?
