### ISSUE TITLE
v2 - Azure deploy fails if there are dashes in the project folder name

### ISSUE THREAD

**Issue by theprash** [SAFE-Stack/SAFE-template#381]
Any dashes (and presumably spaces etc.) in the project name are replaced with an underscore and inserted into the project. If your folder is `my-safe-app` then this Farmer deploy code is generated in `build.fsx`:

```fsharp
    let web = webApp {
        name "my_safe_app"
        zip_deploy "deploy"
    }
```

Azure web apps cannot have underscores in their names so this fails to deploy.

One way to fix this is by adding some code to replace underscores with dashes again for Azure names in `build.fsx`.

```fsharp
    let appName = "my_safe_app".Replace('_', '-')
    let web = webApp {
        name appName
        zip_deploy "deploy"
    }
```

But if this could be done with the template system that would be even better. It would be good to sanitise the string properly: from the Azure docs these are the naming rules:

> Contains alphanumerics and hyphens.
> Can't start or end with hyphen.

**Comment by olivercoad** [comment]
I tried adding a generated symbol to `symbols` in template.json with regex replacements to sanitise according to the naming rules.

```json
"azureAppName": {
    "type": "generated",
    "generator": "regex",
    "parameters": {
        "action": "replace",
        "source": "sourceName",
        "steps": [
            { "regex": "[^[:alnum:]]+", "replacement": "-" },
            { "regex": "^-|-$", "replacement": "" }
        ]

    },
    "replaces": "SAFE.AzureAppName"
}
```

Unfortunately it's not currently possible to use `sourceName` as the source for a generated symbol. See https://github.com/dotnet/templating/issues/2210

**Comment by Zaid-Ajaj** [comment]
@theprash This looks like more of an issue for farmer itself rather than the SAFE template. Basically farmer should either fail telling you that the name is invalid or it should sanitize it directly (cc @isaacabraham)

**Comment by isaacabraham** [comment]
@Zaid-Ajaj Yeah. We used to "implicitly" sanitise and clean up resource names but it ended up causing more trouble than it was worth - people would see resource names changed without realising it, so we're now moving to a "fail fast" approach where we validate and fail on bad resource names, so that wouldn't solve this (it's made worse by the fact that **every** **single** **azure** **resource** has different naming requirements).

I think the easiest option is to just do some sanitisation in the FAKE script.

(Hmmm. As a future idea, we could look at adding a naming factory in Farmer that would return a known valid resource name given an arbitrary input string).

**Comment by theprash** [comment]
@Zaid-Ajaj Well the deploy does fail with a message about an invalid name so you do get that information from the error. I didn't save the error but I think I didn't have trouble knowing what the problem was. Of course, it would be better if the error happened even earlier.

But even then I still think the SAFE Template should clean up the name at template creation type if it can. Or at the very least it should preserve a valid name: in this case the folder name was valid and the template changed it to be invalid.

**Comment by isaacabraham** [comment]
I think that this is out of scope of SAFE - it's an Azure concern. I'm doing some work in Farmer that will at least "ahead of time" give back a nice error message for this. And potentially will expose a feature to explicitly "sanitised" a name - we could use that here.

@theprash I would raise an issue in Farmer for this, but I would like to close this issue.

**Comment by isaacabraham** [comment]
I think we can close this. The latest Farmer has (IIRC) a validator against app service names so at least it would fail fast.
