### ISSUE TITLE
Straight out of the box template failure

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-template#388]
When running the latest safe-template (v1.24.0). I get an error:

> webpack-dev-server' is not recognized as an internal or external command

I just do:

```
dotnet new safe
dotnet tool restore 
dotnet fake build -t run
```

When I use npm as paket manager I get:

> Cannot find module 'webpack'

The only workaround is to change the build file to start the dev-server:

```fsharp
runTool nodeTool "node_modules/webpack-dev-server/bin/webpack-dev-server.js" __SOURCE_DIRECTORY__
```

versions:

λ node --version
v14.8.0
λ yarn --version
1.22.4
λ npm --version
6.14.7

.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

**Comment by halcwb** [comment]
Seems this is a very annoying webpack issue, without any resolution: https://github.com/webpack/webpack-cli/issues/299.

**Comment by isaacabraham** [comment]
Closing as it's not a SAFE issue, although the SAFE v2 template (which will be published this week) is much simpler to use around webpack and npm.
