### ISSUE TITLE
Not setting NODE_ENV when bundling for Production

### ISSUE THREAD

**Issue by CallumVass** [SAFE-Stack/SAFE-template#392]
Hi,

I encountered an issue earlier whereby the NODE_ENV was not being set to production when I was running the bundle FAKE task. This caused my CSS to not be purged as part of Tailwind: https://tailwindcss.com/docs/controlling-file-size#setting-up-purge-css-manually

I've got a fix. I installed the cross-env NPM package and then as part of the build script I changed it to this:
`"build": "cross-env NODE_ENV=production webpack -p",`

I'm happy to submit a PR for it if you wish? Just thought I'd make you aware of the issue beforehand.

**Comment by isaacabraham** [comment]
I think that this should be done as part of webpack? @Zaid-Ajaj

**Comment by isaacabraham** [comment]
How did this work in the v1 template - I can't find any NODE_ENV anywhere.

**Comment by CallumVass** [comment]
Do you want me to hold off on the PR for now then?

**Comment by isaacabraham** [comment]
I thought this was just a regression, but seems like this is something we've not supported in the past?

But I *know* we used to set the NODE_ENV flag somewhere - I just can't find where.

**Comment by Zaid-Ajaj** [comment]
> I think that this should be done as part of webpack?

Some tools outside of webpack use this environment variable so it is good to add it there as too just in case

**Comment by isaacabraham** [comment]
I guess this is maybe just about best practice - if NODE_ENV is something that should normally be set, I guess we should do that as well. I'm not sure the best place to add it, nor how to do so across both full and minimal templates.

Can we set the environment variable inside webpack and have it naturally flow through everything else in the build chain (this way we could put it in both webpack files)? Or is there another way to do this?

**Comment by Zaid-Ajaj** [comment]
@isaacabraham It is pretty common to put the command in the npm `build` script like @CallumVass did

**Comment by isaacabraham** [comment]
Putting it in packages.json seems fine - is cross-env necessary for this though or is that for something else aside from just setting the environment variable itself?

**Comment by CallumVass** [comment]
The cross-env package just ensures it sets the environment variable across different platforms in a uniform way as each platform has a different way of setting the environment variable: https://www.npmjs.com/package/cross-env

There might be other options out there, that one just seems to be the biggest recommended one I could see. If you know of anything better I'm happy to swap it out.

**Comment by isaacabraham** [comment]
Not at all. Does it need to be a dependency or can it be a dev dependency?

**Comment by CallumVass** [comment]
Ah - good spot! Sorry Friday afternoon. Will fix :)

**Comment by kulshekhar** [comment]
Doesn't `webpack -p` (the current command) automatically set this?

Running `webpack --help` shows:

```
  -p           shortcut for --optimize-minimize --define process.env.NODE_ENV="production"
```
