### ISSUE TITLE
Remove .NET Standard support from the application.

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#395]
I'm not sure we need .NET Standard TFM support in the app. It's .NET Core 3.1 specific, and removing Standard will simplify the toolchain as well as reduce the size of the paket lock file, making upgrades quicker for everyone.

**Comment by theimowski** [comment]
Does Fable support netcoreapp TFM? I think we use netstandard because of Fable

**Comment by theimowski** [comment]
Just tested the minimal template with netcoreapp3.1 in fsproj - seems to be working fine, so it's probably doable. Haven't checked whether we can use netcoreapp3.1 for FAKE dependencies though

**Comment by isaacabraham** [comment]
@theimowski I suspect not, but even if we just make the main group netcoreapp3.1, this will still simplify things anyway. It wouldn't surprise me if once net5 comes out if Fake just moves to #r nuget anyway.
