### ISSUE TITLE
Add Feliz to template options

### ISSUE THREAD

**Issue by jkone27** [SAFE-Stack/SAFE-template#396]
would be nice to have a simple Feliz option in SAFE template too

https://zaid-ajaj.github.io/Feliz/

I think by default, Feliz looks much simpler and does not require any (useful but not always needed) "Elmish" knowledge,

Awesome work, thanks a lot and have a nice day

**Comment by theimowski** [comment]
There is a [recipe](https://safe-stack.github.io/docs/recipes/ui/add-feliz/) in docs that shows how to easily migrate to using Feliz after creating project from SAFE template.

Given that we want to minimize number of template variants in v2, we currently don't want to add an option to choose between Fable.React and Feliz.

We're actively observing Feliz adoption which indeed seems to be higher and higher - we might switch to Feliz at some point in future.
