### ISSUE TITLE
Inconsistent Usage Documentation and Template Tool Configuration Provisioning

### ISSUE THREAD

**Issue by em-jones** [SAFE-Stack/SAFE-template#399]
The v2.0.0 template does not accommodate [these directions](https://safe-stack.github.io/docs/feature-debugging/).

Can I ask for some feedback/resources that would help me understand changes that were made for v2.0.0? 

Maybe adding a link to the git repo to any community boards/roadmap documentation would be meaningful?

**Comment by isaacabraham** [comment]
@em-jones We have a recipe on how to add this to SAFE v2 which is just in review and should be released this evening, but if you want to look through it now, here it is: https://github.com/CompositionalIT/safe-stack-docs/pull/28/files

**Comment by em-jones** [comment]
@isaacabraham Thank you very much for taking your time to direct me to these resources.
I realize that the company behind this tool has customers to take care of, so the time provided by you to help me out is most appreciated!

**Comment by isaacabraham** [comment]
Not a problem - SAFE is an important tool for us and we're committed to getting the documentation sorted for things like this ASAP :-)
