### ISSUE TITLE
fake build --target bundle errors for template v2

### ISSUE THREAD

**Issue by davedawkins** [SAFE-Stack/SAFE-template#403]
I think it's because the template places these two lines inside a `#if DEBUG` section in `App.fs`

```
open Fable.Remoting.Client
open Shared
```

**Comment by isaacabraham** [comment]
What error do you get? We've been using that target and it worked for us

**Comment by davedawkins** [comment]
Not being able to find definition for `Todo` or Remoting. Let's put this on hold while I check a new instance out and see if I can reproduce to copy actual error messages in to the issue. If I can't reproduce then we'll just close the issue.
