### ISSUE TITLE
Is is possible to get Server to work with net5.0?

### ISSUE THREAD

**Issue by travis-leith** [SAFE-Stack/SAFE-template#413]
I tried but was getting weird paket errors. I updated paket to the latest beta. It tells me that 

```
There was a problem while setting up the environment:
-> Extracting platforms from path 'net5.0' failed, a newer Paket version might support it, otherwise please open an issue for a missing platform handler.
```

**Comment by isaacabraham** [comment]
Looping in @theprash - we've got a prototype up and running.

**Comment by kerams** [comment]
Sure, just update paket to one of the prereleases

```dotnet tool update paket --version 6.0.0-beta3```

**Comment by theprash** [comment]
@travis-leith See here (https://github.com/theprash/SAFE-template/commits/net5.0-fable3) for some changes to the template I've made for our own use. Note that it also includes Fable 3 which still hasn't been properly released yet.

The FAKE dotnet tool is tied to a particular version of paket which doesn't support .NET 5 so I've moved away from `dotnet fake` to `dotnet fsi build.fsx`. This isn't necessarily a "correct" or official approach. Just something that I've done so we can get started with .NET 5 internally.

If you want you can clone my branch and install the template from it. See CONTRIBUTING.md.

**Comment by travis-leith** [comment]
@theprash based on your comment, is it fair to say that we are waiting for a proper fable3 release and better fake/paket support for .Net 5 before we see a SAFE template released for .Net 5?

**Comment by theimowski** [comment]
I started https://github.com/SAFE-Stack/SAFE-template/pull/415 - continuing on top of @theprash  changes
