### ISSUE TITLE
Add new template with a SqLite database built in

### ISSUE THREAD

**Issue by morallito** [SAFE-Stack/SAFE-template#420]
Recently I've faced some issues, putting a SqLite database in the SAFE template. As a beginner i think that It would be more easy to understand some concepts with a database like SqLite. 

Now I want to create a new SAFE template, following the same patterns that SATURN template follows an add it to the CLI. What Is the best way to do it here? Should I create  a private project, finish it and send to SAFE to evaluate it? Or since it's based on this template, should I create a pull request in this repo?

**Comment by olivercoad** [comment]
That would be a good addition. Rather than adding it to the template, it's probably best to [add a recipe](https://safe-stack.github.io/docs/recipes/template/) to the docs, similar to the [LiteDB recipe](https://safe-stack.github.io/docs/recipes/storage/use-litedb/).

**Comment by theimowski** [comment]
Hi @morallito - thanks for your interest in the template. 
Indeed we currently avoid adding too many new features to the template itself, and instead encourage community to share "recipes" on how to integrate SAFE projects with various technologies.
