### ISSUE TITLE
Version 2.2.1 is not discoverable

### ISSUE THREAD

**Issue by mexx** [SAFE-Stack/SAFE-template#421]
I've tried to install the template by running
```
dotnet new -i SAFE.Template
```
However the template doesn't appear in the listing of the installed templates after the command run.

I've tried to create a new project with the template by running
```
dotnet new SAFE
```

The output of this command:
```
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "SAFE-Stack Web App v2.2.0" (SAFE) from author "Tomasz Heimowski" in pack SAFE.Template
    To use this template, run the following command and try again:
        dotnet new -i SAFE.Template::2.2.0
```

For some reason the latest version 2.2.1 is not installed by the first command and not offered by the second one.
Looks like there is some defect in it.

**Comment by theimowski** [comment]
Huh thanks for reporting that. Indeed I've screwed something up when pushing 2.2.1, I'll see if I can release a valid next version

**Comment by theimowski** [comment]
Can you try 2.2.2?

**Comment by theimowski** [comment]
I wasn't aware of the `--update-check` option in `dotnet new` - I'll need to look if there's a feature that SAFE template is not using.

> trying to create without installing offers still the version 2.2.0

I think that's expected? You need to update the template manually to get latest bits, right?
