### ISSUE TITLE
Remove Shared namespace

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#425]
Do we really need `Shared` as a namespace? Why not just leave that a level up? If the user wishes, they can prefix everything with e.g. ProjectName and be done with it.

**Comment by theimowski** [comment]
![image](https://user-images.githubusercontent.com/5909015/108766998-1f6ff400-7556-11eb-8fba-6570e29f452d.png)
If you remove top level namespace then you need to make module top-level, so we'd need to make e.g. `Route` top-level module

**Comment by isaacabraham** [comment]
You can put it in the `global` namespace?

**Comment by theimowski** [comment]
Oh I didn't know you can do that! So literally we'd have something like:
```fsharp
namespace global

module Route =
    let hello = "/api/hello"
```

**Comment by olivercoad** [comment]
I've never seen that before and would probably find it confusing if I saw that without context. If it was my first time using SAFE I might think that shared code has to be directly in the global namespace for some reason and then copy it when making other shared files.

What's the purpose of removing the Shared namespace?

> If the user wishes, they can prefix everything with e.g. ProjectName and be done with it.

If it starts as `Shared` you can do that with just a rename. Not so quick if it starts as `global`.

**Comment by theimowski** [comment]
That's a valid point. I've never used global namespace myself either. @isaacabraham thoughts?

**Comment by isaacabraham** [comment]
True.

I'm just thinking of making it simpler that both client and server can access "common" stuff without a Shared namespace.

Maybe I should create a sample SAFE app with some renames etc. - we can chuck it around and see where it goes?

**Comment by isaacabraham** [comment]
Either that or you have multiple files for each top-level module e.g. Routes etc.. But this feels a bit of an overkill (as it is, I'm not convinced we should even have the Routes module in the minimal template).

**Comment by theimowski** [comment]
I like the Routes module in minimal as it's the only small thingy that you can actually use to share code between server and client
