### ISSUE TITLE
Updating SAFE Documentation for V3

### ISSUE THREAD

**Issue by Akash-Mair** [SAFE-Stack/SAFE-template#437]
Hey guys!

I've put together a list of pages on the SAFE documentation that will need to be updated/added for the latest template

- [ ] Quick Start 
- Components of SAFE
   -  [ ] Learn about Fable
 - The SAFE Template 
    - [ ] The FAKE script 
- How do I...
   - [ ] Upgrade from V2 to V3 (NEW)
   - Build 
      - [ ] Remove FAKE from my project 
      - [ ] Add build automation 
      - [ ] Package my SAFE app for deployment 
      - [ ] Support older browsers 
      - [ ] Create a docker image   
   - Dev / Test 
      - [ ] Test the Client 
      - [ ] Test the Server 
   - Package Management 
      - [ ] Migrate to Yarn from NPM
 
- [ ] Moving current docs into a Legacy V2 section (NEW)

If I've missed something let me know :)

**Comment by theimowski** [comment]
Hi @Akash-Mair  thanks for this, it's gonna be very helpful. Shall we transfer this issue over to docs repository @isaacabraham  ?

**Comment by Akash-Mair** [comment]
Glad it'll help, I'll move this over to the docs :)
