### ISSUE TITLE
Add Saturn backend option 

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#44]
https://github.com/SaturnFramework/Saturn

Together with Fable.Remoting.Saturn for `--Remoting`

**Comment by theimowski** [comment]
@Krzysztof-Cieslak do you have any comments on how this should be done?

I mean in Suave or Giraffe case it's pretty simple to have a single server-side source file from SAFE-template, but for Saturn I know there are some other considerations

**Comment by Zaid-Ajaj** [comment]
As of `Fable.Remoting.Giraffe 2.0`, there is no need to use a seperate package for Saturn, just use the Giraffe adapter with the new CE-based API :
```fs
open Saturn
open Fable.Remoting.Server
open Fable.Remoting.Giraffe

let webApp = remoting server { 
  with_builder routeBuilder
} 

let app = application {
    url "http://127.0.0.1:8083/"
    router webApp
}

[<EntryPoint>]
let main _ =
    run app
    0
```

**Comment by theimowski** [comment]
having issue with `Fable.Remoting.Giraffe 2.0`: https://github.com/Zaid-Ajaj/Fable.Remoting/issues/23
