### ISSUE TITLE
Why does this use mono, when dotnet cli is cross platform?

### ISSUE THREAD

**Issue by NullVoxPopuli** [SAFE-Stack/SAFE-template#45]
just wondering. I'm developing and deploying with docker, so knowing why dependencies are needed is helpful.

**Comment by forki** [comment]
Well this is a temporary requirement until fake 5 is ready and until paket is finally converted to a dotnet tool. It's much harder than expected and unfortunately takes longer than expected. But good news is: this is only for dev environment. No mono needed for production
