### ISSUE TITLE
SAFE v3 -minimal template, no Fable.React

### ISSUE THREAD

**Issue by Akash-Mair** [SAFE-Stack/SAFE-template#451]
Hey @theimowski!

Just noticed that the latest version of the minimal template doesn't include Fable.React, I believe the previous version did any reason in particular why it was stripped out?
(Just noticed as I was updating some docs for a recipe that was for both templates)

Thanks!

**Comment by theimowski** [comment]
That's right - the reason being we going the way of `minimal` being minimal indeed, one might not like to use `Fable.React` but e.g. go fully with Feliz
