### ISSUE TITLE
Error when running the safe-stack template

### ISSUE THREAD

**Issue by Pipsy100** [SAFE-Stack/SAFE-template#452]
Html Webpack Plugin:
  Error: Child compilation failed:
  Module build failed (from ./node_modules/html-webpack-plugin/lib/loader.js):
  Error: ENOENT: no such file or directory, open '/var/www/kentekenkaartuitlezen/_safe/src/Client/inde  x.html':
  Error: ENOENT: no such file or directory, open '/var/www/kentekenkaartuitlezen/_safe/src/Client/inde  x.html'
  
  - compiler.js:79 childCompiler.runAsChild
    [_safe]/[html-webpack-plugin]/lib/compiler.js:79:16
  
  - Compiler.js:343 compile
    [_safe]/[webpack]/lib/Compiler.js:343:11
  
  - Compiler.js:681 hooks.afterCompile.callAsync.err
    [_safe]/[webpack]/lib/Compiler.js:681:15
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [_safe]/[tapable]/lib/Hook.js:154:20
  
  - Compiler.js:678 compilation.seal.err
    [_safe]/[webpack]/lib/Compiler.js:678:31
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [_safe]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1423 hooks.optimizeAssets.callAsync.err
    [_safe]/[webpack]/lib/Compilation.js:1423:35
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [_safe]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1414 hooks.optimizeChunkAssets.callAsync.err
    [_safe]/[webpack]/lib/Compilation.js:1414:32
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [_safe]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1409 hooks.additionalAssets.callAsync.err
    [_safe]/[webpack]/lib/Compilation.js:1409:36

**Comment by theimowski** [comment]
did you place a space in webpack.config.js by mistake? `inde x.html` vs `index.html`?

**Comment by isaacabraham** [comment]
@Pipsy100 Hi. Have you had any luck fixing this or is it still an issue?
