### ISSUE TITLE
Safe apps have npm dependencies missing / out of date

### ISSUE THREAD

**Issue by teknikal-wizard** [SAFE-Stack/SAFE-template#455]
I just installed a package with Femto, and it bumped my React version to 17.x (from 16.x in the default app) and also imported bulma.

It looks like bulma is being pulled in because Fulma is still in the paket dependencies file. We could just remove it now that we use Feliz.Bulma <del>(which doesn't require bulma at all)</del>.

React is being bumped because of Feliz I believe.

**Comment by Nhowka** [comment]
Feliz.Bulma has bulma [added as a requirement](https://github.com/Dzoukr/Feliz.Bulma/blob/master/src/Feliz.Bulma/Feliz.Bulma.fsproj#L16-L20) for Femto.

**Comment by Ryan-Palmer-CIT** [comment]
Ah so it does. It's a bit confusing as the template doesn't come with Bulma but it still seems to work?

Either way, I would think it is a good idea to release a template update after running Femto on it.

**Comment by Nhowka** [comment]
The template kinda cheats and gets it from a CDN, that's why it don't appear to be a dependency. [Check here](https://github.com/SAFE-Stack/SAFE-template/blob/c07383e91111015ec71b6b9c62f3fa5bc141dd06/Content/default/src/Client/index.html#L7)

**Comment by Ryan-Palmer-CIT** [comment]
ahhhh

**Comment by isaacabraham** [comment]
What's the best way forward here - should we be including it again as a dependency? A couple of of the reasons we removed it was:

1. Cut down on bundle size.
2. Ensure we kept the webpack stuff as simple as possible.

**Comment by teknikal-wizard** [comment]
@isaacabraham  just doing the clean up - I'll close this for now as the current template uses React 17. The Bulma npm vs CDN issue can be reopened if there is interested.
