### ISSUE TITLE
Consider adding some basic abstractions into the full template.

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#458]
I think that developers may benefit from having some utilities baked into the template - or perhaps as a separate NuGet package (which would have benefits outside of the template). Things such as:

`Deferred<'T>` and `AsyncOperation<'T>` - this are abstractions that, especially newcomers, could benefit from having "in the box". With suitable "starter" documentation and references to other locations e.g. the Elmish Book, I think that this could be useful.

**Comment by mattgallagher92** [comment]
There were some reservations raised about this in a recent call between SAFE maintainers, largely because there's already a lot of complexity for newcomers.

**Comment by theprash** [comment]
Based on the last comment, I'm closing this.
