### ISSUE TITLE
"build.cmd run" server watch issue

### ISSUE THREAD

**Issue by cotyar** [SAFE-Stack/SAFE-template#46]
Some strange behaviour with "build.cmd run" for server side.
The script's 'run dotnetCli "watch run" serverPath' for some strange reason executes "watch" but not "run" - server doesn't start.
The same time "cd .\src\Server\" + "dotnet watch run" = works as expected.
Bookstore doesn't have this issue, so it's template specific (but it does the command slightly differently so)

**Comment by theimowski** [comment]
can you please list steps to reproduce? I.e. which arguments you use for the template + commands + what's the console output
