### ISSUE TITLE
dotnet run azure exits with errors

### ISSUE THREAD

**Issue by jollyblondgiant** [SAFE-Stack/SAFE-template#461]
Build an app using the template. 
dotnet run bundle => works just fine
dotnet run azure => 1) site name already taken ; 2) resource group location default to West Europe not mentioned in docs ; 3) updating site name in Build.fs leads to InternalServerError and BadRequest error messages 

deploying the plain template to azure works just fine too, can't find what's causing my issue. is there a better way to debug azure deployment errors?

**Comment by isaacabraham** [comment]
Hi @jollyblondgiant!

* If the site name is already taken, you'll always only get an error after deployment. 
* If you pick a site which doesn't conform to Azure App Service naming restrictions, the same will happen (see [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftweb) under **sites**).

Farmer (the technology that does the deploys) detects some of these before deploying but I believe that it doesn't trap all of them for App Service - something we should add.

Could you tell us the name of the web app that you changed to and a little more about the error messages (InternalServerError / BadRequest etc.) - where did they occur? 

Ta
