### ISSUE TITLE
dotnet new -i SAFE.Template requires version on some clients

### ISSUE THREAD

**Issue by zdfowler** [SAFE-Stack/SAFE-template#478]
We are having mixed results with dotnet new -i for the 3.1.1 template. On some machines the full version name is required to pull it down (`dotnet new -i SAFE.Template::3.1.1`) On others, the version number isn't required (`dotnet new -i SAFE.Template works`).

Referencing https://www.nuget.org/packages/SAFE.Template/, the install sample _includes_ the version spec, but previous versions and the docs do not indicate that is required.

Not sure if this is a packing issue or a client machine issue. Anyone else having trouble?

Thanks!

**Comment by isaacabraham** [comment]
Do you have any `global.json` files floating around in the folder structure? I've noticed this sometimes - it'll pull down a different version depending on which version of .net core the implicit context is bound to.

**Comment by zdfowler** [comment]
FWIW -- we did not pursue any further. We updated the pull to use a specific version as noted above and moved on.  Appreciate the conversation. Not solved, but the workaround was clearly sufficient.

@isaacabraham - No.  It was a clean working directory.
