### ISSUE TITLE
documentation of prerequisites: first time build: mono required

### ISSUE THREAD

**Issue by xtofl** [SAFE-Stack/SAFE-template#48]
After following the instructions in the README.md, on Ubuntu 16.04, I run `build.sh run` and get as output: `build.sh line 24: mono: command not found`.

Maybe that was missing in the requirements?

**Comment by Zaid-Ajaj** [comment]
Yeah mono is required to run paket and FAKE, porting both paket and FAKE to dotnet core is work in progress 

> I think as F# devs, we just assumed you have mono installed because we use paket and FAKE all the time

**Comment by theimowski** [comment]
Thanks, added to README
