### ISSUE TITLE
Using safe stack with dotnet 6

### ISSUE THREAD

**Issue by EverybodyKurts** [SAFE-Stack/SAFE-template#481]
Hey all,

I've been trying to get the safe stack template working with dotnet 6 but I've run into errors. The link below is a fresh install from the safe stack template, with upgrades from `net5.0` to `net6.0` and upgrades of the dotnet tools to their latest versions (Fable, Femto, etc).

https://github.com/EverybodyKurts/MySafe6App

There are 2 problems:
1. Ionide can't seem to find the `Fake` modules in `Build.fs` or `Helpers.fs`. Rider doesn't experience the same problems.
2. `dotnet run` runs but then errors out at the `webpack` compilation stage.

<img width="1552" alt="Screen Shot 2021-11-21 at 12 26 41 PM" src="https://user-images.githubusercontent.com/879734/142858366-e728ebdd-05c8-4c61-ae36-b75b9b5376ca.png">

**Comment by olivercoad** [comment]
Just tried testing it. Thanks for the simple repro repo.

1. The `Build.fs` is fine for me. That said, Ionide can be a bit buggy sometimes. I find closing a `.fs` file a reopening often helps, or reloading the entire window. (And it's really inconsistent, sometimes reloading the entire VSCode window doesn't help but then closing and reopening just that file tab does)

2. Can reproduce the same error. There was another issue that had a similar error message #483. Indeed, commenting out `open Elmish.HRM` in `App.fs` seems to make it work. I wonder if it's to do with an update to that package.

**Comment by olivercoad** [comment]
It works if you pin the version of `Fable.Elmish.HMR` to `4.1`

**Comment by EverybodyKurts** [comment]
<img width="1552" alt="Screen Shot 2021-11-25 at 9 55 22 AM" src="https://user-images.githubusercontent.com/879734/143463194-90264770-7bee-4c3a-887d-83bdcbf93160.png">

No joy :(

I ran `dotnet paket update` and it still throws that error.

**Comment by olivercoad** [comment]
Hmm IDK then. If I clone your repo and pin Fable.Elmish.HMR to 4.1 and don't change anything else then it works fine. Did you do a `dotnet paket install` after changing `paket.dependencies`? Can you confirm that pinning the version actually worked by checking `paket.lock`?

**Comment by olivercoad** [comment]
Oh, in the screenshot the tab has white circle meaning it's bean edited but not saved. Maybe you just forgot to actually save the changes?

**Comment by EverybodyKurts** [comment]
![I'm not a smart man](https://c.tenor.com/YQv2NMgnGmoAAAAC/tom-hanks-forrest-gump.gif)

Oh yea, duh. That did it and now Webpack successfully compiled! Thank you for the help!

**Comment by olivercoad** [comment]
Haha no worries. Can't tell you how many times I've done that 😅
