### ISSUE TITLE
Add support for Fable JSON serialization

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#49]
I think that if using either Giraffe or Saturn, the templates should include the Fable.Json package and have them auto-configured as part of the template.

Happy to help with this if you agree that this is worth doing!

**Comment by theimowski** [comment]
I agree, this should be the default option when not using the `--Remoting` flag, where the serialization is then handled by `Fable.Remoting` 

In future we could add option to exclude any auto configuration of JSON serialization if one has a desire to do os.
