### ISSUE TITLE
Server test is throwing NRE due to F# known issue

### ISSUE THREAD

**Issue by Ryan-Palmer-CIT** [SAFE-Stack/SAFE-template#492]
Currently the Server test throws a null reference exception when adding a Todo.

I believe this is due to [a known F# issue](https://github.com/fsharp/fsharp/issues/892)

We could add an explicit entry point or revert to using a class for the Storage instead of a module?

I also think this, along with the broken tests when the class was first replaced with a module, are a strong case for us running the content unit tests in the CI pipeline in addition to the template ones.

**Comment by Ryan-Palmer-CIT** [comment]
@isaacabraham

**Comment by theimowski** [comment]
I don't think this is related to the issue you linked - the `[<EntryPoint>]` attribute is there and has been before the changes. 
To me it seems that there's some issue with `todos` ResizeArray not being initialised for some reason.
Anyway thanks for noticing that - needs to be fixed before we release next template version. 
:+1: for adding unit tests to CI - see #493

**Comment by Ryan-Palmer-CIT** [comment]
I was told yesterday on Slack that upgrading the tests project to .NET 6 fixes the issue as well, and that someone is working on an update. I haven't tried this myself though yet.

**Comment by olivercoad** [comment]
> If I were to choose, I'd revert back to the class approach, but that's just me :)

Is that just because of this issue or other reasons?
