### ISSUE TITLE
Switching to paket from the minimal template results in build error

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-template#501]
1. Run the safe template in minimal mode: `dotnet new safe -m`
2. Install paket tool: `dotnet tool install paket`
3. Convert from nuget: `dotnet paket convert-from-nuget`
4. Try a build `dotnet build`

I get a build error:

>  error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 6.0.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.AspNetCore.Authentication.JwtBearer 6.0.1 supports: net6.0 (.NETCoreApp,Version=v6.0) [C:\Development\lab\TestMinimal\TestMinimal.sln]

on my machine:

.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.403\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

**Comment by halcwb** [comment]
When I manually set the ".JwtBearer" to 5.0.2 in the paket.lock file it works. Probably a paket thing?

**Comment by teknikal-wizard** [comment]
Hello! I just tried this out on the most recent SAFE template (4.0.0) and it worked properly, so I'll close the issue now.
