### ISSUE TITLE
It seems that the minimal and default template are out of sync?

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-template#502]
I tried starting from the minimal template and then add functionality. But I ran into issues where for example the default template has been upgraded to webpack 5 and the minimal still uses the 4 version.

**Comment by theimowski** [comment]
Both default and minimal are using webpack 5.65 at current master branch - though this change has not yet been released: 
https://github.com/SAFE-Stack/SAFE-template/blob/4580061b78423dea6dbcc3f3ed722e2588a6912e/Content/minimal/package-lock.json#L6852-L6853
https://github.com/SAFE-Stack/SAFE-template/blob/4580061b78423dea6dbcc3f3ed722e2588a6912e/Content/default/package-lock.json#L8256-L8257
