### ISSUE TITLE
Pulumi to make the template multi-cloud?

### ISSUE THREAD

**Issue by jkone27** [SAFE-Stack/SAFE-template#503]
Could we use Pulumi DSL to make the template a multi-cloud template,
not only Azure ? 

just an idea

https://github.com/UnoSD/Pulumi.FSharp.Extensions

Amazing template!

**Comment by theimowski** [comment]
We're trying to avoid giving too many options - it's much harder to maintain. But definitely there would be value in adding a recipe to the docs on how to integrate with Pulumi

**Comment by theprash** [comment]
@jkone27 As discussed above this won't become part of the template, but we would welcome a new [recipe](https://safe-stack.github.io/docs/recipes/template/) or even a repo where you have converted a SAFE template project to use Pulumi as that would be a great basis for someone to write a recipe.

**Comment by theprash** [comment]
I'm closing this as no one has offered to create the recipe.
