### ISSUE TITLE
Client-server communication doesn't work with type "Map<'a option, 'b>" when the key is "None"

### ISSUE THREAD

**Issue by reneederer** [SAFE-Stack/SAFE-template#505]
Hi,

you can replicate the error by cloning https://github.com/reneederer/maptest

Basically, I created a new SAFE project from the template and changed ITodosApi in Shared.fs to
```type ITodosApi =
    { getTodos: unit -> Async<Map<int option, Todo list>>
      addTodo: Todo -> Async<Todo> }
```

When the call to getTodos returns a Map with a "None" key, the client throws an error:
```Input string was not in a correct format.```

**Comment by kerams** [comment]
This could potentially be a Fable.SimpleJson problem.

**Comment by theprash** [comment]
@reneederer This is an issue with https://github.com/Zaid-Ajaj/Fable.Remoting so please could you raise an issue there? Thank you.
