### ISSUE TITLE
Error loading npm-installed fonts via SCSS

### ISSUE THREAD

**Issue by mattgallagher92** [SAFE-Stack/SAFE-template#527]
With the default SAFE Template, importing an npm-installed font via SCSS doesn't work. Errors are shown in the console stating "OTS parsing error: invalid sfntVersion".

Replacing the following line in the `webpack.config.js` with `type: 'asset'` resolved the issue.

https://github.com/SAFE-Stack/SAFE-template/blob/fc97e144863b850461d4d6060b84c31b9f5c56fd/Content/default/webpack.config.js#L126

More details about webpack asset modules at https://webpack.js.org/guides/asset-modules/

## Repro

You can see a simple repro at https://github.com/mattgallagher92/safe-fonts-bug-repro.

Before installing the font (https://github.com/mattgallagher92/safe-fonts-bug-repro/commit/b8254a7ae5e2612f67bc10b2ea20ea983a856e7e):
![Standard SAFE Todo list. The targeted item does not have the correct typeface.](https://user-images.githubusercontent.com/46973220/189375920-99815df8-609c-42cb-b991-91889c9afd73.png)

After installing the font (https://github.com/mattgallagher92/safe-fonts-bug-repro/commit/14c86f432ed34f1f89d7c670434440ca49628fcb):
![Browser console showing OTS parsing errors](https://user-images.githubusercontent.com/46973220/189376348-b90a5c02-4020-434e-8ba1-19643cd09857.png)

After updating webpack config (https://github.com/mattgallagher92/safe-fonts-bug-repro/commit/9037df9354f567ce8ed613a4eb68fb553bcdef26):
![Standard SAFE Todo list. The targeted item has the correct typeface](https://user-images.githubusercontent.com/46973220/189376579-8334cb7b-e638-42d5-b567-4d2988d5545d.png)

## Question

Should this change (replacing `use: ['file-loader']` with `type: asset`) be reflected in the SAFE template? Should we be using `type: asset/resource` instead (at least for font files)? I'm not experienced enough with webpack to be sure of the consequences of this change.

**Comment by mattgallagher92** [comment]
@isaacabraham can you recommend anyone(s) to ask for advice on this?

**Comment by isaacabraham** [comment]
Any ideas @MangelMaxime ?

**Comment by MangelMaxime** [comment]
I stopped using Webpack in favor of Vite.js since 2 years now. 

So I don't have a string opinion on it no, you can try to look at how https://github.com/MangelMaxime/fulma-demo does it. It is still using Webpack 5

**Comment by Larocceau** [comment]
Webpack is being replaced by vite in #564. We can close the ticket as soon as that is merged
