### ISSUE TITLE
Move from fantomas-tool to fantomas

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#529]
With the imminent release of Fantomas 5, we should upgrade the `dotnet-tools.json`:

```diff
-"fantomas-tool": {
+"fantomas": {
-  "version": "4.7.1",
+  "version": "5.0.0",
  "commands": [
    "fantomas"
  ]
},
```

We also need to update `.editorconfig` as follows:

```diff
-[src/Client/*.fs]
-# Feliz style
-fsharp_single_argument_web_mode=true
+fsharp_multiline_block_brackets_on_same_column = true
+fsharp_experimental_stroustrup_style = true
```

**Comment by isaacabraham** [comment]
@nojaf is this roughly correct?

**Comment by nojaf** [comment]
Yes, that will do the trick.

On a side note:
I would also advise to change `insert_final_newline = false` to `true`.
See [link](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)

**Comment by isaacabraham** [comment]
Will do. Any reason why this isn't the default then? :-)

**Comment by nojaf** [comment]
It is the default in Fantomas, but the `.editorconfig` of the template seems to have put it on `false`.
