### ISSUE TITLE
Updates to the template are not being released

### ISSUE THREAD

**Issue by jwthomson** [SAFE-Stack/SAFE-template#565]
There have been no releases for a long time, despite PRs being merged in.

I noticed that I was having problems with package versions when removing packages and I came here to discusss pinning versions but I notice that it is already resolved as of #559. The problem is that it was never released!

Is this something which we should be doing?

**Comment by Larocceau** [comment]
templates are nuget packages, https://www.nuget.org/packages/SAFE.Template. The package is currently owned by @theimowski. I will ask him to transfer ownership of the package as soon as I know which account he should transfer it to. I think we might want to create an organsation on nuget for the SAFE-Stack project.

**Comment by Larocceau** [comment]
@theimowski could you make the nuget account Compositional-IT owner of the SAFE.Template package, so we can continue releasing template versions?

**Comment by theimowski** [comment]
Hi, sorry for being inactive recently. I'll do my best to publish a new version during coming week. I'm happy to add CompositionalIT tem as maintainer of the NuGET package as well so that they can release as well

**Comment by theimowski** [comment]
I've just released version [4.3.0](https://www.nuget.org/packages/SAFE.Template/4.3.0) and invited [Compositional-IT](https://www.nuget.org/profiles/Compositional-IT) account to NuGET owners @isaacabraham 

Again, apologies for the delay. Busy dad is busy, but hoping to find some time for OSS contributions from now on :)

**Comment by mattgallagher92** [comment]
Thanks @theimowski, I've accepted your invitation, so Compositional IT is now a joint owner of the NuGet package :heart: 

No worries for the delay :slightly_smiling_face: your OSS contributions are a gift to the community and it's reasonable to have other priorities! We should now be able to share the load in future :slightly_smiling_face:

**Comment by theprash** [comment]
Tomasz provided some release instructions which I'll leave here for now (they should go into CONTRIBUTING.md eventually)

1. Add entry to RELEASE_NOTES.md with new version, date and release notes
2. Set NUGET_KEY env var
3. Run `dotnet run --project Build.fsproj -- release`
