### ISSUE TITLE
SAFE Stack v5

### ISSUE THREAD

**Issue by theprash** [SAFE-Stack/SAFE-template#569]
This issue is for tracking everything we need to do for v5 of SAFE Stack, which we plan to release this month.

Template changes (PR #564):

- [x] Upgrade SDK to .NET 8
- [x] Upgrade runtime to .NET 8
- [x] Upgrade to Fable 4
- [x] Update Fable dependencies
- [x] Use Vite (instead of Webpack)
- [x] Use Tailwind for styling
- [x] Verify minimal template
- [x] Verify Azure deployment
- [x] Review and merge PR
- [x] Fix formatting
- [x] Update release notes and versions
- [x] Release template
- [x] Remove unnecessary type annotations
- [x] Consider accepting the PR for Fun.Build (not mandatory - can be postponed)

Other:

- [x] Update docs (https://github.com/SAFE-Stack/docs/issues/290)
- [x] Update sample repos like SAFE Search (or mark them as obsolete)
- [x] Close any issues relating to the previous version that no longer apply

**Comment by ciphertools** [comment]
I hope you don't mind this comment as I have nothing useful to add to the work that you are doing, except to say that I am really grateful and that I am very much looking forward to the next version of the SAFE Stack template (even though the current one is still great!).

**Comment by isaacabraham** [comment]
I'm reviewing the deps + lock files - to my mind they aren't at a state that I want them to be.

**Comment by martinbryant** [comment]
> I'm wondering whether to include the lock file in the upgrade instructions (it's ~200 lines) and then simply recommend "any custom packages that you have added will need to be added again".
> 
> What do you think @martinbryant @mattgallagher92 ? This might be easier / safer than having people regenerate a lock file?

@isaacabraham that is what has been done on the previous version upgrade recipes - it says overwrite the files with one from the current version of the template, which we should link to tbh
