### ISSUE TITLE
Successfully upgraded to SAFE-template version 5! But missing guidelines with server client setup.

### ISSUE THREAD

**Issue by halcwb** [SAFE-Stack/SAFE-template#583]
First of all, great that SAFE-stack is now fully on the latest F#, dotnet, etc.. versions!

I also used the upgrade recipe, however, I think this only involves a client setup. It should be really useful to have some more documentation on how to:

1. Use a server client setup
2. Add docker support
3. Use JSX literals 
4. Add more js libs using femto
5. etc...

A problem I ran into is that a `vite build` seems to behave differently from what it used to be regarding parsing the fable generated jsx files, see issue: https://github.com/fable-compiler/Fable/issues/3642.

For my current upgrade, see: https://github.com/halcwb/GenPres2/commit/54cf8ad37df6f6d16191d5818cd1ff31b400e24c

Thanks

**Comment by martinbryant** [comment]
Hi @halcwb 

Thanks for your comment.

- The upgrade recipe from V4 to V5 assumes going from the base V4 template and includes upgrades to client and server(the Server only needs package upgrades and the code remains the same) 
- The docker recipe is now live
- So I can see that Fable and Femto include documentation for using JSX literals and adding JS libraries respectively

Please have a look at the current SAFE stack docs and if you can suggest anything else you would like to see then we would be happy to have a look into it.

**Comment by martinbryant** [comment]
@halcwb Let me know if I can assist with anything else upgrade wise. 

Please feel free to open an issue at https://github.com/SAFE-Stack/docs if you have any ideas for documentation you would like to see
