### ISSUE TITLE
Enable discussions

### ISSUE THREAD

**Issue by mattgallagher92** [SAFE-Stack/SAFE-template#592]
Pros:

- Would have been useful instead of an issue for https://github.com/SAFE-Stack/SAFE-template/issues/588
- Might encourage further discussions if people are put off by the idea of raising an issue
- Could be a good place to gather feedback on things like "should we continue to maintain the minimal template"
- More at [about discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions)

Cons:

- One more place to check
- Potentially unclear when a discussion is resolved

[Done via repo settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository), which can only changed by a SAFE Stack org owner.

**Comment by theprash** [comment]
Good idea. Yes, I think it we should try out enabling discussions. It would be good to encourage more discussion and engagement.

And also to keep issues mainly as a list of fairly well defined and planned work, which are hopefully not long-lived.

**Comment by isaacabraham** [comment]
Done
