### ISSUE TITLE
Add Elmish.Browser to basic set of deps

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#60]
Should we add Fable.Elmish.Browser to paket.dependencies for the client? Even if it's not necessarily used in the basic template code, at least it's there for when people inevitably want to start using it.

I know that this is a bit of a slippery slope - we need to be careful of not adding the whole world to the template etc., but perhaps this one is worthwhile?

**Comment by theimowski** [comment]
I'd prefer to preserve a minimal set of initial dependencies. 
I think there are valid cases where users do not need the navigation functionality from Fable.Elmish.Browser, so that would be simply redundant for them.

**Comment by isaacabraham** [comment]
How do people handle browser integration for e.g. routes without the browser dependency?

**Comment by theimowski** [comment]
What I meant were very simple apps not using routes at all. But it might be I'm wrong assuming that people build those kind of apps anyway?

**Comment by isaacabraham** [comment]
Yes, you're probably right, that could well be the case - I imagine though that most applications will at some point want some support for routing, at which point the next question will be "which dependency do I download".

We shouldn't add it to the code in the template, definitely. But does having one more dependency matter? I don't mind either way - just thinking aloud here. Any thoughts @forki ?

**Comment by isaacabraham** [comment]
Perhaps an alternative way around this is to provide some docs on the site with a list of optional extra dependencies, with things that people might need as their sites grow larger?

**Comment by theimowski** [comment]
that would be the best - I'd rather keep the deps to minimum required. Adding this dependency after creating from template, should be a matter of single `paket add` invocation

**Comment by isaacabraham** [comment]
Happy to close this then.
