### ISSUE TITLE
Server.fs/Client.fs cannot resolve dependencies after a fresh install

### ISSUE THREAD

**Issue by KarandikarMihir** [SAFE-Stack/SAFE-template#63]
I'm new to F# and .net core so this might not be a real issue. When I installed the template and scaffolded out a project, all I could see is red underlines in any file I open. Although, the project runs just fine with `./build.sh run`. I'm on Ubuntu. Have a look at the screenshot -

![screenshot from 2018-04-23 20-07-41](https://user-images.githubusercontent.com/17466938/39133563-22e99ba4-4732-11e8-9b4a-d5c9c689efce.png)

**Comment by forki** [comment]
1) do you have ionide f# extension installed in vs code?
2) you need to run "build.sh run" before you open code, so that everything is already installed

**Comment by theimowski** [comment]
also you might check out VS Code `Reload Window` command to see if it gets fixed after `build.sh run` is triggerred

**Comment by KarandikarMihir** [comment]
@forki Yes I'm using ionide extension. I ran `build.sh` too.. @theimowski Happens even if I close VS code reopen it.

Weird thing is that the project runs in the browser just fine.

**Comment by Zaid-Ajaj** [comment]
@KarandikarMihir Try deleting all `obj` and `bin` directories and `./build.sh run` again. It will reset the cache for the project. Also you can modify the `Clean` build target to perform the cache resetting everytime you build:
```fs
// Before
Target "Clean" (fun _ -> 
  CleanDirs [deployDir]
)

// After
Target "Clean" <| fun _ -> 
  [deployDir
   "src" </> "Client" </> "bin" 
   "src" </> "Client" </> "obj"
   "src" </> "Server" </> "bin" 
   "src" </> "Server" </> "obj" ] 
  |> CleanDirs 

```

**Comment by theimowski** [comment]
Let us know if deleting `obj` helps - if so we should bake it into the script

**Comment by KarandikarMihir** [comment]
@Zaid-Ajaj @theimowski I cleared `obj` and `bin` but no joy. I wonder what am I missing. If it was a mono or dotnet core issue, the project wouldn't run, but it does run in the browser.

I have these plugins installed in VS Code- 
- Ionide-FAKE
- Ionide-fsharp
- Ionide-Paket

Off topic - Why does the sdk version in `global.json` say 2.1.3? AFAIK [there is no 2.1.3 version](https://github.com/dotnet/core/releases) of dotnet core, is there?

**Comment by tsctao** [comment]
Try to install latest version of dotnet core SDK.

**Comment by theimowski** [comment]
yes the sdk version in global.json should probably be updated. There used to be a released 2.1.3 version one day, but cannot find it right now

**Comment by KarandikarMihir** [comment]
I had to switch to Windows for this to work. :neutral_face: I wish it worked on Linux. Any way. Thanks for this awesome template.

**Comment by theimowski** [comment]
@KarandikarMihir - new version of the template makes use of dotnet SDK 2.1.105 can you try this one to see if editor support is correct now on Ubuntu?

**Comment by isaacabraham** [comment]
@theimowski in the SAFE training course we did last month, we had two delegates that used Linux and both were able to use the SAFE template without a problem (although the raw Fable template didn't work for them!).

**Comment by theimowski** [comment]
Closing for now, please open if the issue persists
