### ISSUE TITLE
Update webpack and add webpack-cli

### ISSUE THREAD

**Issue by forki** [SAFE-Stack/SAFE-template#76]
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D

**Comment by forki** [comment]
I did `yarn upgrade --latest` and it broke.

@theimowski can you please do `yarn upgrade --latest` and `yarn add webpack-cli -D` in the template?

**Comment by MangelMaxime** [comment]
I am on it
