### ISSUE TITLE
use babel-preset-react

### ISSUE THREAD

**Issue by forki** [SAFE-Stack/SAFE-template#78]
we should use     "babel-preset-react": "^6.24.1"` in package.json

and change the webpack.config.js to:

    var babelOptions = fableUtils.resolveBabelOptions({
      presets: [
        "stage-0",
        [ "env", {
          "targets": {
            "browsers": ["last 2 versions"]
          },
          "modules": false
        }],
        "react"
      ],
      plugins: [
          "transform-runtime",
          "transform-object-rest-spread",
          "transform-class-properties"]
    });

**Comment by isaacabraham** [comment]
Apologies for my lack of knowledge here - what does this improve?

**Comment by MangelMaxime** [comment]
This is needed for my project because I have a react component written in JavaScript.

Every project don't need part:

```js
    "react"
  ],
  plugins: [
      "transform-runtime",
      "transform-object-rest-spread",
      "transform-class-properties"]
```

**Comment by MangelMaxime** [comment]
In current form of the template there no impact, it will just do nothing.

**Comment by theimowski** [comment]
closing then for now
