### ISSUE TITLE
Fake target `InstallDotNetCore`

### ISSUE THREAD

**Issue by MangelMaxime** [SAFE-Stack/SAFE-template#79]
Do we really need the `InstallDotNetCore` target ?

If the user want to use the template they need to have `dotnet` already installed. I am asking because, when contributing to a new project this is really painful to have this target. 

I always comment it so it doesn't download dotnet each time I switch from one project to another. 

But perhaps there is good reason for it.

**Comment by isaacabraham** [comment]
I think the only way it can be useful is if it upgrades the local machine when we upgrade the template to the latest SDK. But for clean machines there's no point is there?.

**Comment by MangelMaxime** [comment]
Upgrading local machine can be seen as dangerous I think. It will not impact only the template but all the project on the user system.

**Comment by isaacabraham** [comment]
Agreed. I'm happy to remove that task.

**Comment by forki** [comment]
I vote to keep it. It's very useful for the rest of the team and it upgrades the stuff for everyone if you touch global.json

**Comment by isaacabraham** [comment]
I think that's a separate concern though. I've been burned by this - what if you run a project with an old project.json and it overwrites what you already have? Alternatively, you may not want to upgrade - this happens without your evening knowing.

**Comment by isaacabraham** [comment]
I think that's a separate concern though. I've been burned by this - what if you run a project with an old project.json and it overwrites what you already have? Alternatively, you may not want to upgrade - this happens without your evening knowing.

**Comment by forki** [comment]
not project.json - global.json 

and that file is .NET Core best practice

**Comment by isaacabraham** [comment]
Yeah, sorry - typo. I know they're different :-) Still not sure that's really what we want but open to being educated :-)

**Comment by MangelMaxime** [comment]
If you think this is the good way I am ok with that :)

It's just take forever (5 to 15minutes) to do the first build. And I suppose my issue is more because I work on a lot of project and it's annoying when each one download his own version of dotnet by erasing the previous ones.

What I am trying to say, his perhaps this not an issue for SAFE-Template because in general people with want to use it for their work and not some OSS project.

**Comment by forki** [comment]
It won't take forever if you already have the correct version.

**Comment by MangelMaxime** [comment]
Perhaps, we could simply make it an option in the template ?

**Comment by forki** [comment]
sure that would work

**Comment by isaacabraham** [comment]
And turn it off by default. Especially if you have multiple projects this will just end up ping-ponging between versions.

**Comment by theimowski** [comment]
If we make it an option, no one is ever going to use it I'm afraid. 
Is there any ready-to-use mechanism to use global.json file, but just warn if an older dotnet version is installed instead?

**Comment by jarcane** [comment]
This actually broke my setup today. The template created a project with .NET Core 2.1.105, when I already had 2.1.300 installed. The build went off fine, eventually, but Ionide couldn't get any of the projects to work, which I then learned was because somehow my local tools had broken as well due to the mismatched version.

Changing global.json to 2.1.300 and reinstalling the SDK fixed it, but it was a nasty surprise.

**Comment by forki** [comment]
I think a netcore2.1 version will be released soon

Am Di., 12. Juni 2018 um 17:20 Uhr schrieb Annaia Berry <
notifications@github.com>:

**Comment by theimowski** [comment]
Yes it's still in progress https://github.com/SAFE-Stack/SAFE-template/pull/101

**Comment by isaacabraham** [comment]
I notice that the FAKE build script also is coupled to a specific version of dotnetcore - so we now have global.json *and* FAKE pointing to (currently) 2.1.3. I can see people changing one but not other other etc. etc.

**Comment by MangelMaxime** [comment]
Better to have one source of truth :) And `global.json` seems the right place.

**Comment by theimowski** [comment]
I've decided to remove "Install dotnet" step for now - https://github.com/SAFE-Stack/SAFE-template/commit/e4462c98116e9b93dbf66aefaf1335a7eca853ea 

Let's see what people think of it - if you encounter issues please reopen
