### ISSUE TITLE
Create a 1.0 milestone

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#83]
We should look to target a 1.0 release of the template as soon as possible. What is outstanding in order to do that? Any blockers? Are there any specific features that are missing that we need to add?

**Comment by theimowski** [comment]
It's rather just me affording to introduce breaking changes all the time, without any worries :)
A really minor issue for 1.0 would be #57 
And maybe #70

**Comment by theimowski** [comment]
I created 1.0 milestone, we can continue to discuss here what else should be there

**Comment by isaacabraham** [comment]
#57 seems like a good one because it's a breaking change. We should maybe also change the NPM one to a packagemanager command that's either yarn or NPM.

#70 would be great although I'm not sure how easy that will be to do / how much effort it is?

**Comment by isaacabraham** [comment]
Closing.
