### ISSUE TITLE
No solution file

### ISSUE THREAD

**Issue by vasily-kirichenko** [SAFE-Stack/SAFE-template#86]

**Comment by forki** [comment]
I guess a sln would be a good thing for people who don't use ionide

Vasily Kirichenko <notifications@github.com> schrieb am Fr., 4. Mai 2018,
20:28:

**Comment by isaacabraham** [comment]
Someone was also asking for this in Slack (albeit for the zebra template)

**Comment by forki** [comment]
Only argument against it is that dotnet new doesn't create it. But since
this scaffolds whole stack I think we should do it

Isaac Abraham <notifications@github.com> schrieb am Sa., 5. Mai 2018, 14:08:

**Comment by theimowski** [comment]
👍 
Is there any new, recommended format for solution files, similar to new-sdk-project format?
Or would it be simply one generated from VS 2017?
