### ISSUE TITLE
More beautiful styling

### ISSUE THREAD

**Issue by vasily-kirichenko** [SAFE-Stack/SAFE-template#87]
I'm sorry, but this is just too simple and ugly to catch attention:

![image](https://user-images.githubusercontent.com/873919/39646657-cd1d0bbe-4fe4-11e8-86d2-8cda0bbbbc9c.png)

Maybe adding Fulma by default can help?

**Comment by vasily-kirichenko** [comment]
Ah, there is `--Fulma` option. Closing this.

**Comment by forki** [comment]
Maybe we should make fulma a default?

Vasily Kirichenko <notifications@github.com> schrieb am Fr., 4. Mai 2018,
20:54:
