### ISSUE TITLE
Errors on new project

### ISSUE THREAD

**Issue by Banashek** [SAFE-Stack/SAFE-template#91]
OS: MacOS 10.13
Dotnet Version: 2.1.4
Latest Ionide plugins installed
Command run to scaffold: `dotnet new SAFE -lang F\# --Fulma admin --Remoting --Deploy azure`

Errors on `./build.sh run`:

```
src/Server/Server.fs(29,30): error FS0039: The type 'IServiceCollection' is not defined. [src/Server/Server.fsproj]
src/Server/Server.fs(31,17): error FS0072: Lookup onobject of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [src/Server/Server.fsproj]

The build failed. Please fix the build errors and run again.
watch : Exited with error code 1
```

![image](https://user-images.githubusercontent.com/7094571/39899196-734572f4-546f-11e8-9c55-34c9ba8337c2.png)

Specifics for each squiggly in that screenshot:

Line 23:
```
The record label 'getInitCounter' is not defined.
val getInitCounter: 
   : unit 
   -> Task<Counter>
Full name: Server.getInitCounter
Assembly: Server
```

Line 25:
```
The value, namespace, type or module 'Route' is not defined. Maybe you want one of the following:
   route
   Router
   routef
   routex
   routeCi
```

Line 29:
```
The type 'IServiceCollection' is not defined.
```

Line 31:
```
Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
```

**Comment by theimowski** [comment]
looks like Paket didn't restore the packages correctly.
Can you make sure the packages are restored? try `paket restore` or `paket install` if there's no lock file.

If still doesn't help, can you attach whole log from the build?

**Comment by Banashek** [comment]
Looks like a full clean did it. 
Just deleting the paket folder didn't seem enough. 
Some odd caching.
All good now!

**Comment by Banashek** [comment]
Actually it looks like it was still occurring (was doing too many things at once).

Adding `open Microsoft.Extensions.DependencyInjection` to the top fixes it.

Is this supposed to be autoopened in another package?

**Comment by forki** [comment]
Please send a pull request

Banashek <notifications@github.com> schrieb am Sa., 12. Mai 2018, 03:58:
