### ISSUE TITLE
Normalize the indentations

### ISSUE THREAD

**Issue by MangelMaxime** [SAFE-Stack/SAFE-template#92]
The template is sometimes using 2, 3 or 4 spaces indentation. We should have only one indentation types in general it's 4 spaces.

**Comment by forki** [comment]
Yes 4 spaces. Please

Maxime Mangel <notifications@github.com> schrieb am Fr., 11. Mai 2018,
15:05:

**Comment by theimowski** [comment]
argh I got used to 2 spaces, but willing to switch to a standard used more often.
I guess this should go in pair with adding an [editorconfig](http://editorconfig.org/) file
