### ISSUE TITLE
Are all package.json scripts elements needed?

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#98]
Are the following elements needed, considering that we do all of this stuff in the FAKE script? Removing any of this that's not needed would be very useful from a documentation point of view.

```json
  "scripts": {
    "prebuildServer": "dotnet restore src/Server/Server.fsproj",
    "buildServer": "dotnet build src/Server/Server.fsproj",
    "prebuildServerTest": "dotnet restore test/ServerTests/ServerTests.fsproj",
    "buildServerTest": "dotnet build test/ServerTests/ServerTests.fsproj",
    "restoreClient": "cd src/Client && yarn install",
    "restoreNetClient": "dotnet restore src/Client/Client.fsproj",
    "prestartClient": "concurrently \"npm run restoreClient\" \"npm run restoreNetClient\" ",
    "startClient": "cd src/Client && dotnet fable webpack-dev-server"
  }```

**Comment by theimowski** [comment]
good question, need to check what they are for :)

**Comment by isaacabraham** [comment]
I deleted them all, it didn't *appear* to make a difference :-)

**Comment by Krzysztof-Cieslak** [comment]
From quick scanning through our build.fsx it looks like we never call something like `yarn run` in it, just `dotnet` directly (so exactly same what does scripts). I guess the only reason to have those scripts is if someone would want to build app without FAKE (i.e without mono)

**Comment by isaacabraham** [comment]
I think we should remove them. It's confusing.

**Comment by theimowski** [comment]
yes, I'll remove them in 0.24
